- common/msgs/autoware_perception_msgs/CMakeLists.txt
- common/msgs/autoware_perception_msgs/msg/object_recognition/DynamicObject.msg.in
- common/msgs/autoware_perception_msgs/package.xml
> Add ros2 perception msgs

- common/msgs/autoware_control_msgs/CMakeLists.txt
This fixes the issue mentioned here: https://github.com/tier4/Pilot.Auto/pull/6#issuecomment-707485328
It adds missing dependency in CMakeLists.txt
> Fix autoware control msgs

- vendor/osqp_vendor/.github/workflows/build.yml
- vendor/osqp_vendor/CMakeLists.txt
- vendor/osqp_vendor/LICENSE
- vendor/osqp_vendor/README.md
- vendor/osqp_vendor/osqp_vendor-extras.cmake
- vendor/osqp_vendor/package.xml
This is a PR to clean up the botched in #35  merged.
> Osqp vendor 2

- vehicle/remote_cmd_converter/CMakeLists.txt
- vehicle/remote_cmd_converter/include/remote_cmd_converter/node.hpp
- vehicle/remote_cmd_converter/launch/remote_cmd_converter.launch.xml
- vehicle/remote_cmd_converter/package.xml
- vehicle/remote_cmd_converter/src/main.cpp
- vehicle/remote_cmd_converter/src/node.cpp
This ports remote_cmd_converter node to ROS2.
> port remote_cmd_converter

- localization/util/autoware_localization_srvs/srv/PoseWithCovarianceStamped.srv
- localization/util/pose_initializer/CMakeLists.txt
- localization/util/pose_initializer/include/pose_initializer/pose_initializer_core.h
- localization/util/pose_initializer/launch/pose_initializer.launch.xml
- localization/util/pose_initializer/package.xml
- localization/util/pose_initializer/src/pose_initializer_core.cpp
- localization/util/pose_initializer/src/pose_initializer_node.cpp
* Tested the build with ROS2 Foxy by
* following [this](https://docs.google.com/document/d/1eqkWCKHZfHcaY4uvs1eSrIBPU6AZCkyxJI3XoRU1WeU/edit) but entering an AutowareAuto ADE environment instead (Foxy `.aderc` taken from [here](https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/merge_requests/637#note_424910484))
* running `colcon build --packages-up-to pose_initializer` in the `ros2` branch of the AutowareArchitectureProposal repo (with this branch checked out in the `autoware/autoware.iv` sub-repo)
* running the launch file
> Port pose_initializer to ROS2

- awapi/autoware_api_msgs/CMakeLists.txt
- awapi/autoware_api_msgs/msg/AwapiAutowareStatus.msg
- awapi/autoware_api_msgs/msg/LaneChangeStatus.msg
- awapi/autoware_api_msgs/msg/ObstacleAvoidanceStatus.msg
- awapi/autoware_api_msgs/package.xml
> Port autoware_api_msgs to ROS2

- planning/mission_planning/mission_planner/CMakeLists.txt
- planning/mission_planning/mission_planner/include/mission_planner/lanelet2_impl/mission_planner_lanelet2.h
- planning/mission_planning/mission_planner/include/mission_planner/lanelet2_impl/utility_functions.h
- planning/mission_planning/mission_planner/include/mission_planner/mission_planner_base.h
- planning/mission_planning/mission_planner/launch/mission_planning.launch.xml
- planning/mission_planning/mission_planner/lib/mission_planner_base.cpp
- planning/mission_planning/mission_planner/package.xml
- planning/mission_planning/mission_planner/src/mission_planner_lanelet2/mission_planner_lanelet2.cpp
- planning/mission_planning/mission_planner/src/mission_planner_lanelet2/mission_planner_main.cpp
- planning/mission_planning/mission_planner/src/mission_planner_lanelet2/route_handler.cpp
- planning/mission_planning/mission_planner/src/mission_planner_lanelet2/utility_functions.cpp
This ports mission planner to ROS2.
> port mission_planner to ROS2

- planning/scenario_planning/parking/astar_search/CMakeLists.txt
- planning/scenario_planning/parking/astar_search/include/astar_search/astar_search.h
- planning/scenario_planning/parking/astar_search/package.xml
- planning/scenario_planning/parking/astar_search/src/astar_search.cpp
needed by https://github.com/tier4/Pilot.Auto/pull/41.
- Since `tf2::doTransform(Pose, Pose, Transform)` is not in the ROS2 tf_geometry_msgs, it is replaced to `tf2::doTransform(PoseStamped, PoseStamped, Transform)`
> port astar_search to ros2

- planning/scenario_planning/parking/freespace_planner/CMakeLists.txt
- planning/scenario_planning/parking/freespace_planner/include/freespace_planner/freespace_planner.h
- planning/scenario_planning/parking/freespace_planner/launch/freespace_planner.launch.xml
- planning/scenario_planning/parking/freespace_planner/package.xml
- planning/scenario_planning/parking/freespace_planner/src/freespace_planner/freespace_planner_node.cpp
- planning/scenario_planning/parking/freespace_planner/src/freespace_planner/main.cpp
depending on the `astar_search` package. https://github.com/tier4/Pilot.Auto/pull/38
Remarks:
- Since `tf2::doTransform(Pose, Pose, Transform)` is not in the ROS2 tf_geometry_msgs, it is replaced to `tf2::doTransform(PoseStamped, PoseStamped, Transform)`
> port freespace plannet to ros2

- common/math/spline_interpolation/CMakeLists.txt
- common/math/spline_interpolation/include/spline_interpolation/spline_interpolation.h
- common/math/spline_interpolation/package.xml
- common/math/spline_interpolation/src/spline_interpolation.cpp
With this PR, spline interpolation package can be built with ROS2 foxy.
> Port spline interpolation

- localization/pose_estimator/ndt_scan_matcher/ndt_scan_matcher/CMakeLists.txt
- localization/pose_estimator/ndt_scan_matcher/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.h
- localization/pose_estimator/ndt_scan_matcher/ndt_scan_matcher/include/ndt_scan_matcher/util_func.h
- localization/pose_estimator/ndt_scan_matcher/ndt_scan_matcher/launch/ndt_scan_matcher.launch.xml
- localization/pose_estimator/ndt_scan_matcher/ndt_scan_matcher/package.xml
- localization/pose_estimator/ndt_scan_matcher/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
- localization/pose_estimator/ndt_scan_matcher/ndt_scan_matcher/src/ndt_scan_matcher_node.cpp
* This requires https://github.com/tier4/AutowareArchitectureProposal/pull/102
* I replaced `std_msgs::Float32` with `autoware_debug_msgs::msg::Float32Stamped` (and `Int32Stamped` in one case)
* I had to delete `key_value_stdmap_["seq"]` since messages don't have a sequence number anymore
> Port ndt_scan_matcher package to ROS2

- common/math/spline_interpolation/src/spline_interpolation.cpp
Updated logger name when called within the SOR class
> Update logger name for SOR class

- build_depends.repos
Add the dependencies to fix CI failure in #101 and (possibly) #51
> Add topic_tools to build_depend.repos

- awapi/awapi_awiv_adapter/CMakeLists.txt
- awapi/awapi_awiv_adapter/Readme.md
- awapi/awapi_awiv_adapter/include/awapi_awiv_adapter/awapi_autoware_state_publisher.h
- awapi/awapi_awiv_adapter/include/awapi_awiv_adapter/awapi_autoware_util.h
- awapi/awapi_awiv_adapter/include/awapi_awiv_adapter/awapi_awiv_adapter_core.h
- awapi/awapi_awiv_adapter/include/awapi_awiv_adapter/awapi_lane_change_state_publisher.h
- awapi/awapi_awiv_adapter/include/awapi_awiv_adapter/awapi_obstacle_avoidance_state_publisher.h
- awapi/awapi_awiv_adapter/include/awapi_awiv_adapter/awapi_stop_reason_aggregator.h
- awapi/awapi_awiv_adapter/include/awapi_awiv_adapter/awapi_vehicle_state_publisher.h
- awapi/awapi_awiv_adapter/launch/awapi_awiv_adapter.launch.xml
- awapi/awapi_awiv_adapter/package.xml
- awapi/awapi_awiv_adapter/src/awapi_autoware_state_publisher.cpp
- awapi/awapi_awiv_adapter/src/awapi_awiv_adapter_core.cpp
- awapi/awapi_awiv_adapter/src/awapi_awiv_adapter_node.cpp
- awapi/awapi_awiv_adapter/src/awapi_lane_change_state_publisher.cpp
- awapi/awapi_awiv_adapter/src/awapi_obstacle_avoidance_state_publisher.cpp
- awapi/awapi_awiv_adapter/src/awapi_stop_reason_aggregator.cpp
- awapi/awapi_awiv_adapter/src/awapi_vehicle_state_publisher.cpp
Relatively straightforward port.
> Port awapi_awiv_adapter to ROS2

- perception/object_recognition/detection/tensorrt_yolo3/CMakeLists.txt
- perception/object_recognition/detection/tensorrt_yolo3/README.md
- perception/object_recognition/detection/tensorrt_yolo3/include/tensorrt_yolo3_ros.h
- perception/object_recognition/detection/tensorrt_yolo3/launch/tensorrt_yolo3.launch.xml
- perception/object_recognition/detection/tensorrt_yolo3/package.xml
- perception/object_recognition/detection/tensorrt_yolo3/src/tensorrt_yolo3_main.cpp
- perception/object_recognition/detection/tensorrt_yolo3/src/tensorrt_yolo3_ros.cpp
This ports tensorrt_yolo3 to ROS2.
> port tensorrt_yolo3 to ROS2

- common/util/rviz_plugins/autoware_perception_rviz_plugin/CMakeLists.txt
- common/util/rviz_plugins/autoware_perception_rviz_plugin/package.xml
- common/util/rviz_plugins/autoware_perception_rviz_plugin/plugins/plugin_description.xml
- common/util/rviz_plugins/autoware_perception_rviz_plugin/src/tools/car_pose.cpp
- common/util/rviz_plugins/autoware_perception_rviz_plugin/src/tools/car_pose.hpp
- common/util/rviz_plugins/autoware_perception_rviz_plugin/src/tools/delete_all_objects.cpp
- common/util/rviz_plugins/autoware_perception_rviz_plugin/src/tools/delete_all_objects.hpp
- common/util/rviz_plugins/autoware_perception_rviz_plugin/src/tools/pedestrian_pose.cpp
- common/util/rviz_plugins/autoware_perception_rviz_plugin/src/tools/pedestrian_pose.hpp
Port of `autoware_perception_rviz_plugin` to ROS2
> Port autoware-perception-rviz-plugin

- common/util/rviz_plugins/autoware_planning_rviz_plugin/CMakeLists.txt
- common/util/rviz_plugins/autoware_planning_rviz_plugin/include/mission_checkpoint/mission_checkpoint.hpp
- common/util/rviz_plugins/autoware_planning_rviz_plugin/include/path/display.hpp
- common/util/rviz_plugins/autoware_planning_rviz_plugin/include/trajectory/display.hpp
- common/util/rviz_plugins/autoware_planning_rviz_plugin/package.xml
- common/util/rviz_plugins/autoware_planning_rviz_plugin/plugins/plugin_description.xml
- common/util/rviz_plugins/autoware_planning_rviz_plugin/src/mission_checkpoint/mission_checkpoint.cpp
- common/util/rviz_plugins/autoware_planning_rviz_plugin/src/path/display.cpp
- common/util/rviz_plugins/autoware_planning_rviz_plugin/src/trajectory/display.cpp
Port `autoware-planning-rviz-plugin` to ROS2
> Port autoware-planning-rviz-plugin

- perception/object_recognition/prediction/map_based_prediction/launch/map_based_prediction.launch.xml
Fix parameter setting in a launch file.
> [map_based_detection] fix launch file

- control/autoware_joy_controller/CMakeLists.txt
- control/autoware_joy_controller/config/autoware_joy_controller.yaml
- control/autoware_joy_controller/include/autoware_joy_controller/autoware_joy_controller.hpp
- control/autoware_joy_controller/include/autoware_joy_controller/joy_converter/ds4_joy_converter.hpp
- control/autoware_joy_controller/include/autoware_joy_controller/joy_converter/g29_joy_converter.hpp
- control/autoware_joy_controller/include/autoware_joy_controller/joy_converter/joy_converter_base.hpp
- control/autoware_joy_controller/launch/autoware_joy_controller.launch.xml
- control/autoware_joy_controller/package.xml
- control/autoware_joy_controller/src/autoware_joy_controller/autoware_joy_controller_node.cpp
- control/autoware_joy_controller/src/autoware_joy_controller/main.cpp
Port `autoware-joy-controller` to ROS2
> Port autoware joy controller

- planning/scenario_planning/parking/freespace_planner/CMakeLists.txt
- planning/scenario_planning/parking/freespace_planner/include/freespace_planner/freespace_planner.hpp
- planning/scenario_planning/parking/freespace_planner/package.xml
- planning/scenario_planning/parking/freespace_planner/src/freespace_planner/freespace_planner_node.cpp
- planning/scenario_planning/parking/freespace_planner/src/freespace_planner/main.cpp
> Enable lints in freespace_planner

- planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/CMakeLists.txt
- planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/include/surround_obstacle_checker/debug_marker.hpp
- planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/include/surround_obstacle_checker/node.hpp
- planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/package.xml
- planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/src/debug_marker.cpp
- planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/src/main.cpp
- planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/src/node.cpp
And the issues found by clang-tidy
> Fix lints in surround_obstacle_checker package

- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/CMakeLists.txt
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/package.xml
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/plugins/plugin_description.xml
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/console_meter.cpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/console_meter.hpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/jsk_overlay_utils.cpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/jsk_overlay_utils.hpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/steering_angle.cpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/steering_angle.hpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/turn_signal.cpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/turn_signal.hpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/velocity_history.cpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/velocity_history.hpp
Port `autoware_vehicle_rviz_plugin` to ROS2
> Port autoware vehicle rviz plugin

- localization/pose_twist_fusion_filter/ekf_localizer/src/ekf_localizer.cpp
- localization/util/pose_initializer/src/pose_initializer_core.cpp
This fixes topic types for subscribers and publishers in pose_initializer and ekf_localizer
> [ekf_localizer] [pose_initializer] fix topic message type

- perception/object_recognition/detection/lidar_apollo_instance_segmentation/include/lidar_apollo_instance_segmentation/cluster2d.hpp
- perception/object_recognition/detection/lidar_apollo_instance_segmentation/include/lidar_apollo_instance_segmentation/detector.hpp
- perception/object_recognition/detection/lidar_apollo_instance_segmentation/include/lidar_apollo_instance_segmentation/feature_generator.hpp
- perception/object_recognition/detection/lidar_apollo_instance_segmentation/lib/include/TrtNet.hpp
- perception/object_recognition/detection/lidar_apollo_instance_segmentation/lib/src/TrtNet.cpp
- perception/object_recognition/detection/tensorrt_yolo3/include/tensorrt_yolo3_ros.hpp
- perception/object_recognition/detection/tensorrt_yolo3/lib/include/EntroyCalibrator.hpp
- perception/object_recognition/detection/tensorrt_yolo3/lib/include/PluginFactory.hpp
- perception/object_recognition/detection/tensorrt_yolo3/lib/include/TrtNet.hpp
- perception/object_recognition/detection/tensorrt_yolo3/lib/include/UpsampleLayer.hpp
- perception/object_recognition/detection/tensorrt_yolo3/lib/include/YoloLayer.hpp
- perception/object_recognition/detection/tensorrt_yolo3/lib/src/TrtNet.cpp
- perception/object_recognition/detection/tensorrt_yolo3/lib/src/UpsampleLayer.cu
- perception/object_recognition/detection/tensorrt_yolo3/lib/src/YoloLayer.cu
This fixes errors in object recognition headers.
Dear reviewer: please check this by building with cuda&tensorrt installed.
> fix objection recognition headers

- planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/lane_changer.cpp
Fix QoS option for map topic subscription. (missed out from https://github.com/tier4/Pilot.Auto/pull/160)
> Fix transient local

- localization/pose_twist_fusion_filter/ekf_localizer/CMakeLists.txt
- localization/pose_twist_fusion_filter/ekf_localizer/include/ekf_localizer/ekf_localizer.hpp
- localization/pose_twist_fusion_filter/ekf_localizer/include/kalman_filter/kalman_filter.hpp
- localization/pose_twist_fusion_filter/ekf_localizer/include/kalman_filter/time_delay_kalman_filter.hpp
- localization/pose_twist_fusion_filter/ekf_localizer/src/ekf_localizer.cpp
- localization/pose_twist_fusion_filter/ekf_localizer/src/ekf_localizer_node.cpp
- localization/pose_twist_fusion_filter/ekf_localizer/test/src/test_ekf_localizer.cpp
`cpp_lint` giving some errors related to TODO.
> adding linters to ekf_localizer

- control/shift_decider/CMakeLists.txt
- control/shift_decider/include/shift_decider/shift_decider.hpp
- control/shift_decider/package.xml
- control/shift_decider/src/main.cpp
- control/shift_decider/src/shift_decider.cpp
> Added linters to shift_decider

- control/vehicle_cmd_gate/CMakeLists.txt
- control/vehicle_cmd_gate/include/vehicle_cmd_gate/vehicle_cmd_filter.hpp
- control/vehicle_cmd_gate/include/vehicle_cmd_gate/vehicle_cmd_gate.hpp
- control/vehicle_cmd_gate/package.xml
- control/vehicle_cmd_gate/src/vehicle_cmd_filter.cpp
- control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
> Added linters to vehicle_cmd_gate

- planning/scenario_planning/parking/costmap_generator/nodes/costmap_generator/costmap_generator_node.cpp
Transient_local was accidentally removed in https://github.com/tier4/Pilot.Auto/pull/149/files#diff-c56d9bb3e6070403bd756fa6f2827218d292819d188ba9142f9b92365012388b
> [costmap_generator] set transient_local() option for map subscriber

- control/velocity_controller/src/velocity_controller_core.cpp
- localization/pose_twist_fusion_filter/ekf_localizer/src/ekf_localizer.cpp
- planning/scenario_planning/common/motion_velocity_optimizer/CMakeLists.txt
- planning/scenario_planning/common/motion_velocity_optimizer/src/motion_velocity_optimizer.cpp
- planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/lane_changer.cpp
Fix units of time for chrono objects and throttled messages.
This is one of the fixes that we made in experiment-20201208-final
> fix units of time objects

- simulator/util/dummy_perception_publisher/CMakeLists.txt
- simulator/util/dummy_perception_publisher/launch/dummy_perception_publisher.launch.xml
This fixes installation of the launch file in dummy_perception_publisher, and also do ros2 porting of the launch file that was missed out.
> [dummy_perception_publisher] fix launch file and installation

- planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/src/node.cpp
Part of https://github.com/tier4/AutowareArchitectureProposal/issues/132
The result of the waitForTransform doesn't even seem to have been used, I fixed it and moved the variable declarations to their initialization.
> Replace waitForTransform by lookupTransform in surround_obstacle_checker

- perception/object_recognition/tracking/multi_object_tracker/src/multi_object_tracker_core.cpp
Closer to the ROS1 original now: https://github.com/tier4/Pilot.Auto/blob/master/perception/object_recognition/tracking/multi_object_tracker/src/node.cpp#L39-L59
> Replace waitForTransform with lookupTransform in multi_object_tracker

- sensing/preprocessor/pointcloud/pointcloud_preprocessor/CMakeLists.txt
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/src/filter.cpp
Fix declaration of tf_buffer so that it can use lookup transform with timeouts
> [pointcloud_preprocessor] fix timestamp issues

- planning/scenario_planning/lane_driving/behavior_planning/turn_signal_decider/src/data_manager.cpp
- planning/scenario_planning/parking/costmap_generator/nodes/costmap_generator/costmap_generator_node.cpp
- simulator/simple_planning_simulator/src/simple_planning_simulator_core.cpp
- simulator/util/dummy_perception_publisher/src/node.cpp
This reduces terminal output for error/info messages.
> reduce terminal ouput for better error message visibility

- localization/pose_estimator/ndt_scan_matcher/ndt_scan_matcher/launch/ndt_scan_matcher.launch.xml
- localization/pose_twist_fusion_filter/ekf_localizer/launch/ekf_localizer.launch.xml
- localization/twist_estimator/gyro_odometer/launch/gyro_odometer.launch.xml
- localization/twist_estimator/pose2twist/launch/pose2twist.launch.xml
- localization/util/pose_initializer/launch/pose_initializer.launch.xml
- map/map_loader/launch/lanelet2_map_loader.launch.xml
- map/map_loader/launch/pointcloud_map_loader.launch.xml
- map/map_tf_generator/launch/map_tf_generator.launch.xml
- sensing/preprocessor/gnss/gnss_poser/launch/gnss_poser.launch.xml
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/launch/ring_passthrough_filter.launch.xml
- sensing/preprocessor/pointcloud/pointcloud_to_laserscan/launch/sample_node.launch.xml
- sensing/preprocessor/pointcloud/pointcloud_to_laserscan/launch/sample_nodelet.launch.xml
- sensing/preprocessor/pointcloud/pointcloud_to_laserscan/launch/vscan.launch.xml
- vehicle/as/launch/pacmod_interface.launch.xml
- vehicle/as/launch/ssc_interface.launch.xml
- vehicle/raw_vehicle_cmd_converter/launch/raw_vehicle_converter.launch.xml
- vehicle/remote_cmd_converter/launch/remote_cmd_converter.launch.xml
Using env variable to set use_sim_time.
This pr aims to set use_sim_time in Localizaion, Perception, Map and Vehicle module.
This pr needs to be merged with PR in autoware_launcher.iv.universe
> apply env_var to  use_sim_time

- perception/util/visualizer/dynamic_object_visualization/launch/dynamic_object_visualizer.launch.xml
- simulator/util/dummy_perception_publisher/launch/dummy_perception_publisher.launch.xml
* fix minor issues in launch files
* need to be merged for making planning simulator work
> modify launch file for making psim work

- control/vehicle_cmd_gate/launch/vehicle_cmd_gate.launch.xml
- planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/launch/behavior_velocity_planner.launch.xml
Make the vehicle model configurable in all launch files that require vehicle information.
> Make launch files load vehicle model params dependent on argument

- control/vehicle_cmd_gate/launch/vehicle_cmd_gate.launch.xml
- planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/launch/behavior_velocity_planner.launch.xml
change vehicle_model to vehicle_param_file
> change from vehicle_model to vehicle_param_file

- simulator/simple_planning_simulator/include/simple_planning_simulator/simple_planning_simulator_core.hpp
- simulator/simple_planning_simulator/src/simple_planning_simulator_core.cpp
Add missing subscriber to get z position from trajectory
before
after
> Use trajectory for z position source

- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/CMakeLists.txt
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/console_meter.cpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/jsk_overlay_utils.cpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/jsk_overlay_utils.hpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/steering_angle.cpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/turn_signal.cpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/velocity_history.cpp
Please check if you can see vehicle plugins at the upper left on rviz as below.
> Fix bugs in autoware vehicle rviz plugin

- planning/scenario_planning/common/motion_velocity_optimizer/CMakeLists.txt
- planning/scenario_planning/common/motion_velocity_optimizer/package.xml
- planning/scenario_planning/common/motion_velocity_optimizer/scripts/closest_velocity_checker.py
- planning/scenario_planning/common/motion_velocity_optimizer/scripts/trajectory_visualizer.py
Note: based on 0.8.0
```
$ python3 ./src/autoware/pilot.auto/planning/scenario_planning/common/motion_velocity_optimizer/scripts/closest_velocity_checker.py
```
```
$ python3 ./src/autoware/pilot.auto/planning/scenario_planning/common/motion_velocity_optimizer/scripts/trajectory_visualizer.py
```
> Port velocity debug tools

- localization/pose_estimator/ndt_scan_matcher/ndt_omp/LICENSE
- localization/pose_estimator/ndt_scan_matcher/ndt_omp/include/ndt_omp/ndt_omp_impl.hpp
Note: I dropped CMakeLists.txt modification because the modification has been already applied.
> Ros2 v0.8.0 ndt omp

- planning/scenario_planning/parking/astar_search/include/astar_search/astar_search.hpp
- planning/scenario_planning/parking/astar_search/src/astar_search.cpp
- planning/scenario_planning/parking/costmap_generator/include/costmap_generator/costmap_generator.hpp
- planning/scenario_planning/parking/costmap_generator/include/costmap_generator/points_to_costmap.hpp
- planning/scenario_planning/parking/freespace_planner/src/freespace_planner/freespace_planner_node.cpp
includes
- astar_search
- freespace_planner
- costmap_generator
> update to v0.8.0 for parking planner

- perception/traffic_light_recognition/traffic_light_map_based_detector/launch/traffic_light_map_based_detector.launch.xml
> traffic light map based detector: Fix launch

- .github/PULL_REQUEST_TEMPLATE.md
Translate Japanese to English 
Might need more information like `related issue`?
> PR template in english

- system/autoware_state_monitor/include/autoware_state_monitor/autoware_state_monitor_node.hpp
- system/autoware_state_monitor/include/autoware_state_monitor/state_machine.hpp
- system/autoware_state_monitor/package.xml
- system/autoware_state_monitor/src/autoware_state_monitor_node/autoware_state_monitor_node.cpp
- system/autoware_state_monitor/src/autoware_state_monitor_node/state_machine.cpp
Use `autoware_control_msg/EngageMode` in pub/sub instead of `std:_msgs/Bool`.
> change engage from bool to control msg

- .github/workflows/build_and_test.yml
- control/latlon_muxer/src/node.cpp
- perception/object_recognition/prediction/map_based_prediction/src/map_based_prediction_ros.cpp
- planning/scenario_planning/lane_driving/behavior_planning/turn_signal_decider/src/turn_signal_decider_core.cpp
- vehicle/as/include/pacmod_additional_debug_publisher/pacmod_additional_debug_publisher_node.hpp
- vehicle/as/include/pacmod_interface/pacmod_interface.hpp
- vehicle/as/src/pacmod_additional_debug_publisher/pacmod_additional_debug_publisher_main.cpp
- vehicle/as/src/pacmod_additional_debug_publisher/pacmod_additional_debug_publisher_node.cpp
- vehicle/as/src/pacmod_interface/pacmod_interface.cpp
- vehicle/raw_vehicle_cmd_converter/include/raw_vehicle_cmd_converter/accel_map.hpp
- vehicle/raw_vehicle_cmd_converter/include/raw_vehicle_cmd_converter/brake_map.hpp
- vehicle/remote_cmd_converter/src/node.cpp
This enables CI for PRs against ros2-v0.8.0-beta branch
> update target branch for ci

- planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/src/node.cpp
- Drop https://github.com/tier4/autoware.iv/pull/925/files because this is already modified.
- Fix warn duration(s -> ms)
> Ros2 v0.8.0 surround obstacle checker

- simulator/util/dummy_perception_publisher/launch/dummy_perception_publisher.launch.xml
- simulator/util/dummy_perception_publisher/src/node.cpp
> Ros2 v0.8.0 dummy perception publisher

- control/vehicle_cmd_gate/launch/vehicle_cmd_gate.launch.xml
> [vehicle_cmd_gate]: Fix launch

- common/util/autoware_utils/include/autoware_utils/ros/debug_publisher.hpp
> [autoware_utils]: fix traits

- control/velocity_controller/config/velocity_controller_param.yaml
- control/velocity_controller/src/velocity_controller_core.cpp
> [velocity controller]: Fix parameter

- system/autoware_state_monitor/config/autoware_state_monitor.planning_simulation.yaml
- system/autoware_state_monitor/config/autoware_state_monitor.yaml
- system/autoware_state_monitor/src/autoware_state_monitor_node/autoware_state_monitor_node.cpp
`ros2 launch autoware_state_monitor autoware_state_monitor.launch.xml`
> Fix invalid exception handling

- sensing/preprocessor/gnss/gnss_poser/include/gnss_poser/gnss_poser_core.hpp
- sensing/preprocessor/gnss/gnss_poser/package.xml
- sensing/preprocessor/gnss/gnss_poser/src/gnss_poser_core.cpp
> Ros2 v0.8.0 gnss poser rm std msgs

- localization/twist_estimator/pose2twist/include/pose2twist/pose2twist_core.hpp
- localization/twist_estimator/pose2twist/package.xml
- localization/twist_estimator/pose2twist/src/pose2twist_core.cpp
```
ros2 launch pose2twist pose2twist.launch.xml 
[INFO] [launch]: All log files can be found below /home/ros2-foxy/.ros/log/2021-02-24-21-29-49-102328-ros2foxy-332032
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [pose2twist-1]: process started with pid [332034]
```
> Ros2 v0.8.0 pose2twist rm std msgs

- control/velocity_controller/include/velocity_controller/delay_compensation.hpp
- control/velocity_controller/include/velocity_controller/lowpass_filter.hpp
- control/velocity_controller/include/velocity_controller/pid.hpp
- control/velocity_controller/include/velocity_controller/velocity_controller.hpp
- control/velocity_controller/include/velocity_controller/velocity_controller_mathutils.hpp
- control/velocity_controller/package.xml
- control/velocity_controller/src/pid.cpp
- control/velocity_controller/src/velocity_controller_core.cpp
- control/velocity_controller/src/velocity_controller_mathutils.cpp
- control/velocity_controller/src/velocity_controller_node.cpp
remove std_msgs and add autoware debug msgs
> remove std_msgs

- vehicle/as/include/pacmod_additional_debug_publisher/pacmod_additional_debug_publisher_node.hpp
- vehicle/as/launch/pacmod_additional_debug_publisher.launch.xml
- vehicle/as/src/pacmod_additional_debug_publisher/pacmod_additional_debug_publisher_node.cpp
This updates `as` package from v0.8 to v0.9
> Update v0.9.0 as

- planning/scenario_planning/lane_driving/behavior_planning/turn_signal_decider/src/turn_signal_decider_core.cpp
This removes unnecessary assignment of value to a variable.
> remove unused assignment

- sensing/preprocessor/pointcloud/pointcloud_preprocessor/src/ground_filter/ray_ground_filter_nodelet.cpp
This updates ray_ground_filter node to v0.9.0
> [ray_ground_filter] fix height threshold bug

- perception/object_recognition/detection/shape_estimation/src/model/normal/cylinder.cpp
This updates shape estimation node to v0.9.0
> fix bug in shape estimation node

- system/autoware_error_monitor/config/autoware_error_monitor.param.yaml
- system/autoware_error_monitor/config/autoware_error_monitor.planning_simulation.param.yaml
- system/system_monitor/config/system_monitor.param.yaml
- system/system_monitor/include/system_monitor/cpu_monitor/cpu_monitor_base.hpp
- system/system_monitor/src/cpu_monitor/cpu_monitor_base.cpp
- system/system_monitor/src/cpu_monitor/intel_cpu_monitor.cpp
- system/system_monitor/src/net_monitor/net_monitor.cpp
- system/system_monitor/test/src/cpu_monitor/test_intel_cpu_monitor.cpp
This updates system monitor and error monitor to v0.9.0 from v0.8.0
> [Update v0.9.0] system monitor

- planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/package.xml
- planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/src/node.cpp
* fix slow down insert slow down point bug
* refactor code
> fix insert slow down point bug

- system/topic_state_monitor/launch/topic_state_monitor.launch.xml
This PR updates topic_state_monitor to version v0.9.0 from v0.8.0
> Add node_name_suffix to topic_state_monitor.launch

- system/system_monitor/include/system_monitor/ntp_monitor/ntp_monitor.hpp
- system/system_monitor/src/ntp_monitor/ntp_monitor.cpp
This updates system_monitor package to v0.9
> Use thread for ntpdate. (#1160)

- control/autoware_joy_controller/CMakeLists.txt
- control/autoware_joy_controller/include/autoware_joy_controller/autoware_joy_controller.hpp
- control/autoware_joy_controller/include/autoware_joy_controller/joy_converter/ds4_joy_converter.hpp
- control/autoware_joy_controller/include/autoware_joy_controller/joy_converter/g29_joy_converter.hpp
- control/autoware_joy_controller/include/autoware_joy_controller/joy_converter/joy_converter_base.hpp
- control/autoware_joy_controller/package.xml
- control/autoware_joy_controller/src/autoware_joy_controller/autoware_joy_controller_node.cpp
- control/autoware_joy_controller/src/autoware_joy_controller/main.cpp
* remove using in global namespace
* Revert "remove using in global namespace"
* Add package namespace
> remove using in global namespace

- sensing/preprocessor/pointcloud/pointcloud_preprocessor/src/concatenate_data/concatenate_data_nodelet.cpp
Added warning msg for easier debugging.
Related PR: https://github.com/tier4/AutowareArchitectureProposal.iv/pull/369
> Add warning msg when concat pointcloud is not published

- perception/util/visualizer/dynamic_object_visualization/CMakeLists.txt
- perception/util/visualizer/dynamic_object_visualization/include/dynamic_object_visualization/dynamic_object_visualizer.hpp
- perception/util/visualizer/dynamic_object_visualization/package.xml
- perception/util/visualizer/dynamic_object_visualization/src/dynamic_object_visualizer.cpp
- perception/util/visualizer/dynamic_object_visualization/src/main.cpp
* visualize covariance and reduce cylinder polygon
* cosmetic change
* change line width
> visualize covariance and reduce cylinder polygon

- planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/src/scene_module/crosswalk/scene_walkway.cpp
* launch planning simulator with a map including walkway
```
ros2 launch autoware_launch planning_simulator.launch.xml map_path:=(your map) vehicle_model:=lexus sensor_model:=aip_xx1
```
*check if ego vehicle pass walkway after stopping.
> Ros2 v0.9.0 fix walkway

- map/lanelet2_extension/include/lanelet2_extension/visualization/visualization.hpp
- map/lanelet2_extension/lib/visualization.cpp
- map/map_loader/include/map_loader/pointcloud_map_loader_node.hpp
- map/map_loader/src/lanelet2_map_loader/lanelet2_map_loader.cpp
- map/map_loader/src/lanelet2_map_loader/lanelet2_map_visualization.cpp
- map/map_loader/src/pointcloud_map_loader/main.cpp
- map/map_loader/src/pointcloud_map_loader/pointcloud_map_loader_node.cpp
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/src/concatenate_data/concatenate_data_nodelet.cpp
Reduced the number of markers by grouping all vertices together.
Rviz FPS improved from 3 to 10 on my PC.
> Fix rviz2 low FPS

- awapi/awapi_awiv_adapter/launch/awapi_awiv_adapter.launch.xml
- common/msgs/autoware_localization_msgs/CMakeLists.txt
- common/msgs/autoware_localization_msgs/msg/PoseInitializationRequest.msg
- common/msgs/autoware_localization_msgs/package.xml
- localization/util/pose_initializer/CMakeLists.txt
- localization/util/pose_initializer/include/pose_initializer/pose_initializer_core.hpp
- localization/util/pose_initializer/launch/pose_initializer.launch.xml
- localization/util/pose_initializer/package.xml
- localization/util/pose_initializer/src/pose_initializer_core.cpp
* modify pose_initialize for foa
* rename topic
> modify pose_initialize for foa 

- common/util/web_controller/autoware_web_controller/www/autoware_web_controller/js/autoware_engage.js
- common/util/web_controller/autoware_web_controller/www/autoware_web_controller/js/lane_change_approval.js
- common/util/web_controller/autoware_web_controller/www/autoware_web_controller/js/vehicle_engage.js
- common/util/web_controller/autoware_web_controller/www/autoware_web_controller/js/velocity_limit.js
This fixes bug in autoware_web_controller
> Fix autoware web controller

- sensing/preprocessor/pointcloud/pointcloud_preprocessor/CMakeLists.txt
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/include/pointcloud_preprocessor/downsample_filter/approximate_downsample_filter_nodelet.hpp
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/package.xml
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/src/downsample_filter/approximate_downsample_filter_nodelet.cpp
* add approximate downsample filter nodelet
* add pcl_voxel_grid_modified package
* fixed cmake list
* use approximate voxel grid filter
* rename packages
* rename voxel grid filter class
> Add approximate voxel grid filter

- perception/traffic_light_recognition/traffic_light_ssd_fine_detector/include/traffic_light_ssd_fine_detector/nodelet.hpp
- perception/traffic_light_recognition/traffic_light_ssd_fine_detector/package.xml
- perception/traffic_light_recognition/traffic_light_ssd_fine_detector/src/nodelet.cpp
rm float32 msgs and use autoware debug msgs instead
> Ros2 v0.8.0 beta rm std msgs ssd traffic light

- sensing/preprocessor/pointcloud/pointcloud_preprocessor/include/pointcloud_preprocessor/concatenate_data/concatenate_data_nodelet.hpp
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/package.xml
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/src/concatenate_data/concatenate_data_nodelet.cpp
* Remove std msgs from concatenate data
* Adaptive timer(https://github.com/tier4/AutowareArchitectureProposal.iv/issues/119)
> Fix concatenate data

- awapi/awapi_awiv_adapter/src/awapi_awiv_adapter_core.cpp
Fix Topic name.
"input/max_velocity"
->
"input/current_max_velocity"
> fix awapi-awiv-adapter

- planning/scenario_planning/common/motion_velocity_optimizer/scripts/closest_velocity_checker.py
- planning/scenario_planning/common/motion_velocity_optimizer/scripts/trajectory_visualizer.py
Fix python scripts in motion velocity optimizer
$ros2 launch autoware_launch planning_simulator.launch.xml vehicle_model:=lexus vehicle_id:=default sensor_model:=aip_xx1 map_path:=MAP_PATH
$ros2 run motion_velocity_optimizer closest_velocity_checker.py
$ros2 run motion_velocity_optimizer trajectory_visualizer.py
$ros2 run motion_velocity_optimizer trajectory_visualizer.py -t VEL_ACC_JERK
> Ros2 fix motion velocity pyscripts

- system/topic_state_monitor/include/topic_state_monitor/topic_state_monitor.hpp
- system/topic_state_monitor/launch/topic_state_monitor.launch.xml
- system/topic_state_monitor/src/topic_state_monitor_core.cpp
Add transient_local option to topic_state_monitor.
> add transient local option to topic state monitor

- control/autoware_joy_controller/src/autoware_joy_controller/autoware_joy_controller_node.cpp
> fix namespace of parameter in autoware_joy_controller

- localization/util/pose_initializer/src/pose_initializer_core.cpp
> Fix missing gnss subscriber

- awapi/awapi_awiv_adapter/src/awapi_awiv_adapter_core.cpp
- control/mpc_follower/src/mpc_follower_core.cpp
- control/pure_pursuit/include/pure_pursuit/util/tf_utils.hpp
- control/velocity_controller/src/velocity_controller_core.cpp
- perception/object_recognition/detection/roi_cluster_fusion/src/roi_cluster_fusion_nodelet.cpp
- planning/scenario_planning/common/motion_velocity_optimizer/src/motion_velocity_optimizer.cpp
- planning/scenario_planning/lane_driving/behavior_planning/turn_signal_decider/src/data_manager.cpp
- planning/scenario_planning/parking/costmap_generator/nodes/costmap_generator/costmap_generator_node.cpp
- simulator/util/dummy_perception_publisher/src/node.cpp
Should be merged after #419.
Removed console spams.
- Before
```
[INFO] [rviz2-72]: process started with pid [1658936]
[INFO] [web_server-73]: process started with pid [1658942]
[INFO] [rosbridge_websocket-74]: process started with pid [1658971]
[INFO] [clock_publisher_node-75]: process started with pid [1658976]
[robot_state_publisher-1] Parsing robot urdf xml string.
[robot_state_publisher-1] Link sensor_kit_base_link had 4 children
[robot_state_publisher-1] Link livox_front_center_base_link had 1 children
[robot_state_publisher-1] Link livox_front_center had 0 children
[robot_state_publisher-1] Link livox_front_left_base_link had 1 children
[robot_state_publisher-1] Link livox_front_left had 0 children
[robot_state_publisher-1] Link livox_front_right_base_link had 1 children …
```
> Fix transform

- common/msgs/autoware_perception_msgs/CMakeLists.txt
autoware_perception_msgsの中のtypoを修正しました。
ビルドが通ることは検証済み
> fix typo in autoware_perception_msgs

- common/math/osqp_interface/include/osqp_interface/osqp_interface.hpp
- common/msgs/autoware_planning_msgs/msg/PathPoint.msg
- common/util/autoware_debug_tools/README.md
Fix typo in common module.
Please merge this with the following pull request simultaneously for `PathPoint.msg`.
https://github.com/tier4/AutowareArchitectureProposal.proj/pull/185
> Fix typo in common module

- awapi/autoware_api_msgs/msg/AwapiAutowareStatus.msg
- awapi/awapi_awiv_adapter/launch/awapi_awiv_adapter.launch.xml
- awapi/awapi_awiv_adapter/src/awapi_autoware_state_publisher.cpp
- awapi/awapi_awiv_adapter/src/awapi_awiv_adapter_core.cpp
> Fix typo in awapi module

- simulator/simple_planning_simulator/config/simple_planning_simulator.param.yaml
- simulator/simple_planning_simulator/include/simple_planning_simulator/simple_planning_simulator_core.hpp
- simulator/simple_planning_simulator/include/simple_planning_simulator/vehicle_model/sim_model_ideal.hpp
- simulator/simple_planning_simulator/include/simple_planning_simulator/vehicle_model/sim_model_time_delay.hpp
- simulator/simple_planning_simulator/scripts/README_fitParamDelayInputModel.md
- simulator/simple_planning_simulator/scripts/fitParamDelayInputModel.py
- simulator/simple_planning_simulator/src/simple_planning_simulator_core.cpp
Fix typo in the simulator module.
> Fix typo in simulator module

- sensing/preprocessor/pointcloud/pointcloud_preprocessor/include/pointcloud_preprocessor/filter.hpp
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/include/pointcloud_preprocessor/ground_filter/ransac_ground_filter_nodelet.hpp
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/include/pointcloud_preprocessor/ground_filter/ray_ground_filter_nodelet.hpp
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/launch/preprocessor.launch.py
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/launch/preprocessor.launch.xml
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/launch/random_downsample_filter.launch.xml
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/src/ground_filter/ransac_ground_filter_nodelet.cpp
Fix typo in sensing module.
Did not fix a lot of typos in the code from Point Cloud Library to ensure traceability of the code.
> Fix typo in sensing module

- awapi/awapi_awiv_adapter/include/awapi_awiv_adapter/awapi_autoware_state_publisher.hpp
- awapi/awapi_awiv_adapter/include/awapi_awiv_adapter/diagnostics_filter.hpp
- awapi/awapi_awiv_adapter/src/awapi_autoware_state_publisher.cpp
- control/mpc_follower/include/mpc_follower/mpc_trajectory.hpp
- control/mpc_follower/include/mpc_follower/mpc_utils.hpp
- control/mpc_follower/src/mpc_follower_core.cpp
- control/mpc_follower/src/mpc_trajectory.cpp
- control/mpc_follower/src/mpc_utils.cpp
- localization/pose_estimator/ndt_scan_matcher/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.hpp
- localization/pose_estimator/ndt_scan_matcher/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/src/ground_filter/ransac_ground_filter_nodelet.cpp
- system/autoware_error_monitor/config/autoware_error_monitor.param.yaml
- system/autoware_error_monitor/config/autoware_error_monitor.planning_simulation.param.yaml
- system/autoware_error_monitor/config/diagnostic_aggregator/vehicle.param.yaml
- system/system_monitor/config/system_monitor.param.yaml
- system/system_monitor/include/system_monitor/hdd_monitor/hdd_monitor.hpp
- system/system_monitor/reader/hdd_reader/hdd_reader.cpp
- system/system_monitor/src/hdd_monitor/hdd_monitor.cpp
- system/system_monitor/src/mem_monitor/mem_monitor.cpp
- system/system_monitor/test/config/test_hdd_monitor.param.yaml
- system/system_monitor/test/src/hdd_monitor/test_hdd_monitor.cpp
`bbffe6aca` is ignored because it's already applied.
```sh
❯ git log --oneline v0.9.0..v0.9.1
919e50532 (tag: v0.9.1, autowareiv/rc/v0.9.1) fix yaw-smoothing bug (#1198)
01e26c159 return input pointcloud when ground plane not found (#1190)
e77c4bd6a  Change monitoring method to get HDD temperature and usage per specified device. (#1195)
c195471a1 Fix wrong calculation of available memory. (#1168)
423e3fde7 Filter hazard_status (#1191)
921ce91b0 Add missing diag in autoware_error_monitor.yaml (#1187)
e4ca22f78 Fix diagnostics api (#1185)
9fc0275f6 Add obstacle_crush diagnostic (#1186)
10c9d2769 add local optimal solution ocillation check to ndt_scan_matcher (#1182)
bbffe6aca ransac_ground_filter: Fix minor issue (#1181)
```
> Import v0.9.1

- map/util/lanelet2_map_preprocessor/package.xml
- planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/package.xml
- tmp/trajectory_loader/package.xml
Replace `TODO` in package.xml with appropriate license
> add license

- planning/scenario_planning/common/motion_velocity_optimizer/README.md
- planning/scenario_planning/common/motion_velocity_optimizer/include/motion_velocity_optimizer/motion_velocity_optimizer_utils.hpp
- planning/scenario_planning/common/motion_velocity_optimizer/scripts/trajectory_visualizer.py
- planning/scenario_planning/common/motion_velocity_optimizer/src/motion_velocity_optimizer.cpp
- planning/scenario_planning/common/motion_velocity_optimizer/src/motion_velocity_optimizer_utils.cpp
- planning/scenario_planning/common/motion_velocity_optimizer/src/optimizer/pseudo_jerk_l2_optimizer.cpp
- planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp
- planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/config/obstacle_avoidance_planner.param.yaml
- planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/eb_path_optimizer.hpp
- planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/util.hpp
- planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/vehicle_model/vehicle_model_bicycle_kinematics.hpp
- planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/scripts/trajectory_visualizer.py
- planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/src/eb_path_optimizer.cpp
- planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp
- planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/src/node.cpp
- planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/src/process_cv.cpp
- planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/src/util.cpp
- planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/src/vehicle_model/vehicle_model_bicycle_kinematics.cpp
- planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/src/vehicle_model/vehicle_model_bicycle_kinematics_no_delay.cpp
Fix typo in the planning module.
Please merge this with the following pull request simultaneously.
https://github.com/tier4/autoware_launcher.iv.universe/pull/92
> Fix typo in planning module

- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/CMakeLists.txt
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/console_meter.cpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/console_meter.hpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/jsk_overlay_utils.cpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/jsk_overlay_utils.hpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/steering_angle.cpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/steering_angle.hpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/turn_signal.cpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/turn_signal.hpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/velocity_history.cpp
- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/velocity_history.hpp
```
rviz2 -d (your rviz config)
ros2 topic pub /control/turn_signal_cmd autoware_vehicle_msgs/msg/TurnSignal
ros2 topic pub /vehicle/status/steering autoware_vehicle_msgs/msg/Steering
ros2 topic pub /vehicle/status/twist geometry_msgs/msg/TwistStamped
```
> Ros2 rtd plugin

- awapi/awapi_awiv_adapter/Readme.md
- awapi/awapi_awiv_adapter/launch/awapi_awiv_adapter.launch.xml
add topic relay for traffic light overwriter in awapi
> add tl overwriter relay in awapi

- planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/src/node.cpp
get vehicle_width from vehicle info
> fix bug of obstacle avoidance planner

- perception/object_recognition/detection/bev_optical_flow/include/bev_optical_flow/flow_calculator.hpp
- perception/object_recognition/detection/bev_optical_flow/src/flow_calculator.cpp
- perception/object_recognition/detection/object_flow_fusion/include/object_flow_fusion/object_flow_fusion.hpp
- perception/object_recognition/detection/object_flow_fusion/src/object_flow_fusion.cpp
- perception/object_recognition/detection/object_merger/include/object_association_merger/data_association.hpp
- perception/object_recognition/detection/object_merger/src/object_association_merger/data_association/data_association.cpp
- perception/object_recognition/detection/object_merger/src/object_association_merger/data_association/successive_shortest_path/successive_shortest_path.cpp
- perception/object_recognition/detection/object_range_splitter/src/node.cpp
- perception/object_recognition/detection/roi_cluster_fusion/include/roi_cluster_fusion/roi_cluster_fusion_nodelet.hpp
- perception/object_recognition/detection/roi_cluster_fusion/src/roi_cluster_fusion_nodelet.cpp
- perception/object_recognition/detection/shape_estimation/launch/shape_estimation.launch.xml
- perception/object_recognition/prediction/map_based_prediction/package.xml
- perception/object_recognition/prediction/map_based_prediction/src/map_based_prediction.cpp
- perception/object_recognition/tracking/multi_object_tracker/src/data_association/successive_shortest_path/successive_shortest_path.cpp
- perception/object_recognition/tracking/multi_object_tracker/src/tracker/model/bicycle_tracker.cpp
- perception/object_recognition/tracking/multi_object_tracker/src/utils/utils.cpp
- perception/util/visualizer/dynamic_object_visualization/launch/dynamic_object_visualizer.launch.xml
Fix typo in the perception module.
Please merge this with the following pull request simultaneously.
https://github.com/tier4/autoware_launcher.iv.universe/pull/93
> Fix typo in perception module

- planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/src/scene_module/traffic_light/scene.cpp
Change log type :warn->debug
(Delete annoying standard output)
> change log type

- simulator/simple_planning_simulator/README.md
Add readme for `simple_planning_simulator` node.
> [simple_planning_simulator] add readme

- localization/twist_estimator/pose2twist/src/pose2twist_core.cpp
> Fix pose2twist

- map/lanelet2_extension/lib/autoware_osm_parser.cpp
Reverts tier4/AutowareArchitectureProposal.iv#463
> Revert "fix: re-construct laneletMapLayer for reindex RTree"

- localization/pose_twist_fusion_filter/ekf_localizer/README.md
- improvement
update readme for EKF.
> Update ekf readme

- .github/PULL_REQUEST_TEMPLATE.md
Simplify PR template for .Auto integration.
Please see the removed part. …
> Simplify PR template for .Auto integration

- .github/workflows/build_and_test.yml
- .github/workflows/build_and_test_pr.yml
- build_depends.repos
Fix CI for Autoware.Auto integration
Checks if CI passes. …
> Fix CI for Autoware.Auto integration

- common/util/rviz_plugins/polar_grid/package.xml
.auto porting others seems not necessary to change
- remove unused packages 
colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to polar_grid
```
Starting >>> autoware_lint_common
Finished <<< autoware_lint_common [0.20s]                  
Starting >>> polar_grid
Finished <<< polar_grid [0.35s]                     
Summary: 2 packages finished [1.21s]
```
check that any autoware utils and vehicle packages are not inlcluded
- **Build and test for PR / clang-tidy-pr**: NOT …
> port polar grid remove unused depends

- common/util/autoware_utils/include/autoware_utils/geometry/geometry.hpp
- common/util/autoware_utils/include/autoware_utils/trajectory/trajectory.hpp
- common/util/autoware_utils/package.xml
- common/util/autoware_utils/test/src/geometry/test_geometry.cpp
- common/util/autoware_utils/test/src/trajectory/test_trajectory.cpp
> use autoware_auto_msgs in autoware_utils

- map/lanelet2_extension/include/lanelet2_extension/utility/message_conversion.hpp
- map/lanelet2_extension/lib/message_conversion.cpp
- map/lanelet2_extension/package.xml
- map/lanelet2_extension/test/src/test_message_conversion.cpp
Signed-off-by: Kosuke Murakami <kosuke.murakami@tier4.jp>
- New Feature
- Improvement
- Bug Fix
Port lanelet2 extension  …
> port lanelet2_extension

- common/util/rviz_plugins/autoware_planning_rviz_plugin/include/path/display.hpp
- common/util/rviz_plugins/autoware_planning_rviz_plugin/include/path_footprint/display.hpp
- common/util/rviz_plugins/autoware_planning_rviz_plugin/include/trajectory/display.hpp
- common/util/rviz_plugins/autoware_planning_rviz_plugin/include/trajectory_footprint/display.hpp
- common/util/rviz_plugins/autoware_planning_rviz_plugin/package.xml
- common/util/rviz_plugins/autoware_planning_rviz_plugin/src/path/display.cpp
- common/util/rviz_plugins/autoware_planning_rviz_plugin/src/path_footprint/display.cpp
- common/util/rviz_plugins/autoware_planning_rviz_plugin/src/trajectory/display.cpp
- common/util/rviz_plugins/autoware_planning_rviz_plugin/src/trajectory_footprint/display.cpp
autoware planning rviz pluginの.auto porting
**TODO**
autoware_planning_msgs::VelocityLimitのみiv_msgsに依存 …
> port planning rviz plugins

- sensing/preprocessor/pointcloud/pointcloud_preprocessor/include/pointcloud_preprocessor/vector_map_filter/lanelet2_map_filter_nodelet.hpp
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/src/vector_map_filter/lanelet2_map_filter_nodelet.cpp
- use autoware_auto_mapping_msgs/HADMapBin.idl
- remove COLCON_IGNORE
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_gui …
> port vector map filter

- common/util/autoware_debug_tools/include/autoware_debug_tools/lateral_error_publisher.hpp
- common/util/autoware_debug_tools/package.xml
- common/util/autoware_debug_tools/src/lateral_error_publisher.cpp
autoware_debug_tools .auto porting …
> port autoware_debug_tools

- common/util/autoware_utils/include/autoware_utils/trajectory/convert.hpp
- common/util/autoware_utils/include/autoware_utils/trajectory/tmp_conversion.hpp
- common/util/autoware_utils/test/src/trajectory/test_trajectory.cpp
Add trajectory converter functions in autoware_utils.
Please build autoware_utils and check the result of tests. …
> Add trajectory converter

- system/emergency_handler/README.md
- system/emergency_handler/include/emergency_handler/emergency_handler_core.hpp
- system/emergency_handler/launch/emergency_handler.launch.xml
- system/emergency_handler/package.xml
- system/emergency_handler/src/emergency_handler/emergency_handler_core.cpp
- support .auto msg
autoware_control_msgs/msg/control_command_stamped -> autoware_auto_control_msgs/msg/ackermann_control_command
autoware_vehicle_msgs/msg/control_mode -> autoware_auto_vehicle_msgs/msg/vehicle_state_report.
autoware_vehicle_msgs/msg/shift_stamped, autoware_vehicle_msgs/msg/turn_signal -> autoware_auto_vehicle_msgs/msg/vehicle_state_command.
autoware_system_msgs/msg/emergency_state_stamped -> autoware_auto_system_msgs/msg/emergency_state
autoware_system_msgs/msg/hazard_status_stamped -> autoware_auto_system_msgs/msg/hazard_status_stamped
- update readme
$colcon build --catkin-skip-building-tests --symlink-install --continue-on-error --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to emargency_handler
**PR Author should check the checkboxes below when creating the …
> [emergency_handler]support autoware.auto msg

- planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/include/surround_obstacle_checker/node.hpp
- planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/package.xml
- planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/src/node.cpp
.auto ポーティング
autoware_planning_msgs::msg::Trajectory
→
autoware_auto_planning_msgs::msg::TrajectoryPoint
autoware_perception_msgs::msg::DynamicObjectArray
→
autoware_auto_perception_msgs::msg::PredictedObjects
以下の変更がmergeされる前提でporting
https://github.com/tier4/autoware_auto_msgs/pull/7
- **Check spelling**: NOT required to pass before …
> port surround obstacle checker

- control/trajectory_follower/obstacle_collision_checker/include/obstacle_collision_checker/obstacle_collision_checker.hpp
- control/trajectory_follower/obstacle_collision_checker/include/obstacle_collision_checker/obstacle_collision_checker_node.hpp
- control/trajectory_follower/obstacle_collision_checker/launch/obstacle_collision_checker.launch.xml
- control/trajectory_follower/obstacle_collision_checker/package.xml
- control/trajectory_follower/obstacle_collision_checker/src/obstacle_collision_checker_node/obstacle_collision_checker.cpp
- control/trajectory_follower/obstacle_collision_checker/src/obstacle_collision_checker_node/obstacle_collision_checker_node.cpp
.autoポーティング
obstacle collision checker …
> port obstacle collision checker

- planning/scenario_planning/scenario_selector/include/scenario_selector/scenario_selector_node.hpp
- planning/scenario_planning/scenario_selector/launch/scenario_selector.launch.xml
- planning/scenario_planning/scenario_selector/package.xml
- planning/scenario_planning/scenario_selector/src/scenario_selector_node/scenario_selector_node.cpp
.autoポーティング
scenario_selector
**TODO**
Scenarioはiv_msgsを使用 …
> port scenario_selector

- perception/object_recognition/detection/object_range_splitter/include/object_range_splitter/node.hpp
- perception/object_recognition/detection/object_range_splitter/package.xml
- perception/object_recognition/detection/object_range_splitter/src/node.cpp
.auto porting
input / output
- autoware_perception_msgs::msg::DynamicObjectWithFeatureArray -> autoware_auto_perception_msgs::msg::DetectedObjects …
> port object range splitter

- system/autoware_error_monitor/README.md
- system/autoware_error_monitor/include/autoware_error_monitor/autoware_error_monitor_core.hpp
- system/autoware_error_monitor/package.xml
- system/autoware_error_monitor/src/autoware_error_monitor_core.cpp
- support .auto msg
autoware_system_msgs/msg/autoware_state -> autoware_auto_system_msgs/msg/autoware_state
autoware_system_msgs/msg/hazard_status_stamped -> autoware_auto_system_msgs/msg/hazard_status_stamped
autoware_vehicle_msgs/msg/control_mode -> autoware_auto_vehicle_msgs/msg/vehicle_state_report
autoware_control_msgs/msg/gate_mode -> no change ( do not use autoware.auto msg)
- update readme 
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). …
> [autoware error monitor] support autoware.auto msg

- map/map_loader/include/map_loader/elevation_map_loader_node.hpp
- map/map_loader/include/map_loader/lanelet2_map_loader_node.hpp
- map/map_loader/include/map_loader/lanelet2_map_visualization_node.hpp
- map/map_loader/package.xml
- map/map_loader/src/elevation_map_loader/elevation_map_loader_node.cpp
- map/map_loader/src/lanelet2_map_loader/lanelet2_map_loader_node.cpp
- map/map_loader/src/lanelet2_map_loader/lanelet2_map_visualization_node.cpp
Porting of map_loader for .auto …
> port map loader

- common/util/web_controller/autoware_web_controller/www/autoware_web_controller/index.html
- common/util/web_controller/autoware_web_controller/www/autoware_web_controller/js/autoware_engage.js
- common/util/web_controller/autoware_web_controller/www/autoware_web_controller/js/autoware_state.js
- common/util/web_controller/autoware_web_controller/www/autoware_web_controller/js/vehicle_engage.js
Sport to autoware_auto_msgs
autoware_vehicle_msgs/Engage to autoware_auto_vehicle_msgs/Engage
autoware_system_msgs/AutowareState to autoware_auto_system_msgs/AutowareState
ignore msgs, because, these message not exist in autoware_auto_msgs.
autoware_planning_msgs/msg/Approval
autoware_vehicle_msgs/ControlMode
autoware_planning_msgs/VelocityLimit
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the …
> autoware_web_controller port to .auto

- perception/traffic_light_recognition/traffic_light_ssd_fine_detector/include/traffic_light_ssd_fine_detector/nodelet.hpp
- perception/traffic_light_recognition/traffic_light_ssd_fine_detector/package.xml
- perception/traffic_light_recognition/traffic_light_ssd_fine_detector/src/nodelet.cpp
support autoware auto messages in traffic_light_ssd_fine_detector
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/C …
> [traffic_light_ssd_fine_detector] support autoware auto msgs

- perception/object_recognition/detection/object_merger/include/object_association_merger/data_association.hpp
- perception/object_recognition/detection/object_merger/include/object_association_merger/node.hpp
- perception/object_recognition/detection/object_merger/include/object_association_merger/utils/utils.hpp
- perception/object_recognition/detection/object_merger/package.xml
- perception/object_recognition/detection/object_merger/src/object_association_merger/data_association/data_association.cpp
- perception/object_recognition/detection/object_merger/src/object_association_merger/node.cpp
- perception/object_recognition/detection/object_merger/src/object_association_merger/utils/utils.cpp
- porting object_merger package
- remove **ANIMAL** label
- support for autoware_auto_perception_msgs …
> port object merger

- common/util/goal_distance_calculator/include/goal_distance_calculator/goal_distance_calculator.hpp
- common/util/goal_distance_calculator/include/goal_distance_calculator/goal_distance_calculator_node.hpp
- common/util/goal_distance_calculator/package.xml
- common/util/goal_distance_calculator/src/goal_distance_calculator.cpp
- common/util/goal_distance_calculator/src/goal_distance_calculator_node.cpp
sport to autoware_auto_msgs
convert autoware_planning_msgs to autoware_auto_planning_msgs …
> goal_distance_calculator port to .auto

- control/trajectory_follower/lane_departure_checker/README.md
- control/trajectory_follower/lane_departure_checker/include/lane_departure_checker/lane_departure_checker.hpp
- control/trajectory_follower/lane_departure_checker/include/lane_departure_checker/lane_departure_checker_node.hpp
- control/trajectory_follower/lane_departure_checker/launch/lane_departure_checker.launch.xml
- control/trajectory_follower/lane_departure_checker/package.xml
- control/trajectory_follower/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp
- control/trajectory_follower/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp
Porting lane_departure_checker for using autoware_auto_msgs.
- Use autoware_auto_planning_msgs, autoware_auto_mapping_msgs.
- Use nav_msgs/Odometry to get current twist and pose covariance.
- Use TrajectoryPointArray for resampling
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See …
> port lane_departure_checker

- perception/traffic_light_recognition/traffic_light_map_based_detector/include/traffic_light_map_based_detector/node.hpp
- perception/traffic_light_recognition/traffic_light_map_based_detector/package.xml
- perception/traffic_light_recognition/traffic_light_map_based_detector/src/node.cpp
support autoware_auto messages in traffic_light_map_based_detector
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ …
> [traffic_light_map_based_detector] support autoware auto msgs

- perception/util/visualizer/traffic_light_visualization/include/traffic_light_map_visualizer/node.hpp
- perception/util/visualizer/traffic_light_visualization/include/traffic_light_roi_visualizer/nodelet.hpp
- perception/util/visualizer/traffic_light_visualization/package.xml
- perception/util/visualizer/traffic_light_visualization/src/traffic_light_map_visualizer/node.cpp
- perception/util/visualizer/traffic_light_visualization/src/traffic_light_roi_visualizer/nodelet.cpp
support autoware auto messages in traffic_light_visualization
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/Clang …
> [traffic_light_visualization] support autoware auto msgs 

- planning/scenario_planning/common/motion_velocity_smoother/include/motion_velocity_smoother/motion_velocity_smoother_node.hpp
- planning/scenario_planning/common/motion_velocity_smoother/include/motion_velocity_smoother/resample.hpp
- planning/scenario_planning/common/motion_velocity_smoother/include/motion_velocity_smoother/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.hpp
- planning/scenario_planning/common/motion_velocity_smoother/include/motion_velocity_smoother/smoother/analytical_jerk_constrained_smoother/velocity_planning_utils.hpp
- planning/scenario_planning/common/motion_velocity_smoother/include/motion_velocity_smoother/smoother/jerk_filtered_smoother.hpp
- planning/scenario_planning/common/motion_velocity_smoother/include/motion_velocity_smoother/smoother/l2_pseudo_jerk_smoother.hpp
- planning/scenario_planning/common/motion_velocity_smoother/include/motion_velocity_smoother/smoother/linf_pseudo_jerk_smoother.hpp
- planning/scenario_planning/common/motion_velocity_smoother/include/motion_velocity_smoother/smoother/smoother_base.hpp
- planning/scenario_planning/common/motion_velocity_smoother/include/motion_velocity_smoother/trajectory_utils.hpp
- planning/scenario_planning/common/motion_velocity_smoother/motion_velocity_smoother-design.ja.md
- planning/scenario_planning/common/motion_velocity_smoother/motion_velocity_smoother-design.md
- planning/scenario_planning/common/motion_velocity_smoother/package.xml
- planning/scenario_planning/common/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp
- planning/scenario_planning/common/motion_velocity_smoother/src/resample.cpp
- planning/scenario_planning/common/motion_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.cpp
- planning/scenario_planning/common/motion_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/velocity_planning_utils.cpp
- planning/scenario_planning/common/motion_velocity_smoother/src/smoother/jerk_filtered_smoother.cpp
- planning/scenario_planning/common/motion_velocity_smoother/src/smoother/l2_pseudo_jerk_smoother.cpp
- planning/scenario_planning/common/motion_velocity_smoother/src/smoother/linf_pseudo_jerk_smoother.cpp
- planning/scenario_planning/common/motion_velocity_smoother/src/smoother/smoother_base.cpp
- planning/scenario_planning/common/motion_velocity_smoother/src/trajectory_utils.cpp
Port motion_velocity_smoother for using autoware_auto_msgs
- Use autoware_auto_msgs
- Use conversion functions to use autoware_auto_msgs::msg::Trajectory
- Use odometry instead of twist
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words …
> port motion velocity smoother

- common/util/goal_distance_calculator/Readme.md
add readme of goal_distance_calculator node
Check the readme
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangT …
> [goal_distance_calculator]add readme

- perception/object_recognition/detection/object_range_splitter/src/node.cpp
build error by changed autoware_auto_perception_msgs
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuide …
> Fix object_range_splitter

- build_depends.repos
- https://github.com/tier4/AutowareArchitectureProposal_msgs/pull/4
- update build depends by using CI/CD build test
- aap_msgs/main -> aap_msgs/use-autoware-auto-msgs …
> update depend branch

- control/trajectory_follower/obstacle_collision_checker/README.md
- control/trajectory_follower/obstacle_collision_checker/config/obstacle_collision_checker.param.yaml
add readme to obstacle collision checker
add readme to obstacle collision checker …
> add readme to obstacle collision checker

- vehicle/raw_vehicle_cmd_converter/README.md
- vehicle/raw_vehicle_cmd_converter/include/raw_vehicle_cmd_converter/node.hpp
- vehicle/raw_vehicle_cmd_converter/include/raw_vehicle_cmd_converter/steer_converter.hpp
- vehicle/raw_vehicle_cmd_converter/launch/raw_vehicle_converter.launch.xml
- vehicle/raw_vehicle_cmd_converter/package.xml
- vehicle/raw_vehicle_cmd_converter/src/node.cpp
- vehicle/raw_vehicle_cmd_converter/src/steer_converter.cpp
apply autoware auto msgs to raw vehicle cmd converter
autoware_iv_msgs
- actuation_command
- steering_report
- float32_multi_array_stamped
- localization odometry
autoware_auto_msgs
- ackermann_control_command
remove unused shift message
colcon build pass
- control command stamped -> ackerman control command
- vehicle status steering was not in .auto msgs
- localization/twist would be necessary to change to odm later [not in this PR]
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the …
> [raw vehicle cmd converter] apply autoware auto msgs

- common/util/goal_distance_calculator/Readme.md
- common/util/path_distance_calculator/Readme.md
add readme of path distance calculator 
Check the readme
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyG …
> [path_distance_calculator]add readme

- control/shift_decider/include/shift_decider/shift_decider.hpp
- control/shift_decider/src/shift_decider.cpp
- system/autoware_error_monitor/README.md
- system/autoware_error_monitor/include/autoware_error_monitor/autoware_error_monitor_core.hpp
- system/autoware_error_monitor/src/autoware_error_monitor_core.cpp
- system/autoware_state_monitor/Readme.md
- system/autoware_state_monitor/include/autoware_state_monitor/autoware_state_monitor_node.hpp
- system/autoware_state_monitor/include/autoware_state_monitor/state_machine.hpp
- system/autoware_state_monitor/launch/autoware_state_monitor.launch.xml
- system/autoware_state_monitor/src/autoware_state_monitor_node/autoware_state_monitor_node.cpp
- system/autoware_state_monitor/src/autoware_state_monitor_node/state_machine.cpp
- system/emergency_handler/README.md
- system/emergency_handler/include/emergency_handler/emergency_handler_core.hpp
- system/emergency_handler/launch/emergency_handler.launch.xml
- system/emergency_handler/src/emergency_handler/emergency_handler_core.cpp
remove VehicleStateReport/VehicleStateCommand.msg/VehicleControlCommand and use other types of msg …
> remove VehicleStateReport/VehicleStateCommand/VehicleControlCommand

- perception/traffic_light_recognition/traffic_light_classifier/include/traffic_light_classifier/classifier_interface.hpp
- perception/traffic_light_recognition/traffic_light_classifier/include/traffic_light_classifier/cnn_classifier.hpp
- perception/traffic_light_recognition/traffic_light_classifier/include/traffic_light_classifier/color_classifier.hpp
- perception/traffic_light_recognition/traffic_light_classifier/include/traffic_light_classifier/nodelet.hpp
- perception/traffic_light_recognition/traffic_light_classifier/package.xml
- perception/traffic_light_recognition/traffic_light_classifier/src/cnn_classifier.cpp
- perception/traffic_light_recognition/traffic_light_classifier/src/color_classifier.cpp
- perception/traffic_light_recognition/traffic_light_classifier/src/nodelet.cpp
> [traffic_light_classifier] support autoware auto msgs

- common/util/rviz_plugins/polar_grid/Readme.md
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/docs/OccupancyGridMapOutlierFilter.md
- add readme polar grid
- remove colcon ignore …
> [ polar grid ] add readme polar grid remove colcon ignore

- map/map_tf_generator/Readme.md
Add readme of map_tf_generator
Please check the readme
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGui …
> [map_tf_generator]add readme

- planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/src/process_cv.cpp
- planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/src/adaptive_cruise_control.cpp
- planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/src/node.cpp
- planning/scenario_planning/scenario_selector/src/scenario_selector_node/scenario_selector_node.cpp
fix PR
shape array -> shape
initial pose -> initial_pose_with_covariance
goal_point -> goal_pose
check CI pass …
> [apply_predicted_obj_type] adapt to autoware auto msgs

- common/util/rviz_plugins/autoware_state_rviz_plugin/package.xml
- common/util/rviz_plugins/autoware_state_rviz_plugin/src/autoware_state_panel.cpp
- common/util/rviz_plugins/autoware_state_rviz_plugin/src/autoware_state_panel.hpp
porting autoware_state_rviz_plugin …
> port autoware_state_rviz_plugin

- system/topic_state_monitor/Readme.md
- system/topic_state_monitor/launch/topic_state_monitor.launch.xml
Add readme of topic_state_monitor
Please check the readme …
> [topic_state_monitor]add readme

- perception/object_recognition/detection/lidar_apollo_instance_segmentation/include/lidar_apollo_instance_segmentation/cluster2d.hpp
- perception/object_recognition/detection/lidar_apollo_instance_segmentation/include/lidar_apollo_instance_segmentation/debugger.hpp
- perception/object_recognition/detection/lidar_apollo_instance_segmentation/include/lidar_apollo_instance_segmentation/detector.hpp
- perception/object_recognition/detection/lidar_apollo_instance_segmentation/include/lidar_apollo_instance_segmentation/node.hpp
- perception/object_recognition/detection/lidar_apollo_instance_segmentation/package.xml
- perception/object_recognition/detection/lidar_apollo_instance_segmentation/src/cluster2d.cpp
- perception/object_recognition/detection/lidar_apollo_instance_segmentation/src/debugger.cpp
- perception/object_recognition/detection/lidar_apollo_instance_segmentation/src/detector.cpp
- perception/object_recognition/detection/lidar_apollo_instance_segmentation/src/node.cpp
Make lidar apollo instance segmentation compatible with autoware auto msgs.
Build CI won't work correctly because this package depends on cuda-related libraries. …
> Port lidar apollo instance segmentation to .auto

- perception/object_recognition/detection/tensorrt_yolo/include/tensorrt_yolo/nodelet.hpp
- perception/object_recognition/detection/tensorrt_yolo/package.xml
- perception/object_recognition/detection/tensorrt_yolo/src/nodelet.cpp
Signed-off-by: wep21 <border_goldenmarket@yahoo.co.jp>
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGui …
> Port tensorrt yolo to .auto

- planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/README.md
translate README.md in English …
> update README.md in obstacle avoidance planner

- sensing/preprocessor/pointcloud/pointcloud_preprocessor/docs/OccupancyGridMapOutlierFilter.md
- vehicle/util/vehicle_info_util/Readme.md
- vehicle/util/vehicle_info_util/media/vehicle_info.drawio.svg
> [vehicle_info_util] add readme

- planning/mission_planning/mission_planner/include/mission_planner/goal_pose_visualizer.hpp
- planning/mission_planning/mission_planner/include/mission_planner/lanelet2_impl/mission_planner_lanelet2.hpp
- planning/mission_planning/mission_planner/include/mission_planner/mission_planner_base.hpp
- planning/mission_planning/mission_planner/lib/mission_planner_base.cpp
- planning/mission_planning/mission_planner/package.xml
- planning/mission_planning/mission_planner/src/goal_pose_visualizer/goal_pose_visualizer.cpp
- planning/mission_planning/mission_planner/src/mission_planner_lanelet2/mission_planner_lanelet2.cpp
Signed-off-by: Kosuke Murakami <kosuke.murakami@tier4.jp> …
> port mission planner

- perception/object_recognition/detection/roi_cluster_fusion/include/roi_cluster_fusion/roi_cluster_fusion_nodelet.hpp
- perception/object_recognition/detection/roi_cluster_fusion/src/roi_cluster_fusion_nodelet.cpp
- port roi_cluster_fusion package
- use **DetectedObjectsWithFeature** (https://github.com/tier4/AutowareArchitectureProposal_msgs/pull/3) instead of DynamicObjectWithFeatureArray
- subscribe topic type: DynamicObjectWithFeatureArray -> **DetectedObjectsWithFeature**
- publish topic type: DynamicObjectWithFeatureArray -> **DetectedObjects**
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the …
> port roi cluster fusion

- perception/object_recognition/detection/euclidean_cluster/include/euclidean_cluster/utils.hpp
- perception/object_recognition/detection/euclidean_cluster/lib/utils.cpp
- perception/object_recognition/detection/euclidean_cluster/package.xml
- perception/object_recognition/detection/euclidean_cluster/src/euclidean_cluster_node.cpp
- perception/object_recognition/detection/euclidean_cluster/src/euclidean_cluster_node.hpp
- perception/object_recognition/detection/euclidean_cluster/src/voxel_grid_based_euclidean_cluster_node.cpp
- perception/object_recognition/detection/euclidean_cluster/src/voxel_grid_based_euclidean_cluster_node.hpp
.auto porting
use https://github.com/tier4/AutowareArchitectureProposal_msgs/pull/3. 
```
cd src/autoware/msgs/autoware_iv_msgs
git remote add wep21 https://github.com/wep21/AutowareArchitectureProposal_msgs.git
git fetch wep21
git checkout wep21/feature/add-detected-object-with-feature
```
- **Check spelling**: NOT required to pass …
> port euclidean_cluster

- perception/object_recognition/detection/lidar_centerpoint/README.md
- perception/object_recognition/detection/lidar_centerpoint/include/lidar_centerpoint/node.hpp
- perception/object_recognition/detection/lidar_centerpoint/package.xml
- perception/object_recognition/detection/lidar_centerpoint/src/node.cpp
.auto porting
- autoware_perception_msgs -> autoware_auto_perception_msgs.
I checked that detected objects are published. …
> port lidar_centerpoint

- system/velodyne_monitor/Readme.md
add readme of velodyne monitor
Check the readme …
> [Velodyne monitor]add readme

- common/util/rviz_plugins/autoware_perception_rviz_plugin/src/tools/car_pose.cpp
- common/util/rviz_plugins/autoware_perception_rviz_plugin/src/tools/pedestrian_pose.cpp
- common/util/rviz_plugins/autoware_perception_rviz_plugin/src/tools/unknown_pose.cpp
port autoware_perception_rviz_plugin to .auto …
> port autoware_perception_rviz_plugin

- control/shift_decider/README.md
add readme to shift decider
see README.md …
> [shift decider] add README.md

- sensing/preprocessor/gnss/gnss_poser/README.md
> doc gnss poser

- sensing/preprocessor/gnss/geo_pos_conv/README.md
> doc geo conv pos

- sensing/preprocessor/pointcloud/livox/livox_tag_filter/README.md
> doc livox tag filter

- vehicle/as/include/pacmod_interface/pacmod_interface.hpp
- vehicle/as/src/pacmod_interface/pacmod_interface.cpp
use velocity report in as (pacmod_interface) …
> [as]use velocity report

- perception/object_recognition/detection/detection_by_tracker/include/detection_by_tracker/detection_by_tracker_core.hpp
- perception/object_recognition/detection/detection_by_tracker/include/detection_by_tracker/utils.hpp
- perception/object_recognition/detection/detection_by_tracker/src/detection_by_tracker_core.cpp
- perception/object_recognition/detection/detection_by_tracker/src/utils.cpp
.auto porting
- DynamicObjectWithFeatureArray -> DetectedObjects, DetectedObjectsWithFeatrue and TrackedObjects …
> port detection by tracker

- sensing/preprocessor/pointcloud/tier4_pcl_extensions/README.md
> doc tier4 pcl extensions

- control/autoware_joy_controller/README.md
add README.md of autoware_joy_controller …
> update README.md in autoware_joy_controller

- sensing/preprocessor/image/image_transport_decompressor/README.md
> doc image transport decompressor

- vehicle/external_cmd_converter/include/external_cmd_converter/node.hpp
- vehicle/external_cmd_converter/launch/external_cmd_converter.launch.py
- vehicle/external_cmd_converter/launch/external_cmd_converter.launch.xml
- vehicle/external_cmd_converter/package.xml
- vehicle/external_cmd_converter/src/node.cpp
below change
- twist -> odometry
- control command stamped -> AckermannControlCommand
- shift stamped -> VehicleStateCommand
unchanged
- autoware_external_api_msgs
- gate_mode
- topic name for shift remain unchanged
changed
- ackermann_control_command
- gear_command
- odometry
pkg depends
https://github.com/tier4/AutowareArchitectureProposal.iv/pull/519
colcon build pass
launch s
```
/control/current_gate_mode
/diagnostics
/external/selected/control_cmd
/external/selected/external_control_cmd
/external/selected/heartbeat
/external/selected/shift_cmd
/localization/kinematic_state
/parameter_events
/rosout
```
**PR Author should check the checkboxes below …
> [external_cmd_converter] apply autoware auto msgs

- common/util/web_controller/autoware_web_controller/www/autoware_web_controller/js/autoware_state.js
- common/util/web_controller/autoware_web_controller/www/autoware_web_controller/js/vehicle_engage.js
- system/autoware_state_monitor/config/autoware_state_monitor.param.yaml
- system/autoware_state_monitor/config/autoware_state_monitor.planning_simulation.param.yaml
- system/emergency_handler/src/emergency_handler/emergency_handler_core.cpp
fix some packages
comment out Planning/Control/Simulator module from planning_simulator.launch.xml
$ros2 launch autoware_launch planning_simulator.launch.xml vehicle_id:=default vehicle_model:=[VEHICLE_MODEL] sensor_model:=[SENSOR_MODEL] map_path:=[MAP_PATH]
(Please check that no modules die.)
web_controller:
Access to: http://localhost:8085/autoware_web_controller/
force-reload(Ctrl+F5) may be required. 
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the …
> [autowere_web_controller/autoware_state_monitor/emergency_handler]fix some packages

- localization/pose_estimator/ndt_scan_matcher/ndt_pcl_modified/README.md
Add README.md for ndt_pcl_modified
Check README.md.
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuidel …
> add ndt_pcl_modified readme

- system/autoware_version/README.md
> Add readme of autoware_version

- perception/object_recognition/detection/object_merger/README.md
- perception/object_recognition/detection/object_merger/src/object_association_merger/data_association/data_association.cpp
> add README of object_merger

- localization/pose_twist_fusion_filter/ekf_localizer/README.md
add odom topic to README.md(related #501). …
> [ekf_localizer] update README.md

- perception/object_segmentation/compare_map_segmentation/README.md
> doc compare map segmentation

- perception/object_recognition/detection/tensorrt_yolo/README.md
Update document for tensorrt yolo …
> Update document for tensorrt yolo

- perception/object_recognition/detection/euclidean_cluster/README.md
add README of euclidean_cluster …
> add README of euclidean_cluster

- system/util/dummy_diag_publisher/README.md
Add README in dummy diag publisher. …
> add README in dummy diag publisher

- planning/scenario_planning/scenario_selector/src/scenario_selector_node/scenario_selector_node.cpp
initialize pointer before it's accessed …
> [scenario selector] fix bug

- perception/object_recognition/detection/object_range_splitter/README.md
add README of object_range_splitter …
> add README of object_range_splitter

- perception/object_segmentation/ground_segmentation/README.md
> doc ground segmentation

- awapi/awapi_awiv_adapter/package.xml
awapi_awiv_adapter depends on autoware_iv_auto_msgs_converter, which has only one header file and depends on autoware_external_api_msgs.
So this dependency (autoware_external_api_msg) has to be in awapi_awiv_adapter package.xml as well to pass building
- **Check spelling**: NOT required to pass before the merge. It is up to the …
> fix package.xml of awapi_awiv_adapter

- perception/object_recognition/detection/tensorrt_yolo/lib/include/calibrator.hpp
> Fix build failure on jetson

- common/util/rviz_plugins/autoware_auto_perception_rviz_plugin/README.md
fix readme sentence pointed out in https://github.com/tier4/AutowareArchitectureProposal.iv/pull/631#discussion_r748993219 …
> fix readme sentence grammar

- perception/object_recognition/detection/tensorrt_yolo/src/nodelet.cpp
> Fix invalid vector access

- planning/scenario_planning/common/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp
- planning/scenario_planning/common/motion_velocity_smoother/src/trajectory_utils.cpp
- planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/src/node.cpp
Fix planning module
- fix topic name (/localization/odometry -> /localization/kinematic_state)
- fix linear interpolation in motion_velocity_smoother
launch planning simulator without control/awapi modules
$ros2 topic echo /planning/scenario_planning/scenario_selector/trajectory --no-arr
(Check that all planning module works)
- …
> [planning module]fix bug

- sensing/preprocessor/pointcloud/pointcloud_preprocessor/docs/distortion-corrector.md
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/include/pointcloud_preprocessor/distortion_corrector/distortion_corrector.hpp
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/src/distortion_corrector/distortion_corrector.cpp
> fix distortion corrector in pointcloud preprocessor

- simulator/util/fault_injection/README.md
Updated fault injection readme to follow the template.
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGui …
> update readme in fault injection

- perception/object_recognition/prediction/map_based_prediction/src/map_based_prediction.cpp
Fix map based prediction
Run planning_simulator
generate dummy car (5~10m/s)
Original: map_based_prediction module dies with following error.
```
[map_based_prediction-24] terminate called after throwing an instance of 'std::length_error'
[map_based_prediction-24]   what():  Exceeded upper bound
[ERROR] [map_based_prediction-24]: process has died [pid 2908233, exit code -6, cmd '/home/kimura/git/autoware.proj.auto/install/map_based_prediction/lib/map_based_prediction/map_based_prediction --ros-args -r __node:=map_based_prediction -r __ns:=/perception/object_recognition/prediction --params-file /tmp/launch_params_51123cvw --params-file /tmp/launch_params_gl4nd6oe --params-file /tmp/launch_params_zxbb6cpz -r objects:=/perception/object_recognition/objects -r /vector_map:=/map/vector_map -r …
```
> consider upper size of path

- common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/velocity_history.cpp
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/src/concatenate_data/concatenate_data_nodelet.cpp
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/src/distortion_corrector/distortion_corrector.cpp
- simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
- vehicle/pacmod_interface/src/pacmod_interface/pacmod_interface.cpp
- vehicle/ssc_interface/src/ssc_interface.cpp
> update to support velocity report header

- perception/traffic_light_recognition/traffic_light_classifier/README.md
This is a patch PR for https://github.com/tier4/AutowareArchitectureProposal.iv/pull/649 . …
> Update label explanation

- perception/object_recognition/detection/shape_estimation/README.md
> Update document for shape estimation

- perception/traffic_light_recognition/traffic_light_classifier/README.md
update README of traffic_light_classifier …
> update README of traffic_light_classifier

- common/util/rviz_plugins/autoware_state_rviz_plugin/README.md
- common/util/rviz_plugins/autoware_state_rviz_plugin/src/autoware_state_panel.cpp
- planning/scenario_planning/common/motion_velocity_optimizer/package.xml
- planning/scenario_planning/common/motion_velocity_optimizer/scripts/closest_velocity_checker.py
- planning/scenario_planning/common/motion_velocity_optimizer/scripts/trajectory_visualizer.py
- planning/scenario_planning/common/motion_velocity_smoother/scripts/closest_velocity_checker.py
- planning/scenario_planning/common/motion_velocity_smoother/scripts/trajectory_visualizer.py
- simulator/simple_planning_simulator/launch/simple_planning_simulator.launch.py
Fix /vehicle/status... topic name/type …
> FIx vehicle status topic name/type

- vehicle/pacmod_interface/launch/pacmod_additional_debug_publisher.launch.xml
- vehicle/pacmod_interface/launch/pacmod_interface.launch.xml
- vehicle/pacmod_interface/src/pacmod_interface/pacmod_diag_publisher.cpp
- vehicle/pacmod_interface/src/pacmod_interface/pacmod_interface.cpp
Fix topic name of pacmod_interface
Refrence: pub/sub of pacmod3_driver
```
/pacmod3_driver
Subscribers:
/accel_cmd: pacmod3_msgs/msg/SystemCmdFloat
/brake_cmd: pacmod3_msgs/msg/SystemCmdFloat
/can_tx: can_msgs/msg/Frame
/parameter_events: rcl_interfaces/msg/ParameterEvent
/shift_cmd: pacmod3_msgs/msg/SystemCmdInt
/steering_cmd: pacmod3_msgs/msg/SteeringCmd
/turn_cmd: pacmod3_msgs/msg/SystemCmdInt
Publishers:
/accel_aux_rpt: pacmod3_msgs/msg/AccelAuxRpt
/accel_rpt: pacmod3_msgs/msg/SystemRptFloat
/all_system_statuses: pacmod3_msgs/msg/AllSystemStatuses
/brake_aux_rpt: pacmod3_msgs/msg/BrakeAuxRpt
/brake_rpt: pacmod3_msgs/msg/SystemRptFloat
/can_rx: can_msgs/msg/Frame
/component_rpt: pacmod3_msgs/msg/ComponentRpt
/enabled: std_msgs/msg/Bool
/global_rpt: pacmod3_msgs/msg/GlobalRpt …
```
> [pacmod_interface]fix topic name

- localization/twist_estimator/gyro_odometer/README.md
> [gyro_odometer]add readme

- sensing/preprocessor/pointcloud/pointcloud_preprocessor/src/concatenate_data/concatenate_data_nodelet.cpp
Fix pointcloud preprosessor.
- Initialize pointer before it's accessed …
> [pointcloud preprocessor]initialize pointer

- control/trajectory_follower_nodes/src/lateral_controller_node.cpp
- control/trajectory_follower_nodes/src/latlon_muxer_node.cpp
- control/trajectory_follower_nodes/src/longitudinal_controller_node.cpp
- control/trajectory_follower_nodes/test/test_lateral_controller_node.cpp
- control/trajectory_follower_nodes/test/test_latlon_muxer_node.cpp
- control/trajectory_follower_nodes/test/test_longitudinal_controller_node.cpp
Rename topic names in trajectory_follower_nodes.
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideline …
> Change the topic name of the control_cmd to align them in trajectory_follower_node

- control/vehicle_cmd_gate/include/vehicle_cmd_gate/vehicle_cmd_gate.hpp
- control/vehicle_cmd_gate/launch/vehicle_cmd_gate.launch.xml
- control/vehicle_cmd_gate/package.xml
- control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
fix topic 
add this temporary in launch
```
<include file="$(find-pkg-share autoware_global_parameter_loader)/launch/global_params.launch.py">
<arg name="vehicle_model" value="$(var vehicle_model)"/>
</include>
```
ros2 launch vehicle_cmd_gate vehicle_cmd_gate.launch.xml vehicle_model:=lexus
```
ros2 topic list
1637054912.184630 [115]       ros2: selected interface "lo" is not multicast-capable: disabling multicast
/api/autoware/get/emergency
/api/autoware/get/engage
/autoware/engage
/control/command/control_cmd
/control/command/emergency_cmd
/control/command/gear_cmd
/control/command/hazard_lights_cmd
/control/command/turn_indicators_cmd
/control/current_gate_mode
/control/gate_mode_cmd
/control/shift_decider/gear_cmd
/diagnostics
/external/selected/control_cmd …
```
> fix emergency command

- sensing/preprocessor/pointcloud/pointcloud_preprocessor/include/pointcloud_preprocessor/distortion_corrector/distortion_corrector.hpp
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/package.xml
Adding necessary include to avoid following runtime error.
```
[component_container_mt-2] /opt/ros/galactic/lib/rclcpp_components/component_container_mt: symbol lookup error: /home/mars/autoware-auto/autoware.proj/install/pointcloud_preprocessor/lib/libpointcloud_preprocess
or_filter.so: undefined symbol: _ZN3tf27fromMsgIN13geometry_msgs3msg10Transform_ISaIvEEENS_9TransformEEEvRKT_RT0_   
```
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found …
> add tf2_geometry_msgs include to distorction_filter

- system/autoware_state_monitor/config/autoware_state_monitor.param.yaml
- system/autoware_state_monitor/config/autoware_state_monitor.planning_simulation.param.yaml
Autoware state does not changed from PLANNING state because the topic name described in config file is wrong.
In this PR, I fixed it.
Please check the topic name. …
> Fix topic name in config files in autoware_state_monitor

- localization/twist_estimator/pose2twist/src/README.md
> add readme in pose2twist

- control/trajectory_follower_nodes/include/trajectory_follower_nodes/lateral_controller_node.hpp
- control/trajectory_follower_nodes/include/trajectory_follower_nodes/longitudinal_controller_node.hpp
- control/trajectory_follower_nodes/src/lateral_controller_node.cpp
- control/trajectory_follower_nodes/src/longitudinal_controller_node.cpp
- control/trajectory_follower_nodes/test/test_lateral_controller_node.cpp
- control/trajectory_follower_nodes/test/test_longitudinal_controller_node.cpp
In AAP.iv, the type of current odometry is `nav_msgs::msg::Odometry`.
In this PR, fix type of current odometry `nav_msgs::msg::Odometry` instead of `autoware_auto_vehicle_msgs::msg::VehicleOdometry`.
Pass the CI test.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See …
> Fix type of current odometry in trajectory_follower_node to nav_msgs::msg::Odometry

- localization/twist_estimator/pose2twist/src/README.md
> fix readme

- perception/object_segmentation/compare_map_segmentation/CMakeLists.txt
I fixed cmake to avoid following warning.
```
not found: "/home/mars/autoware-auto/autoware.proj/install/compare_map_segmentation/share/compare_map_segmentation/local_setup.bash"
```
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to …
> fix cmake of compare_map_segmentation

- perception/traffic_light_recognition/traffic_light_ssd_fine_detector/README.md
Adding readme for traffic light ssd fine detector
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuidelin …
> add readme for traffic light ssd fine detector

- perception/object_segmentation/ground_segmentation/launch/scan_ground_filter.launch.py
> [scan_ground] fix plugin name

- simulator/simple_planning_simulator/launch/simple_planning_simulator.launch.py
> fix topic name

- control/shift_decider/launch/shift_decider.launch.xml
- control/shift_decider/src/shift_decider.cpp
Fix topic name in shift_decider.
Pass the CI test.
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideli …
> Fix topic name in shift_decider

- planning/scenario_planning/common/motion_velocity_smoother/scripts/closest_velocity_checker.py
> port closest velocity checker

- common/util/autoware_utils/README.md
> add readme in autoware_utils

- common/math/kalman_filter/README.md
> add README in kalman_filter

- control/external_cmd_selector/include/external_cmd_selector/external_cmd_selector_node.hpp
- control/external_cmd_selector/launch/external_cmd_selector.launch.py
- control/external_cmd_selector/launch/external_cmd_selector.launch.xml
- control/external_cmd_selector/package.xml
- control/external_cmd_selector/src/external_cmd_selector/external_cmd_selector_node.cpp
Fix publisher in external_cmd_selector.
Related launcher PR:
https://github.com/tier4/AutowareArchitectureProposal_launcher/pull/116
Pass the CI test and please check the code.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the …
> Fix publisher in external_cmd_selector

- localization/pose_twist_fusion_filter/stop_filter/README.md
- localization/pose_twist_fusion_filter/stop_filter/include/stop_filter/stop_filter.hpp
- localization/pose_twist_fusion_filter/stop_filter/src/stop_filter.cpp
remove twist publisher from stop_filter packages(stop filter subscribe and publish odometry topic #520 ) …
> [stop filter] remove twist publisher

- localization/util/pose_initializer/README.md
add readme in `pose_initialzier` …
> add readme in pose initializer

- control/external_cmd_converter/launch/external_cmd_converter.launch.xml
- system/emergency_handler/launch/emergency_handler.launch.xml
use hazard_lights_cmd/gear_cmd
Confirm hazard/gear cmd with planning-sim …
> [emergency_handler/external_cmd_converter]fix topic name

- planning/scenario_planning/common/motion_velocity_smoother/scripts/trajectory_visualizer.py
> port trajectory visualizer

- planning/scenario_planning/common/motion_velocity_smoother/include/motion_velocity_smoother/motion_velocity_smoother_node.hpp
- planning/scenario_planning/common/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp
Add header for debug trajectories published by motion_velocity_smoother.
Without this change, we can't visualize them with debug tools.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add …
> add header for debug trajectories

- awapi/awapi_awiv_adapter/launch/awapi_awiv_adapter.launch.xml
connect awapi topics
```
/vehicle/status/battery_charge
/vehicle/status/control_mode
/vehicle/status/gear_status
/vehicle/status/hazard_lights_status
/vehicle/status/steering_status
/vehicle/status/turn_indicators_status
/vehicle/status/velocity_status
```
- **Check spelling**: NOT required to pass before the merge. It is up to the …
> fix awapi topics

- control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker_node.hpp
- control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp
Please check that the `control_container` won't die when the initialpose is set far from the trajectory. …
> Add empty trajectory guard in lane_departure_checker

- control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker_node.hpp
- control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp
> Fix lane departure

- awapi/awapi_awiv_adapter/launch/awapi_relay_container.launch.py
awapi gets old route topic so fixed it
autoware_auto_planning_msgs/msg/HADMapRoute
autoware_planning_msgs/msg/Route
```
Node name: put_route_relay
Node namespace: /awapi
Topic type: autoware_auto_planning_msgs/msg/HADMapRoute
```
see in psim then echo route topic
```
- primitives:
- id: 122
primitive_type: lane
preferred_primitive_id: 122
- primitives:
- id: 46
primitive_type: lane
preferred_primitive_id: 46
...
```
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to …
> auto/fix psim route 

- simulator/simple_planning_simulator/launch/simple_planning_simulator.launch.py
Fix warning
`[WARNING] [launch_ros.actions.node]: Parameter file path is not a file: /home/isamu-takagi/projects/autoware.proj.proposal/install/simple_planning_simulator/share/simple_planning_simulator/param/vehicle_characteristics.param.param.yaml`
- **Check spelling**: NOT required to pass before the merge. It is up to the …
> Fix psim param path

- localization/pose_estimator/ndt_scan_matcher/ndt_scan_matcher/README.md
> add ndt_scan_matcher readme

- system/util/dummy_infrastructure/README.md
add readme to dummy infrastructure
to see readme
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideline …
> add readme [dummy infrastructure]

- localization/pose_twist_fusion_filter/stop_filter/launch/stop_filter.launch.xml
remove topic remap from launch filter in stop filter package.
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/Clang …
> remove topic remap from launch file

- perception/object_recognition/detection/euclidean_cluster/launch/euclidean_cluster.launch.py
- perception/object_recognition/detection/euclidean_cluster/launch/euclidean_cluster.launch.xml
- perception/object_recognition/detection/euclidean_cluster/launch/voxel_grid_based_euclidean_cluster.launch.py
- perception/object_recognition/detection/euclidean_cluster/launch/voxel_grid_based_euclidean_cluster.launch.xml
- perception/object_recognition/detection/euclidean_cluster/package.xml
- fix topic name : /sensing/lidar/no_ground/pointcloud -> /perception/object_segmentation/pointcloud …
> auto fix no ground pointcloud topic name

- awapi/awapi_awiv_adapter/launch/awapi_relay_container.launch.py
- awapi/awapi_awiv_adapter/package.xml
> Fix topic type of awapi relay

- perception/traffic_light_recognition/traffic_light_ssd_fine_detector/src/nodelet.cpp
declare variables before subscriber registration to avoid bug.
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/Clan …
> declare variables before subscriber registration

- planning/scenario_planning/common/motion_velocity_smoother/README.md
- planning/scenario_planning/common/motion_velocity_smoother/motion_velocity_smoother-design.ja.md
> fix osqp link

- planning/mission_planning/mission_planner/README.md
> Modify readme for mission planner

- .github/workflows/build_and_test_pr.yml
fix clang_tidy_pr
https://github.com/tier4/AutowareArchitectureProposal.iv/runs/4259999021?check_suite_focus=true
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell …
> add pacmod3 depend for clang_tidy_pr

- awapi/awapi_awiv_adapter/launch/awapi_awiv_adapter.launch.xml
- vehicle/raw_vehicle_cmd_converter/launch/raw_vehicle_converter.launch.xml
adapt to "new pacmod3" message
take a look at …
> fix door cmd topic

- control/control_performance_analysis/include/control_performance_analysis/control_performance_analysis_core.hpp
- control/control_performance_analysis/include/control_performance_analysis/control_performance_analysis_node.hpp
- control/control_performance_analysis/launch/controller_performance_analysis.launch.xml
- control/control_performance_analysis/package.xml
- control/control_performance_analysis/src/control_performance_analysis_core.cpp
- control/control_performance_analysis/src/control_performance_analysis_node.cpp
> port control_performance_analysis

- perception/object_recognition/detection/tensorrt_yolo/src/nodelet.cpp
> set image subscription qos as rmw_qos_profile_sensor_data explicitly

- control/control_performance_analysis/README.md
> add readme in control_performance_analysis

- perception/object_recognition/prediction/map_based_prediction/src/map_based_prediction.cpp
- substitue time steps for object-path
Check that intersection module works after merging this PR. …
> [map_based_preidction]substitute time steps

- localization/twist_estimator/gyro_odometer/README.md
- localization/twist_estimator/gyro_odometer/include/gyro_odometer/gyro_odometer_core.hpp
- localization/twist_estimator/gyro_odometer/launch/gyro_odometer.launch.xml
- localization/twist_estimator/gyro_odometer/src/gyro_odometer_core.cpp
remove input twist topic from gyro odometer package.
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuide …
> [gyro_odometer] remove input twist

- common/util/rviz_plugins/autoware_auto_perception_rviz_plugin/include/object_detection/predicted_objects_display.hpp
- common/util/rviz_plugins/autoware_auto_perception_rviz_plugin/include/object_detection/tracked_objects_display.hpp
patch for https://github.com/tier4/AutowareArchitectureProposal.iv/pull/721 …
> patch for PR721

- common/util/rviz_plugins/autoware_auto_perception_rviz_plugin/include/object_detection/predicted_objects_display.hpp
- common/util/rviz_plugins/autoware_auto_perception_rviz_plugin/include/object_detection/tracked_objects_display.hpp
- common/util/rviz_plugins/autoware_auto_perception_rviz_plugin/src/object_detection/predicted_objects_display.cpp
Fix bug of perception marker.
Check the object-path in rviz
Before merging this PR:
only 1 path is visualized.
After merging this PR:
All path are visualized. …
> [autoware_auto_perception_rviz_plugin]fix bug

- planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/src/utilities.cpp
avoid to set negative velocity for path in behavior_path_planner
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/Cl …
> [behavior_path_planner]fix velocity of pre_refined_goal

- simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
- simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared.cpp
- simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_ideal_steer_acc_geared.cpp
- use z-axis of trajectory for tf/odometry
- return 0 velocity when invalid gear is given
Check the z-axis of the vehicle with ThirdPersonFollower viewer …
> [simple_planning_simulator]fix bug

- planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/include/scene_module/traffic_light/scene.hpp
- planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/src/scene_module/traffic_light/scene.cpp
Fix `isTrafficSignalStop` function in traffic-signal module.
Reference:
https://github.com/tier4/AutowareArchitectureProposal.iv/blob/use-autoware-auto-msgs/perception/traffic_light_recognition/traffic_light_classifier/README.md
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See …
> [behvior_velocity_planner]fix traffic signal check

- simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared.cpp
- simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_ideal_steer_acc_geared.cpp
> fix gear process in sim

- awapi/awapi_awiv_adapter/Readme.md
- awapi/awapi_awiv_adapter/launch/awapi_awiv_adapter.launch.xml
- awapi/awapi_awiv_adapter/launch/awapi_relay_container.launch.py
- perception/traffic_light_recognition/traffic_light_classifier/README.md
- perception/traffic_light_recognition/traffic_light_classifier/launch/traffic_light_classifier.launch.xml
- perception/traffic_light_recognition/traffic_light_classifier/src/nodelet.cpp
- perception/util/visualizer/traffic_light_visualization/launch/traffic_light_map_visualizer.launch.xml
- perception/util/visualizer/traffic_light_visualization/launch/traffic_light_roi_visualizer.launch.xml
- perception/util/visualizer/traffic_light_visualization/src/traffic_light_roi_visualizer/nodelet.cpp
> Update traffic light topic name

- control/obstacle_collision_checker/README.md
- control/obstacle_collision_checker/launch/obstacle_collision_checker.launch.xml
- planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/launch/behavior_velocity_planner.launch.xml
- planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/README.md
- planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/launch/surround_obstacle_checker.launch.xml
- planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/surround_obstacle_checker-design.ja.md
- simulator/util/dummy_perception_publisher/launch/dummy_perception_publisher.launch.xml
- system/autoware_state_monitor/config/autoware_state_monitor.param.yaml
`/sensing/lidar/no_ground/pointcloud` -> `/perception/object_segmentation/pointcloud` …
> Fix no ground pointcloud topic name

- api/autoware_iv_internal_api_adaptor/CMakeLists.txt
- api/autoware_iv_internal_api_adaptor/package.xml
- api/autoware_iv_internal_api_adaptor/src/initial_pose.cpp
- api/autoware_iv_internal_api_adaptor/src/iv_state.cpp
- api/autoware_iv_internal_api_adaptor/src/iv_state.hpp
- simulator/simple_planning_simulator/include/simple_planning_simulator/simple_planning_simulator_core.hpp
- simulator/simple_planning_simulator/package.xml
- simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
> Fix for integration test

- localization/pose_twist_fusion_filter/ekf_localizer/README.md
- localization/pose_twist_fusion_filter/ekf_localizer/include/ekf_localizer/ekf_localizer.hpp
- localization/pose_twist_fusion_filter/ekf_localizer/launch/ekf_localizer.launch.xml
- localization/pose_twist_fusion_filter/ekf_localizer/src/ekf_localizer.cpp
remove input pose and twist topic from ekf_localizer(only use covariance topic) …
> [ekf_localizer] remove input pose and twist topic

- awapi/awapi_awiv_adapter/launch/awapi_awiv_adapter.launch.xml
- control/control_performance_analysis/README.md
- control/lane_departure_checker/README.md
- control/lane_departure_checker/launch/lane_departure_checker.launch.xml
- control/obstacle_collision_checker/launch/obstacle_collision_checker.launch.xml
- planning/scenario_planning/common/motion_velocity_smoother/motion_velocity_smoother-design.ja.md
`localization/odometry` -> `loclaization/kinematic_state` …
> Update twist topic name

- simulator/simple_planning_simulator/include/simple_planning_simulator/simple_planning_simulator_core.hpp
- simulator/simple_planning_simulator/launch/simple_planning_simulator.launch.py
- simulator/simple_planning_simulator/package.xml
- simulator/simple_planning_simulator/param/simple_planning_simulator_default.param.yaml
- simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
```
X　c3cb428ff (main) Change formatter to clang-format and black (#2332)
O　7832179d3 Feature/add ideal accel model interface (#1894) ⇨　すでにautoで考慮されてた
X　8a9af0afe add sort-package-xml hook in pre-commit (#1881)
考慮済み　883951fb3 Add autoware api (#1979)
X　58b6a7cd5 fix some typos (#1941)
X　13cd1dd2c Fix -Wunused-parameter (#1836)
O　59bb6be98 add cov pub in psim (#1732)
X　485f3ac49 Add markdownlint and prettier (#1661)
X　6d255448e Add pre-commit (#1560)
X　9f6a2ba3e Fix lint errors (#1378)
O　336cd4145 Refactor vehicle info util (#1305)
```
- **Build and test for PR / build-and-test-pr**: Required …
> Simple planning simulator update for latest develop

- common/util/rviz_plugins/autoware_planning_rviz_plugin/src/path/display.cpp
- common/util/rviz_plugins/autoware_planning_rviz_plugin/src/trajectory/display.cpp
- Fix planning_rviz_plugin to visualize backward path
Backward
Current:
Only forward trajectory is visualized by Trajectory Plugin (/planning/scenario_planning/trajectory)
with this PR:
Backward trajetory is also visualized
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See …
> [autoware_planning_rviz_plugin]visualize backward trajectory

- planning/route_handler/src/route_handler.cpp
bug fix: clear route_lanelets_ when initializing route_handler for mission_planner
Without this PR, sometimes mission planner outputs the old path after planning some routes.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the …
> clear route_lanelets_ when initializing route_handler for mission_planning

- vehicle/pacmod_interface/src/pacmod_interface/pacmod_interface.cpp
- Fix bug
publish turn indicator command from pacmod_interface
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/Clan …
> publish turn cmd

- control/shift_decider/README.md
fix topic name described in README. …
> fix/shift decider README

- sensing/preprocessor/pointcloud/pointcloud_preprocessor/docs/crop-box-filter.md
update readme of crop_box_filter …
> update readme of crop_box_filter

- sensing/preprocessor/pointcloud/pointcloud_preprocessor/README.md
- sensing/preprocessor/pointcloud/pointcloud_preprocessor/docs/downsample-filter.md
update readme of downsample_filter …
> update readme of downsample_filter

- vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/README.md
- Add description about diagnostics published by accel_brake_map_calibrator
etc …
> [accel brake map]update readme

- build_depends.repos
I fixed aap_api_msgs branch on build_depends.repos
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideli …
> change aap_api_msgs target branch

- perception/object_recognition/tracking/multi_object_tracker/src/tracker/model/pedestrian_tracker.cpp
Due to a porting error, the size of the pedestrian was set to a fixed value after tracking. …
> fix pedestrian shape

- system/system_monitor/CMakeLists.txt
- system/system_monitor/config/cpu_monitor.param.yaml
- system/system_monitor/config/hdd_monitor.param.yaml
- system/system_monitor/config/mem_monitor.param.yaml
- system/system_monitor/config/net_monitor.param.yaml
- system/system_monitor/docs/topics_cpu_monitor.md
- system/system_monitor/docs/topics_mem_monitor.md
- system/system_monitor/docs/topics_net_monitor.md
- system/system_monitor/docs/traffic_reader.md
- system/system_monitor/include/system_monitor/cpu_monitor/cpu_monitor_base.hpp
- system/system_monitor/include/system_monitor/hdd_monitor/hdd_monitor.hpp
- system/system_monitor/include/system_monitor/mem_monitor/mem_monitor.hpp
- system/system_monitor/include/system_monitor/net_monitor/net_monitor.hpp
- system/system_monitor/include/traffic_reader/traffic_reader.hpp
- system/system_monitor/reader/traffic_reader/traffic_reader.cpp
- system/system_monitor/src/cpu_monitor/cpu_monitor_base.cpp
- system/system_monitor/src/hdd_monitor/hdd_monitor.cpp
- system/system_monitor/src/mem_monitor/mem_monitor.cpp
- system/system_monitor/src/net_monitor/net_monitor.cpp
The current implementation of system_monitor is not based on performance measurement results.
So the system_monitor should be improved to check hazardous conditions more accurately on computer according to measurement results. 
- CPU Temperature (updated)
No longer need to handle CPU temperature error because there is a function to check thermal throttling event in system_monitor.
- CPU Usage (updated)
Changed the way to check threshold.
- Memory Usage (updated)
Changed the way to check threshold.
- HDD Usage (updated)
Changed the way to check threshold.
- Network Usage (updated)
This criteria is less related to the functional safety, so removed the processing to determine a warning and error state.
- Network Traffic  (new)
This function is newly implemented to grasp network traffic.
**PR …
> Improve system monitor based on measurement results

- control/external_cmd_selector/README.md
> add readme in external cmd selector

- api/autoware_iv_internal_api_adaptor/README.md
> Fix api readme

- system/autoware_state_monitor/include/autoware_state_monitor/state_machine.hpp
- system/autoware_state_monitor/launch/autoware_state_monitor.launch.xml
- system/autoware_state_monitor/package.xml
- system/autoware_state_monitor/src/autoware_state_monitor_node/autoware_state_monitor_node.cpp
- system/autoware_state_monitor/src/autoware_state_monitor_node/state_machine.cpp
https://github.com/tier4/autoware.iv/pull/2389
と同じ内容のPRになります
同じ変更内容になっていること …
> add angle restriction for arrived goal

- planning/scenario_planning/common/motion_velocity_smoother/scripts/closest_velocity_checker.py
https://github.com/tier4/autoware.iv/pull/2350
と同じ変更です
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGui …
> add distance to stopline to `closest_velocity_checker`

- map/lanelet2_extension/lib/utilities.cpp
Fix bug of `isInLanelet()` in lanelet2_extention package.
If `radius` is equal to zero, which is the default input value, the inequality is not proper.
The default input is only used in [here](https://github.com/tier4/AutowareArchitectureProposal.iv/blob/e9d7744ac5858cb71f56eafa14ace853f1054edb/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/src/scene_module/lane_change/util.cpp#L445).
Please check the code.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before …
> Fix isInLanelet

- map/lanelet2_extension/lib/query.cpp
fix angle diff calculation of mission_planner …
> fix angle diff calculation of mission_planner

- perception/obstacle_segmentation/elevation_map_loader/include/elevation_map_loader/elevation_map_loader_node.hpp
- perception/obstacle_segmentation/elevation_map_loader/src/elevation_map_loader_node.cpp
fix code to declare parameter on constructor. …
> fix elevation map declare param

- planning/scenario_planning/common/motion_velocity_smoother/src/smoother/smoother_base.cpp
Fix bug that the meaning of `decel_distance_before_curve` and `decel_distance_after_curve` is reversed. …
> Fix curve deceleration

- perception/obstacle_segmentation/elevation_map_loader/README.md
Change readme style to fit to template. …
> [elevation_map_loader] update readme

- planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/src/utilities.cpp
- bug fix
Fix searching of goal index in behavior_path_planner.
(In some cases, the trajectory goes to the goal on the way) …
> fix index-search in setGoal

- planning/scenario_planning/lane_driving/behavior_planning/turn_signal_decider/src/frenet_coordinate.cpp
Uターン路で往路と復路が重なるようなレーンにおいて、Uターン後にたまたま条件にあうレーンが探索され、後に探索されたレーンが選択される不具合があり、turn_signal_deciderから呼び出されるconvertToFrenetCoordinate3dでの算出に誤りがありましたので、修正PRを発行します。
関連PR：
https://github.com/tier4/autoware.iv/pull/2359
https://github.com/tier4/autoware.iv/pull/2367
- **Check spelling**: NOT required to pass before the merge. It is up to the …
> fix frenet_coordinate
