tier4/AutowareArchitectureProposal.iv

localization/util/autoware_localization_srvs/CMakeLists.txt, localization/util/autoware_localization_srvs/package.xml, localization/util/autoware_localization_srvs/srv/PoseWithCovarianceStamped.srv
* Tested the build with ROS2 Foxy by
* following [this](https://docs.google.com/document/d/1eqkWCKHZfHcaY4uvs1eSrIBPU6AZCkyxJI3XoRU1WeU/edit) but entering an AutowareAuto ADE environment instead (Foxy `.aderc` taken from [here](https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/merge_requests/637#note_424910484))
* running `colcon build --packages-up-to autoware_localization_srvs` in the `ros2` branch of the AutowareArchitectureProposal repo (with this branch checked out in the `autoware/autoware.iv` sub-repo)
=> Port autoware_localization_srvs

sensing/preprocessor/gnss/geo_pos_conv/CHANGELOG.rst, sensing/preprocessor/gnss/geo_pos_conv/CMakeLists.txt, sensing/preprocessor/gnss/geo_pos_conv/package.xml
The conversion of this package was fairly straightforward because its a library with no executable
* Follow [this convention](https://index.ros.org/doc/ros2/Tutorials/Ament-CMake-Documentation/#building-a-library) for the structuring the `CMakelist.txt`. I am new to ROS2 so please let me know if this has not been executed correctly, or if I have added any redundancy. 
* Update the changelog the increased the release number to 2.0.0.
* Update the package.xml
* There are no code changes required in any of the source files as they are purely C++ with no ROS dependencies.
This was a little difficult to test due to the lack of test code however, I was also porting the `gnss_poser` package simultaneously and making sure that the package could be found using CMake. Let me know if there are any …
=> ROS2 Porting: geo_pos_conv

.github/workflows/build_and_test.yml
This adds `apt update` command before running `rosdep install` so that it can find packages.
This should fix the ci error occurring in this PR https://github.com/tier4/Pilot.Auto/pull/11 for example.
=> add apt update command to ci

control/shift_decider/CMakeLists.txt, control/shift_decider/include/shift_decider/shift_decider.h, control/shift_decider/launch/shift_decider.launch, control/shift_decider/launch/shift_decider.launch.xml, control/shift_decider/package.xml, control/shift_decider/src/main.cpp, control/shift_decider/src/shift_decider.cpp
I ported the code similar in a similar fashion to what @nnmm did with the `vehicle_cmd_gate` and took the review comments given on that [PR](https://github.com/tier4/autoware.iv.universe/pull/3). The PR currently suffers from the same limitation that a jump in sim time would be treated differently than in the previous version. Before implementing a hack, we should agree on a common solution and then implement it in all packages to be ported.
The first commit of this PR is the previous ROS1 version of the code.
The node builds and runs fine with 
ros2 launch shift_decider shift_decider.launch.xml
@nnmm @dejanpan @mitsudome-r
=> Port shift decider to ros2

.github/workflows/build_and_test.yml
This should enable the installation of keyboard-configuration in CI which is blocking this PR https://github.com/tier4/Pilot.Auto/pull/11.
`DEBIAN_FRONTEND=noninteractive` should be set after sudo, not before. (https://askubuntu.com/questions/876240/how-to-automate-setting-up-of-keyboard-configuration-package)
=> set DEBIAN_FRONTEND=noninteractive after sudo

localization/pose_estimator/ndt_scan_matcher/ndt_omp/CMakeLists.txt, localization/pose_estimator/ndt_scan_matcher/ndt_omp/apps/align.cpp, localization/pose_estimator/ndt_scan_matcher/ndt_omp/package.xml
* Removed ROS as a dependency, it was just used for its wall timer
* Replaced `pcl_ros` by `PCL`
* See comments for CMake questions
* There is a large number of warnings from using deprecated `pcl` functions. Maybe this already has been fixed in the newest version of https://github.com/koide3/ndt_omp?
=> Port ndt_omp to ROS2

common/util/autoware_utils/CMakeLists.txt, common/util/autoware_utils/include/autoware_utils/geometry.h, common/util/autoware_utils/package.xml
This package is not in the list of packages to port. However, perhaps this is a good place for time conversion functions, which I need for ndt_scan_matcher.
I changed nothing interesting, I only added one missing header.
=> Port autoware_utils

localization/twist_estimator/gyro_odometer/CMakeLists.txt, localization/twist_estimator/gyro_odometer/include/gyro_odometer/gyro_odometer_core.h, localization/twist_estimator/gyro_odometer/launch/gyro_odometer.launch.xml, localization/twist_estimator/gyro_odometer/package.xml, localization/twist_estimator/gyro_odometer/src/gyro_odometer_core.cpp, localization/twist_estimator/gyro_odometer/src/gyro_odometer_node.cpp
Port `gyro_odometer` package. This package was straightforward with not many dependencies.
1. Using the ADE environment in foxy, compile the package
```
colcon build
. install/setup.bash
```
2. Launch the package
```
ros2 launch gyro_odometer gyro_odometer.launch.xml
```
=> ROS2 Porting: gyro_odometer

localization/twist_estimator/pose2twist/CMakeLists.txt, localization/twist_estimator/pose2twist/include/pose2twist/pose2twist_core.h, localization/twist_estimator/pose2twist/launch/pose2twist.launch.xml, localization/twist_estimator/pose2twist/package.xml, localization/twist_estimator/pose2twist/src/pose2twist_core.cpp, localization/twist_estimator/pose2twist/src/pose2twist_node.cpp
This PR ports pose2twist from ROS1 to ROS2
Changes and notes I made during the port.
The naming of header files are all small letter in Ros2:
`<std_msgs/Float32.h> to <std_msgs/msg/float32.hpp>`
`geometry_msgs/PoseStamped.h to geometry_msgs/msg/pose_stamped.hpp`
=> ported pose2twist from ROS1 to ROS2

map/map_tf_generator/CMakeLists.txt, map/map_tf_generator/launch/map_tf_generator.launch.xml, map/map_tf_generator/nodes/map_tf_generator.cpp, map/map_tf_generator/package.xml
- `pcl` to `PCL`
- add msg conversion for pcl, which was not used in the original code since the raw pcl class can be used for a ROS1 subscriver.
- add `pcl_conversion` for `pcl::fromROSMsg<pcl::PointXYZ>()`.
You need to run rosdep before build for `pcl_conversions`.
```
rosdep update
rosdep install --from-paths src -i -y --rosdistro=$ROS_DISTRO
```
=> port map_tf_generator

.github/workflows/build_and_test.yml, map/lanelet2_extension/CMakeLists.txt, map/lanelet2_extension/include/lanelet2_extension/utility/message_conversion.h, map/lanelet2_extension/include/lanelet2_extension/utility/query.h, map/lanelet2_extension/include/lanelet2_extension/utility/utilities.h, map/lanelet2_extension/include/lanelet2_extension/visualization/visualization.h, map/lanelet2_extension/lib/message_conversion.cpp, map/lanelet2_extension/lib/mgrs_projector.cpp, map/lanelet2_extension/lib/query.cpp, map/lanelet2_extension/lib/utilities.cpp, map/lanelet2_extension/lib/visualization.cpp, map/lanelet2_extension/package.xml, map/lanelet2_extension/src/sample_code.cpp, map/lanelet2_extension/src/validation.cpp, map/lanelet2_extension/test/src/test_message_conversion.cpp, map/lanelet2_extension/test/src/test_projector.cpp, map/lanelet2_extension/test/src/test_query.cpp, map/lanelet2_extension/test/src/test_regulatory_elements.cpp, map/lanelet2_extension/test/src/test_utilities.cpp, map/lanelet2_extension/test/test_message_conversion.test, map/lanelet2_extension/test/test_projector.test, map/lanelet2_extension/test/test_query.test, map/lanelet2_extension/test/test_regulatory_elements.test, map/lanelet2_extension/test/test_utilities.test
This ports lanelet2_extension package to ROS2.
In order to make use of the library easier, I changed ROS loggers (ROS_INFO, ROS_WARN, ROS_ERROR) into standard messages. This is because the functions in the library can be called from anywhere in the source code, which might have bad access to rclcpp::logger(). The drawback is that the messages will not be recorded in the ros logging file anymore, but it will still show up in the terminal screen.
I also changed CI to remove `sudo` from `rosdep` commands since it was somehow failing to find `ros-foxy-lanelet2-*`  packages.
=> Port lanelet2 extension

.github/workflows/build_and_test.yml, build_depends.repos
This modifies CI to use autoware.proj.repos file from AutowareArchitectureProposal to clone any external dependencies.
=> Update ci to use repos file

common/math/osqp_interface/CMakeLists.txt, common/math/osqp_interface/package.xml
It doesn't use any ros functionality so the source code is unchanged, only `package.xml` and `CMakeLists.txt` needed to
be modified. But osqp is added through a vendor package created at https://github.com/tier4/osqp_vendor
To test this locally, eigen needs to be installed in the environment with
sudo apt install libeigen3-dev
This PR requires PR https://github.com/tier4/Pilot.Auto/pull/35 to be merged first and replaces https://github.com/tier4/Pilot.Auto/pull/14 as it introduces the same changes but with a streamlines history
=> Port osqp-interface to ros2

.github/workflows/build_and_test.yml
This PR changes the target branches for `push` and `pull_request` events to `ros2`
=> Fix target CI branches

control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp, localization/pose_twist_fusion_filter/ekf_localizer/src/ekf_localizer.cpp, perception/object_recognition/tracking/multi_object_tracker/src/multi_object_tracker_core.cpp, planning/scenario_planning/parking/freespace_planner/src/freespace_planner/freespace_planner_node.cpp, sensing/preprocessor/gnss/gnss_poser/src/gnss_poser_core.cpp, system/emergency_handler/src/emergency_handler_core.cpp, vehicle/as/src/pacmod_interface/pacmod_interface.cpp, vehicle/as/src/ssc_interface/ssc_interface.cpp, vehicle/raw_vehicle_cmd_converter/src/accel_map.cpp, vehicle/raw_vehicle_cmd_converter/src/brake_map.cpp
The duration arg for  RCLCPP_INFO_THROTTLE() is changed to [ms] from [s] in ROS2.
Some packages are using this function with a very short duration, they seem to be a mistake on porting.
Fix for these packages to use explicit ms duration.
=> Fix RCLCPP_INFO_THROTTLE duration unit

planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/CMakeLists.txt, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/data_manager.h, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/lane_changer.h, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/route_handler.h, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/state/aborting_lane_change.h, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/state/blocked_by_obstacle.h, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/state/common_functions.h, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/state/executing_lane_change.h, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/state/following_lane.h, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/state/forcing_lane_change.h, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/state/state_base_class.h, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/state/stopping_lane_change.h, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/state_machine.h, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/utilities.h, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/package.xml, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/data_manager.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/lane_change_planner_node.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/lane_changer.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/route_handler.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/state/aborting_lane_change.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/state/blocked_by_obstacle.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/state/common_functions.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/state/executing_lane_change.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/state/following_lane.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/state/forcing_lane_change.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/state/state_base_class.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/state/stopping_lane_change.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/state_machine.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/utilities.cpp
This ports lane_change_planner to ROS2.
Although the package is large, porting was generally straight forward except loggers where I had to pass down many logger and clock objects of rclcpp::Node. 
Since there are many file changes, it might be easier to review each commits.
=> Port lane change planner

build_depends.repos, localization/twist_estimator/pose2twist/package.xml, map/lanelet2_extension/package.xml, planning/mission_planning/mission_planner/package.xml
This adds updated version of geometry2 package to dependency until it is released as binary.
This has to be added to build_dependency.repos in order to pass CI for https://github.com/tier4/Pilot.Auto/pull/34
=> Add geometry2 to repos

common/math/osqp_interface/CMakeLists.txt, common/math/osqp_interface/package.xml
This PR introduces two fixes:
1. Eigen is consumed and exported properly to fix #63 
2. osqp lib is exported to correct linker errors with static libs
@nnmm This came out our discussion with @jilaada on PR https://github.com/tier4/Pilot.Auto/pull/24
the 2nd point bugged me for a week and I finally better understood what goes on behind the scenes. I will add some guidelines to the porting doc. You can't see it in this PR but in https://github.com/tier4/Pilot.Auto/pull/52 I can now drop this
```diff
modified   control/mpc_follower/CMakeLists.txt
@@ -43,9 +43,6 @@ set(MPC_FOLLOWER_HDR
)
ament_auto_add_executable(mpc_follower ${MPC_FOLLOWER_SRC} ${MPC_FOLLOWER_HDR})
-# TODO(Frederik.Beaujean) not clear why this isn't taken care of by `ament_auto_add_executable` but `ospq_interface`
-# isn't …
```
=> Fix osqp_interface dependencies

common/msgs/autoware_planning_msgs/CMakeLists.txt, common/msgs/autoware_planning_msgs/msg/VelocityLimit.msg, planning/scenario_planning/common/motion_velocity_optimizer/CMakeLists.txt, planning/scenario_planning/common/motion_velocity_optimizer/include/motion_velocity_optimizer/motion_velocity_optimizer.hpp, planning/scenario_planning/common/motion_velocity_optimizer/include/motion_velocity_optimizer/motion_velocity_optimizer_utils.hpp, planning/scenario_planning/common/motion_velocity_optimizer/include/motion_velocity_optimizer/optimizer/l2_pseudo_jerk_optimizer.hpp, planning/scenario_planning/common/motion_velocity_optimizer/include/motion_velocity_optimizer/optimizer/linf_pseudo_jerk_optimizer.hpp, planning/scenario_planning/common/motion_velocity_optimizer/include/motion_velocity_optimizer/optimizer/optimizer_base.hpp, planning/scenario_planning/common/motion_velocity_optimizer/package.xml, planning/scenario_planning/common/motion_velocity_optimizer/src/interpolate.cpp, planning/scenario_planning/common/motion_velocity_optimizer/src/motion_velocity_optimizer.cpp, planning/scenario_planning/common/motion_velocity_optimizer/src/motion_velocity_optimizer_utils.cpp, planning/scenario_planning/common/motion_velocity_optimizer/src/optimizer/pseudo_jerk_l2_optimizer.cpp, planning/scenario_planning/common/motion_velocity_optimizer/src/optimizer/pseudo_jerk_linf_optimizer.cpp
Remarks
- add autoware_planning_msgs/VelocityLimit.msg
- replace boost::shared_ptr to std::shared_ptr
- replace dynamic reconfigure to `add_on_set_parameters_callback`.
- add `blockUntilVehiclePositionAvailable` as in mpc_follower porting
TODO
=> port motion_velocity_optimizer

build_depends.repos
This adds dependency to gridmap-ros package for costmap_generator (https://github.com/tier4/Pilot.Auto/pull/93)
=> add gridmap-ros

planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/CMakeLists.txt, planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/config/adaptive_cruise_control.yaml, planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/config/obstacle_stop_planner.yaml, planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/include/obstacle_stop_planner/adaptive_cruise_control.hpp, planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/include/obstacle_stop_planner/debug_marker.hpp, planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/include/obstacle_stop_planner/node.hpp, planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/launch/obstacle_stop_planner.launch.xml, planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/package.xml, planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/src/adaptive_cruise_control.cpp, planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/src/debug_marker.cpp, planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/src/main.cpp, planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/src/node.cpp
Port of `obstacle-stop-planner` to ROS2. A couple of notes:
- In the `CMakeLists.txt` compile option `-O3` needs to be added for the `static constexpr` in the `adaptive_cruise_control.hpp` parameters to be compiled properly.
- In `node.cpp` line [212](https://github.com/tier4/Pilot.Auto/pull/86/files#diff-9493ac6ff50c82cecb25fb47d2f6fb1a6a512d07e8aad7d2693d94cc419a1107R212) I've replaced the `pcl_ros::transformPointCloud` usage with the `pcl::transformPointCloud` equivalent as `pcl_ros` is not available in ROS2 yet
=> Port obstacle stop planner

.github/workflows/build_and_test.yml, build_depends.repos, localization/twist_estimator/pose2twist/package.xml, map/lanelet2_extension/package.xml, planning/mission_planning/mission_planner/package.xml
https://github.com/ros/rosdistro/pull/27177 is now available through the ROS package repositories: I upgraded my system in ADE today and got 
```
$ apt show ros-foxy-tf2
Package: ros-foxy-tf2
Version: 0.13.6-1focal.20201028.172335
```
which is the version that has the PR required for `ndt_scan_matcher`.
=> Revert "Add geometry2 to repos (#76)"

build_depends.repos
Remove osqp and ublox now that they have been released to the ROS buildfarm.
=> Removed osqp and ublox from build_depends.repos

perception/object_recognition/prediction/map_based_prediction/CMakeLists.txt, perception/object_recognition/prediction/map_based_prediction/include/cubic_spline.hpp, perception/object_recognition/prediction/map_based_prediction/include/map_based_prediction.h, perception/object_recognition/prediction/map_based_prediction/include/map_based_prediction_ros.h, perception/object_recognition/prediction/map_based_prediction/launch/map_based_prediction.launch.xml, perception/object_recognition/prediction/map_based_prediction/package.xml, perception/object_recognition/prediction/map_based_prediction/src/map_based_prediction.cpp, perception/object_recognition/prediction/map_based_prediction/src/map_based_prediction_main.cpp, perception/object_recognition/prediction/map_based_prediction/src/map_based_prediction_ros.cpp
Port of `map_based_prediction` to ROS2.
I've added a `toHexString` function [here](https://github.com/tier4/Pilot.Auto/pull/95/files#diff-6609d065fa15d5b881b14c3a7b45a522484085c047f05d28f884ca8e27dda4b3R44) as it seems `unique_id::toHexString` is not available.
=> Port map based prediction

planning/scenario_planning/lane_driving/behavior_planning/turn_signal_decider/include/turn_signal_decider/data_manager.h, planning/scenario_planning/lane_driving/behavior_planning/turn_signal_decider/src/data_manager.cpp, planning/scenario_planning/lane_driving/behavior_planning/turn_signal_decider/src/turn_signal_decider_core.cpp
When turn_signal_decider is launched, it fails with bad weak_ptr.
```
terminate called after throwing an instance of 'std::bad_weak_ptr'
what():  bad_weak_ptr
```
This probably is due to calling shared_from_this() in constructor.
The document states that this must be referred by other shared_ptr(). Although the object is handled as shared_ptr in the main function, but that is the case after constructor has finished running.
This PR changes shared_from_this to raw pointer to avoid this error.
For reviewers:
Please test with `ros2 run turn_signal_decider turn_signal_decider` and make sure that the node does not die.
=> [turn_signal_decider] change weak_ptr to raw pointer

planning/scenario_planning/common/motion_velocity_optimizer/config/default_motion_velocity_optimizer.yaml, planning/scenario_planning/common/motion_velocity_optimizer/include/motion_velocity_optimizer/motion_velocity_optimizer.hpp, planning/scenario_planning/common/motion_velocity_optimizer/launch/motion_velocity_optimizer.launch.xml, planning/scenario_planning/common/motion_velocity_optimizer/src/motion_velocity_optimizer.cpp
motion_velocity_optimizer failed to startup from launch file.
This PR fixes:
* fix launch file: looks like the first port missed porting of launch file
* parameter file: parameter file did not have namespace declaration
* tf_buffer: it was using pointer without memory allocation. This PR changes it to member variable rather than pointer.
* parameter declaration: over_a_weight was declared twice in the code which throws an error. The latter was changed to getter function.
How to test:
Make sure that the node launch with the following command and does not terminate with segmentation fault.
`ros2 launch motion_velocity_optimizer motion_velocity_optimizer.launch.xml`
=> [ROS2 Porting] fix motion_velocity_optimizer

planning/scenario_planning/scenario_selector/CMakeLists.txt, planning/scenario_planning/scenario_selector/include/scenario_selector/scenario_selector_node.h, planning/scenario_planning/scenario_selector/launch/dummy_scenario_selector_lane_driving.launch.xml, planning/scenario_planning/scenario_selector/launch/dummy_scenario_selector_parking.launch.xml, planning/scenario_planning/scenario_selector/launch/scenario_selector.launch.xml, planning/scenario_planning/scenario_selector/package.xml, planning/scenario_planning/scenario_selector/src/scenario_selector_node/main.cpp, planning/scenario_planning/scenario_selector/src/scenario_selector_node/scenario_selector_node.cpp
Fairly straightforward port of the scenario_selector package - dependencies to topic tools package so ensure that the `ros2` branch of AutowareArchitectureProposal is up to date. 
Notable Changes:
* Remove boost dependencies
* `boost::function` -> `std::function`
* `boost::bind` -> `std::bind`
* Pull in `topic_tools` dependencies
Compilation should be successful and launch files should launch with issue. The launch files here do not come with default parameters so you will need to input these manually during launch, i.e:
```
ros2 launch scenario_selector dummy_scenario_selector_parking.launch.xml output_scenario:=test_out_scenario input_parking_trajectory:=test_in_traj output_trajectory:=test_out_traj
```
* Launch rostopic as a node in the launch file has been commented out - I am not …
=> ROS2 Porting: scenario_selector

vehicle/util/vehicle_info_util/CMakeLists.txt
Build as shared library to avoid linker problems downstream
blocks https://github.com/tier4/planning_simulator.iv.universe/pull/11
=> Vehicle shared lib

perception/object_recognition/detection/lidar_apollo_instance_segmentation/CMakeLists.txt, perception/object_recognition/detection/lidar_apollo_instance_segmentation/config/hdl-64.param.yaml, perception/object_recognition/detection/lidar_apollo_instance_segmentation/config/vlp-16.param.yaml, perception/object_recognition/detection/lidar_apollo_instance_segmentation/config/vls-128.param.yaml, perception/object_recognition/detection/lidar_apollo_instance_segmentation/include/lidar_apollo_instance_segmentation/cluster2d.h, perception/object_recognition/detection/lidar_apollo_instance_segmentation/include/lidar_apollo_instance_segmentation/debugger.h, perception/object_recognition/detection/lidar_apollo_instance_segmentation/include/lidar_apollo_instance_segmentation/detector.h, perception/object_recognition/detection/lidar_apollo_instance_segmentation/include/lidar_apollo_instance_segmentation/feature_generator.h, perception/object_recognition/detection/lidar_apollo_instance_segmentation/include/lidar_apollo_instance_segmentation/node.h, perception/object_recognition/detection/lidar_apollo_instance_segmentation/launch/lidar_apollo_instance_segmentation.launch.xml, perception/object_recognition/detection/lidar_apollo_instance_segmentation/lib/src/TrtNet.cpp, perception/object_recognition/detection/lidar_apollo_instance_segmentation/package.xml, perception/object_recognition/detection/lidar_apollo_instance_segmentation/src/cluster2d.cpp, perception/object_recognition/detection/lidar_apollo_instance_segmentation/src/debugger.cpp, perception/object_recognition/detection/lidar_apollo_instance_segmentation/src/detector.cpp, perception/object_recognition/detection/lidar_apollo_instance_segmentation/src/feature_map.cpp, perception/object_recognition/detection/lidar_apollo_instance_segmentation/src/main.cpp, perception/object_recognition/detection/lidar_apollo_instance_segmentation/src/node.cpp
This ports lidar_apollo_instance_segmentation package into ROS2.
Notes:
* Added init() function for LidarInstanceSegmentationNode class in order to use shared_from_this() function.
* Created param files for different models for better management of parameters
=> Port lidar apollo instance segmentation

simulator/simple_planning_simulator/launch/simple_planning_simulator.launch.xml, simulator/simple_planning_simulator/package.xml
This re-enables topic relay which was not available when this package was ported.
=> [simple_planning_simulator] add rostopic relay in launch file

planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/CMakeLists.txt, planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/config/blind_spot_param.yaml, planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/config/crosswalk_param.yaml, planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/config/detection_area_param.yaml, planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/config/intersection_param.yaml, planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/config/stop_line_param.yaml, planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/config/traffic_light_param.yaml, planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/launch/behavior_velocity_planner.launch.xml, planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp, vehicle/util/vehicle_info_util/include/vehicle_info_util/vehicle_info.hpp, vehicle/util/vehicle_info_util/src/vehicle_info.cpp
behavior_velocity_planner dies at intersection_module, where it refers to planner_data pointer before object is created in constructor.
This fixes the issue by handing over planner_data at constructor.
It also finishes porting of launch files (which I missed to review at first porting).
Make sure that node does not dies with segmentation fault with following command:
`ros2 launch behavior_velocity_planner behavior_velocity_planner.launch.xml`
=> [ROS2] Fix behavior velocity planner

planning/scenario_planning/common/motion_velocity_optimizer/launch/motion_velocity_optimizer.launch.xml, planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/launch/obstacle_avoidance_planner.launch.xml, planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/launch/obstacle_stop_planner.launch.xml, planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/launch/surround_obstacle_checker.launch.xml
This modifies launch files so that they can be used from autoware_launcher.iv.universe as in https://github.com/tier4/autoware_launcher.iv.universe/pull/9.
This will modify launch files so that some of the topics can be remapped through arguments.
=> Fix launch files

perception/traffic_light_recognition/traffic_light_map_based_detector/CMakeLists.txt, perception/traffic_light_recognition/traffic_light_map_based_detector/config/traffic_light_map_based_detector.yaml, perception/traffic_light_recognition/traffic_light_map_based_detector/include/traffic_light_map_based_detector/node.hpp, perception/traffic_light_recognition/traffic_light_map_based_detector/launch/traffic_light_map_based_detector.launch.xml, perception/traffic_light_recognition/traffic_light_map_based_detector/package.xml, perception/traffic_light_recognition/traffic_light_map_based_detector/src/main.cpp, perception/traffic_light_recognition/traffic_light_map_based_detector/src/node.cpp
Porting traffic light map detector module to ROS2.
Module has standard ROS interfaces, port:
[x] CMakeLists to use ament
[x] convert messages, rclcpp calls
[x] setup subscribers and publishers
=> Ros2 port traffic light map

sensing/preprocessor/pointcloud/pointcloud_preprocessor/launch/preprocessor.launch.xml
This is just an XML wrapper of the `preprocessor.launch.py`, but it might be useful to merge this as an example to load the python launch file from xml.
=> add preprocessor.launch.xml launch

control/mpc_follower/src/mpc_utils.cpp, localization/pose_estimator/ndt_scan_matcher/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp, perception/object_recognition/prediction/map_based_prediction/src/map_based_prediction_ros.cpp, perception/traffic_light_recognition/traffic_light_map_based_detector/src/node.cpp, planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/src/node.cpp, planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/src/scene_module/blind_spot/debug.cpp, planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/src/scene_module/crosswalk/debug.cpp, planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/src/scene_module/detection_area/debug.cpp, planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/src/scene_module/intersection/debug.cpp, planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/src/scene_module/stop_line/debug.cpp, planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/src/scene_module/traffic_light/debug.cpp, planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/src/debug.cpp, planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/src/node.cpp, planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/src/debug_marker.cpp, planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/src/node.cpp, planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/src/debug_marker.cpp, planning/scenario_planning/parking/costmap_generator/nodes/costmap_generator/costmap_generator_node.cpp, planning/scenario_planning/parking/costmap_generator/nodes/costmap_generator/object_map_utils.cpp, planning/scenario_planning/parking/freespace_planner/src/freespace_planner/freespace_planner_node.cpp, simulator/util/dummy_perception_publisher/src/node.cpp
The normal constructor uses nanoseconds instead. See https://github.com/tier4/AutowareArchitectureProposal/pull/135/files
=> Convert calls of Duration to Duration::from_seconds where appropriate

sensing/preprocessor/pointcloud/pointcloud_preprocessor/CMakeLists.txt
In porting `sensing_launch`, I ran into a linker error with this [commit](https://github.com/tier4/autoware_launcher.iv.universe/pull/14/commits/c94ed6920fa4a2aab52e9246555c855a9ef4f13d)
```
[component_container-1] [INFO] [1606769855.352323941] [ray_ground_filter]: Filter (as Component) successfully created with the following parameters:
[component_container-1]  - approximate_sync : false
[component_container-1]  - use_indices      : false
[component_container-1]  - latched_indices  : false
[component_container-1]  - max_queue_size   : 3
[component_container-1] /opt/ros/foxy/lib/rclcpp_components/component_container: symbol lookup error: /home/frederik.beaujean/AutowareArchitectureProposal/install/pointcloud_preprocessor/lib/libray_ground_filter.so: undefined symbol: …
```
=> Pointcloud preprocessor link opencv

localization/pose_estimator/ndt_scan_matcher/ndt_omp/CMakeLists.txt
As mentioned in #139. The `ndt_omp` package is using some compilation flags that are tied to x86 architecture causing the package to fail building on arm64. The PR enables the compilation options when building on x86
=> Compilation fix for arm architecture

planning/scenario_planning/parking/astar_search/CMakeLists.txt, planning/scenario_planning/parking/astar_search/include/astar_search/astar_search.hpp, planning/scenario_planning/parking/astar_search/include/astar_search/helper.hpp, planning/scenario_planning/parking/astar_search/package.xml, planning/scenario_planning/parking/astar_search/src/astar_search.cpp
clang-tidy also pointed out that the `fmod` function is not `constexpr`, so the function will never return a `constexpr` value.
=> Enable lints in astar_search

planning/scenario_planning/common/motion_velocity_optimizer/CMakeLists.txt, planning/scenario_planning/common/motion_velocity_optimizer/include/motion_velocity_optimizer/interpolate.hpp, planning/scenario_planning/common/motion_velocity_optimizer/include/motion_velocity_optimizer/motion_velocity_optimizer.hpp, planning/scenario_planning/common/motion_velocity_optimizer/include/motion_velocity_optimizer/motion_velocity_optimizer_utils.hpp, planning/scenario_planning/common/motion_velocity_optimizer/include/motion_velocity_optimizer/optimizer/l2_pseudo_jerk_optimizer.hpp, planning/scenario_planning/common/motion_velocity_optimizer/include/motion_velocity_optimizer/optimizer/linf_pseudo_jerk_optimizer.hpp, planning/scenario_planning/common/motion_velocity_optimizer/include/motion_velocity_optimizer/optimizer/optimizer_base.hpp, planning/scenario_planning/common/motion_velocity_optimizer/package.xml, planning/scenario_planning/common/motion_velocity_optimizer/scripts/closest_velocity_checker.py, planning/scenario_planning/common/motion_velocity_optimizer/scripts/trajectory_visualizer.py, planning/scenario_planning/common/motion_velocity_optimizer/src/interpolate.cpp, planning/scenario_planning/common/motion_velocity_optimizer/src/motion_velocity_optimizer.cpp, planning/scenario_planning/common/motion_velocity_optimizer/src/motion_velocity_optimizer_utils.cpp, planning/scenario_planning/common/motion_velocity_optimizer/src/optimizer/pseudo_jerk_l2_optimizer.cpp, planning/scenario_planning/common/motion_velocity_optimizer/src/optimizer/pseudo_jerk_linf_optimizer.cpp
This was a lot of work.
clang-tidy pointed out a missing virtual desctructor, a missing "explicit" on a constructor, and the use of a float variable in a for loop, but I left that in since it seems harmless.
@TakaHoribe FYI, I think the scripts still use `rospy`, not `rclpy`.
=> Enable lints in motion_velocity_optimizer

vehicle/remote_cmd_converter/CMakeLists.txt, vehicle/remote_cmd_converter/include/remote_cmd_converter/node.hpp, vehicle/remote_cmd_converter/package.xml, vehicle/remote_cmd_converter/src/main.cpp, vehicle/remote_cmd_converter/src/node.cpp
Relatively straightforward linter addition as this is a small packages.
```
colcon build --packages-up-to remote_cmd_converter --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```
```
colcon test --packages-select remote_cmd_converter && colcon test-result --verbose
```
```
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/vehicle/remote_cmd_converter/src/*
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/vehicle/remote_cmd_converter/include/*
```
=> ROS2 Linting: remote_cmd_converter

vehicle/raw_vehicle_cmd_converter/CMakeLists.txt, vehicle/raw_vehicle_cmd_converter/include/raw_vehicle_cmd_converter/accel_map.hpp, vehicle/raw_vehicle_cmd_converter/include/raw_vehicle_cmd_converter/brake_map.hpp, vehicle/raw_vehicle_cmd_converter/include/raw_vehicle_cmd_converter/csv_loader.hpp, vehicle/raw_vehicle_cmd_converter/include/raw_vehicle_cmd_converter/interpolate.hpp, vehicle/raw_vehicle_cmd_converter/include/raw_vehicle_cmd_converter/node.hpp, vehicle/raw_vehicle_cmd_converter/package.xml, vehicle/raw_vehicle_cmd_converter/src/accel_map.cpp, vehicle/raw_vehicle_cmd_converter/src/brake_map.cpp, vehicle/raw_vehicle_cmd_converter/src/csv_loader.cpp, vehicle/raw_vehicle_cmd_converter/src/interpolate.cpp, vehicle/raw_vehicle_cmd_converter/src/main.cpp, vehicle/raw_vehicle_cmd_converter/src/node.cpp
Add and process linters for `raw_vehicle_cmd_converter`. This package had no issues with `ament_cmake_cppcheck` so I went ahead and just did the entire `ament_lint_common` linters. It was straightforward.
```
colcon build --packages-up-to raw_vehicle_cmd_converter --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```
```
colcon test --packages-select raw_vehicle_cmd_converter && colcon test-result --verbose
```
```
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/vehicle/raw_vehicle_cmd_converter/src/*
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/vehicle/raw_vehicle_cmd_converter/include/* …
```
=> ROS2 Linting: raw_vehicle_cmd_converter

vehicle/util/vehicle_info_util/CMakeLists.txt, vehicle/util/vehicle_info_util/include/vehicle_info_util/vehicle_info.hpp, vehicle/util/vehicle_info_util/package.xml, vehicle/util/vehicle_info_util/src/vehicle_info.cpp
Small and straightforward lint of the `vehicle_info_util` package.
```
colcon build --packages-up-to vehicle_info_util --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```
```
colcon test --packages-select vehicle_info_util && colcon test-result --verbose
```
```
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/vehicle/util/vehicle_info_util/src/*
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/vehicle/util/vehicle_info_util/include/*
```
=> ROS2 Linting: vehicle_info_util

common/util/rviz_plugins/autoware_perception_rviz_plugin/CMakeLists.txt, common/util/rviz_plugins/autoware_perception_rviz_plugin/plugins/plugin_description.xml, common/util/rviz_plugins/autoware_planning_rviz_plugin/CMakeLists.txt, common/util/rviz_plugins/autoware_planning_rviz_plugin/plugins/plugin_description.xml
There is a bug in rviz_plugins where it fails to load in RVIZ2.
For example when you add "Path" tools in display panel by clicking "Add" -> "By Display Type" -> "autoware_rviz_plugin/Path", it outputs error that it cannot find library.
This PR fixes the error.
=> Fix rviz plugins

perception/object_recognition/detection/shape_estimation/CMakeLists.txt, perception/object_recognition/detection/shape_estimation/package.xml, perception/object_recognition/detection/shape_estimation/src/corrector/normal/bus_corrector.cpp, perception/object_recognition/detection/shape_estimation/src/filter/bus_filter.cpp, perception/object_recognition/detection/shape_estimation/src/filter/car_filter.cpp, perception/object_recognition/detection/shape_estimation/src/filter/truck_filter.cpp, perception/object_recognition/detection/shape_estimation/src/model/yaw_fixed/bounding_box.cpp
Some variables where uninitialized and were giving warnings. Initialized them to zero.
Not sure if it is correct. 
Also removed variables that were not used.
=> adding linters to shape_estimation

planning/scenario_planning/scenario_selector/src/scenario_selector_node/scenario_selector_node.cpp
This fixes timer frequency of scenario_selector.
The parameter "rate" is wrongly used as "period" when configuring timer.
=> [scenario_selector_node] fix timer frequency

sensing/preprocessor/gnss/geo_pos_conv/CMakeLists.txt, sensing/preprocessor/gnss/geo_pos_conv/include/geo_pos_conv/geo_pos_conv.hpp, sensing/preprocessor/gnss/geo_pos_conv/package.xml, sensing/preprocessor/gnss/geo_pos_conv/src/geo_pos_conv.cpp
Small and straightforward lint of the `geo_pos_conv` package. I converted the `CMakelist.txt` to use `ament_cmake_auto`. 
Notes to Reviewer:
* Most of the changes here is converting `(double)` to `static_cast<double>()`. Please ensure that brackets are placed correctly.
```
colcon build --packages-up-to geo_pos_conv --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```
```
colcon test --packages-select geo_pos_conv && colcon test-result --verbose
```
```
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/sensing/preprocessor/gnss/geo_pos_conv/include/geo_pos_conv/geo_pos_conv.hpp
clang-tidy -p …
```
=> ROS2 Linting: geo_pos_conv

sensing/preprocessor/gnss/gnss_poser/CMakeLists.txt, sensing/preprocessor/gnss/gnss_poser/include/gnss_poser/convert.hpp, sensing/preprocessor/gnss/gnss_poser/include/gnss_poser/gnss_poser_core.hpp, sensing/preprocessor/gnss/gnss_poser/include/gnss_poser/gnss_stat.hpp, sensing/preprocessor/gnss/gnss_poser/package.xml, sensing/preprocessor/gnss/gnss_poser/src/gnss_poser_core.cpp
Small and straightforward lint of the `gnss_poser` package. There is a TODO with no description - should this be removed? I added "user" so the linter would not complain.
```
colcon build --packages-up-to gnss_poser --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```
```
colcon test --packages-select gnss_poser && colcon test-result --verbose
```
```
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/sensing/preprocessor/gnss/gnss_poser/include/gnss_poser/*
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/sensing/preprocessor/gnss/gnss_poser/src/gnss_poser_core.cpp
```
=> ROS2 Linting: gnss_poser

perception/object_recognition/tracking/multi_object_tracker/CMakeLists.txt, perception/object_recognition/tracking/multi_object_tracker/package.xml, perception/object_recognition/tracking/multi_object_tracker/src/multi_object_tracker_core.cpp
`clang-tidy` flags an error in `multi_object_tracker_core.cpp`. But it is a false positive, so ignored it.
=> adding linters to multi_object_tracker

control/mpc_follower/launch/mpc_follower.launch.xml
The namespace of launch files does not reflect the original ROS1 launch file.
Inserting `/` at the beginning of topic makes it global namespace, but some of the topics were remapped within the local namespace(`~`) in the original code.
=> [mpc_follower] fix namespace of topic names in launch file

planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/data_manager.hpp, planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/src/node.cpp
Some of the nodes had comparison of rclcpp::Time with difference clock source, which outputs error when it tries to do comparison or subtraction operations.
=> [lane_change_planner] [obstacle_avoidance_planner] fix clock type

control/latlon_muxer/CMakeLists.txt
This package already had all the linters, I only added the stricter C++ options to CMake
=> Add strict C++14 features to CMake

planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/CMakeLists.txt, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/data_manager.hpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/lane_changer.hpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/parameters.hpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/route_handler.hpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/state/aborting_lane_change.hpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/state/blocked_by_obstacle.hpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/state/common_functions.hpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/state/executing_lane_change.hpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/state/following_lane.hpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/state/forcing_lane_change.hpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/state/state_base_class.hpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/state/stopping_lane_change.hpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/state_machine.hpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/utilities.hpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/package.xml, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/data_manager.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/lane_change_planner_node.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/lane_changer.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/route_handler.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/state/aborting_lane_change.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/state/blocked_by_obstacle.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/state/common_functions.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/state/executing_lane_change.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/state/following_lane.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/state/forcing_lane_change.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/state/state_base_class.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/state/stopping_lane_change.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/state_machine.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/utilities.cpp
The linters found a few issues (missing explicit constructor, non-virtual destructor in virtual base class).
=> Enable lints in lane_change_planner

planning/scenario_planning/parking/costmap_generator/CMakeLists.txt, planning/scenario_planning/parking/costmap_generator/include/costmap_generator/costmap_generator.hpp, planning/scenario_planning/parking/costmap_generator/include/costmap_generator/object_map_utils.hpp, planning/scenario_planning/parking/costmap_generator/include/costmap_generator/objects_to_costmap.hpp, planning/scenario_planning/parking/costmap_generator/include/costmap_generator/points_to_costmap.hpp, planning/scenario_planning/parking/costmap_generator/nodes/costmap_generator/costmap_generator_node.cpp, planning/scenario_planning/parking/costmap_generator/nodes/costmap_generator/main.cpp, planning/scenario_planning/parking/costmap_generator/nodes/costmap_generator/object_map_utils.cpp, planning/scenario_planning/parking/costmap_generator/nodes/costmap_generator/objects_to_costmap.cpp, planning/scenario_planning/parking/costmap_generator/nodes/costmap_generator/points_to_costmap.cpp, planning/scenario_planning/parking/costmap_generator/package.xml
The usual: Many header guards and includes needed fixing. clang-tidy found nothing in this package.
=> Enable lints in costmap_generator

perception/object_recognition/tracking/multi_object_tracker/src/multi_object_tracker_core.cpp
This fixes the bug in setting timer period.
Original code is using publish_rate directly as period instead of taking inverse.
=> [multi_object_tracker] fix bug in calculating timer period

planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/data_manager.hpp
This was already merged in https://github.com/tier4/Pilot.Auto/pull/183/files, but was reverted in https://github.com/tier4/Pilot.Auto/pull/150 when conflict was resolved.
=> [lane_change_planner] fix clock type when BoolStamped is initialized

perception/object_recognition/prediction/map_based_prediction/launch/map_based_prediction.launch.xml
This adds remapping arguments for output topic so that the topic can be remapped when it is called from another launch file.
=> add remapping option for the launch file in map_based_prediction

system/system_monitor/CMakeLists.txt, system/system_monitor/include/system_monitor/utils.hpp, system/system_monitor/package.xml
Add linter tests to `system_monitor` package. 
```
colcon build --packages-up-to system_monitor --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```
```
colcon test --packages-select system_monitor && colcon test-result --verbose
```
```
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/system/system_monitor/src/cpu_monitor/*
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/system/system_monitor/src/gpu_monitor/* (error finding nvml.h)
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/system/system_monitor/src/hdd_monitor/* 
clang-tidy -p build/compile_commands.json …
```
=> ROS2 Linting: system_monitor

system/util/dummy_diag_publisher/CMakeLists.txt, system/util/dummy_diag_publisher/package.xml
Add linter tests to `dummy_diag_publisher` package. 
```
colcon build --packages-up-to dummy_diag_publisher --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```
```
colcon test --packages-select dummy_diag_publisher && colcon test-result --verbose
```
```
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/system/util/dummy_diag_publisher/src/dummy_diag_publisher_node/*
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/system/util/dummy_diag_publisher/include/dummy_diag_publisher/*
```
=> ROS2 Linting: dummy_diag_publisher

system/emergency_handler/CMakeLists.txt, system/emergency_handler/package.xml
Add linter tests to `emergency_handler` package. 
```
colcon build --packages-up-to emergency_handler --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```
```
colcon test --packages-select emergency_handler && colcon test-result --verbose
```
```
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/system/emergency_handler/src/*
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/system/emergency_handler/include/emergency_handler/*
```
=> ROS2 Linting: emergency_handler

common/math/osqp_interface/CMakeLists.txt, common/math/osqp_interface/include/osqp_interface/csc_matrix_conv.hpp, common/math/osqp_interface/package.xml
Simple lint of the `osqp_interface` package. 
```
colcon build --packages-up-to osqp_interface --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```
```
colcon test --packages-select osqp_interface && colcon test-result --verbose
```
```
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/common/math/osqp_interface/src/*
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/common/math/osqp_interface/include/osqp_interface/*
```
=> ROS2 Linting: osqp_interface

system/autoware_error_monitor/CMakeLists.txt, system/autoware_error_monitor/package.xml
Add linter tests to `autoware_error_monitor` package. 
```
colcon build --packages-up-to autoware_error_monitor --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```
```
colcon test --packages-select autoware_error_monitor && colcon test-result --verbose
```
```
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/system/autoware_error_monitor/src/*
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/system/autoware_error_monitor/include/autoware_error_monitor/autoware_error_monitor_core.hpp
```
=> ROS2 Linting: autoware_error_monitor

control/velocity_controller/CMakeLists.txt, control/velocity_controller/include/velocity_controller/velocity_controller.hpp, control/velocity_controller/package.xml, control/velocity_controller/src/velocity_controller_core.cpp
In `velocity_controller_core.cpp`, I deleted two function calls whose return value was unused, plus some minor fixes.
=> Enable lints in velocity_controller

system/autoware_state_monitor/CMakeLists.txt, system/autoware_state_monitor/package.xml, system/autoware_state_monitor/src/autoware_state_monitor_node/autoware_state_monitor_node.cpp
Add linter tests to `autoware_state_monitor` package. I ended up fixing one of the warning as it was using the deprecated `ConstPtr` type.
```
colcon build --packages-up-to autoware_state_monitor --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```
```
colcon test --packages-select autoware_state_monitor && colcon test-result --verbose
```
```
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/system/autoware_state_monitor/src/autoware_state_monitor_node/*
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/system/autoware_state_monitor/include/autoware_state_monitor/
```
=> ROS2 Linting: autoware_state_monitor

perception/object_recognition/prediction/map_based_prediction/CMakeLists.txt, perception/object_recognition/prediction/map_based_prediction/include/cubic_spline.hpp, perception/object_recognition/prediction/map_based_prediction/include/map_based_prediction.hpp, perception/object_recognition/prediction/map_based_prediction/include/map_based_prediction_ros.hpp, perception/object_recognition/prediction/map_based_prediction/package.xml, perception/object_recognition/prediction/map_based_prediction/src/map_based_prediction.cpp, perception/object_recognition/prediction/map_based_prediction/src/map_based_prediction_main.cpp, perception/object_recognition/prediction/map_based_prediction/src/map_based_prediction_ros.cpp
Deleted a few unused variables & changed functions without `return` from `bool` to `void`.
I ignored the "loop variable of floating point type" from clang-tidy.
=> Enable lints in map_based_prediction

common/math/spline_interpolation/CMakeLists.txt, common/math/spline_interpolation/package.xml
Simple lint of the `spline_interpolation` package. Only changes were in package.xml where I fixed the indentation.
```
colcon build --packages-up-to spline_interpolation --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```
```
colcon test --packages-select spline_interpolation && colcon test-result --verbose
```
```
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/common/math/spline_interpolation/src/*
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/common/math/spline_interpolation/include/spline_interpolation/*
```
=> ROS2 Linting: spline_interpolation

awapi/awapi_awiv_adapter/CMakeLists.txt, awapi/awapi_awiv_adapter/package.xml
Simple lint of the `awapi_awiv_adapter` package, not changes needed apart from adding the linter tests
```
colcon build --packages-up-to awapi_awiv_adapter --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```
```
colcon test --packages-select awapi_awiv_adapter && colcon test-result --verbose
```
3. Run clang-tidy on the the source files from the root AutowareArchitectureProposal directory (this will generate warnings
```
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/awapi/awapi_awiv_adapter/src/*
```
=> ROS2 Linting: awapi_awiv_adapter

control/mpc_follower/CMakeLists.txt, control/mpc_follower/include/mpc_follower/qp_solver/qp_solver_interface.hpp, control/mpc_follower/include/mpc_follower/vehicle_model/vehicle_model_interface.hpp, control/mpc_follower/package.xml
clang-tidy again found missing virtual destructors.
=> Enable lints in mpc_follower

vehicle/as/CMakeLists.txt, vehicle/as/include/pacmod_interface/pacmod_interface.hpp, vehicle/as/include/ssc_interface/ssc_interface.hpp, vehicle/as/package.xml, vehicle/as/src/pacmod_interface/pacmod_interface.cpp, vehicle/as/src/pacmod_interface/pacmod_interface_node.cpp, vehicle/as/src/ssc_interface/ssc_interface.cpp, vehicle/as/src/ssc_interface/ssc_interface_node.cpp
Small and straightforward lint of the `as` package.
```
colcon build --packages-up-to as --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```
```
colcon test --packages-select as && colcon test-result --verbose
```
```
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/vehicle/as/src/pacmod_interface/*
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/vehicle/as/src/ssc_interface/*
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/vehicle/as/include/pacmod_interface/*
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/vehicle/as/include/ssc_interface/*
```
Note: …
=> ROS2 Linting: as

localization/pose_estimator/ndt_scan_matcher/ndt_omp/CMakeLists.txt, localization/pose_estimator/ndt_scan_matcher/ndt_omp/include/ndt_omp/ndt_omp_impl.hpp, localization/pose_estimator/ndt_scan_matcher/ndt_omp/include/ndt_omp/voxel_grid_covariance_omp_impl.hpp, localization/pose_estimator/ndt_scan_matcher/ndt_omp/package.xml
Warnings generated at multiple places by clang-tidy for this function:
```
warning: 'getFieldIndex<pcl::PointXYZ>' is deprecated: use getFieldIndex<PointT> (field_name, fields) instead [clang-diagnostic-deprecated-declarations]
rgba_index = pcl::getFieldIndex(*input_, "rgb", fields);
```
=> adding linters to ndt_omp

common/util/rviz_plugins/autoware_perception_rviz_plugin/CMakeLists.txt, common/util/rviz_plugins/autoware_perception_rviz_plugin/package.xml
`clang-tidy` giving warnings in some rclcpp header files.
=> adding linters to autoware_perception_rviz_plugin

localization/pose_estimator/ndt_scan_matcher/ndt_scan_matcher/include/ndt_scan_matcher/util_func.hpp
fixed `clang-tidy` errors in headers
=> fixing clang-tidy errors in ndt_scan_matcher

localization/util/autoware_localization_srvs/CMakeLists.txt, localization/util/autoware_localization_srvs/package.xml
`clang-tidy` giving errors. Not sure if they are relevant.
```
Error while processing /home/nithilan/AutowareArchitectureProposal/src/autoware/pilot.auto/localization/util/autoware_localization_srvs/srv/PoseWithCovarianceStamped.srv.
/home/nithilan/AutowareArchitectureProposal/src/autoware/pilot.auto/localization/util/autoware_localization_srvs/srv/PoseWithCovarianceStamped.srv:1:3: error: invalid preprocessing directive [clang-diagnostic-error]
^
/home/nithilan/AutowareArchitectureProposal/src/autoware/pilot.auto/localization/util/autoware_localization_srvs/srv/PoseWithCovarianceStamped.srv:2:1: error: unknown type name 'uint32' [clang-diagnostic-error]
uint32 seq
^
/home/nithilan/AutowareArchitectureProposal/src/autoware/pilot.auto/localization/util/autoware_localization_srvs/srv/PoseWit …
```
=> adding linters to autoware_localization_srvs

simulator/util/dummy_perception_publisher/CMakeLists.txt, simulator/util/dummy_perception_publisher/package.xml
Ignored `clang-tidy` warnings in rclcpp headers.
Also there was a warning about using `double` type variable as loop counter in for loop.
=> adding linters to dummy_perception_publisher

awapi/autoware_api_msgs/CMakeLists.txt, awapi/autoware_api_msgs/package.xml
Simple lint of the `autoware_api_msgs` package.
```
colcon build --packages-up-to autoware_api_msgs --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```
```
colcon test --packages-select autoware_api_msgs && colcon test-result --verbose
```
3. No C++ so no clang-tidy needed
=> ROS2 Linting: autoware_api_msgs

sensing/preprocessor/pointcloud/pointcloud_preprocessor/src/ground_filter/ray_ground_filter_nodelet.cpp
This fixes the issue that output message has correct frame id.
=> [ray_ground_filter] overwrite frame_id of output_msg with base_frame_

vehicle/as/include/pacmod_interface/pacmod_interface.hpp, vehicle/as/launch/pacmod_interface.launch.xml, vehicle/as/package.xml, vehicle/as/src/pacmod_interface/pacmod_interface.cpp
Fix pacmod interface to use vehicle_info_util::VehicleInfo class instead of accessing to global parameter which is not available in ros2.
=> [pacmod_interface] fix vehicle_info parameter loading

localization/util/autoware_localization_rviz_plugin/initial_pose_button_panel/CMakeLists.txt, localization/util/autoware_localization_rviz_plugin/initial_pose_button_panel/package.xml, localization/util/autoware_localization_rviz_plugin/initial_pose_button_panel/plugins/plugin_description.xml, localization/util/autoware_localization_rviz_plugin/initial_pose_button_panel/src/initial_pose_button_panel.cpp, localization/util/autoware_localization_rviz_plugin/initial_pose_button_panel/src/initial_pose_button_panel.hpp
Port `initial-pose-button-panel` to ROS2.
To note:
- As the [client call](https://github.com/tier4/Pilot.Auto/pull/125/files#diff-37aff11e5ae763f660e9df6c6df2d63aeac085d24eeb967d1ce3971493337c44R128) is non-blocking now I've moved the intialization of the button inside the request scope otherwise it'll be initalized before getting a response. 
=> Port initial-pose-button-panel

common/util/rviz_plugins/autoware_perception_rviz_plugin/CMakeLists.txt, common/util/rviz_plugins/autoware_perception_rviz_plugin/package.xml
Fix library declaration in CMakeLists.txt.
How to review:
Make sure that you can load autoware_perception_rviz_plugin tools(e.g. CarInitialPoseTool) in rviz without error.
=> [autoware_perception_rviz_plugin] make plugin library SHARED

planning/scenario_planning/parking/freespace_planner/src/freespace_planner/freespace_planner_node.cpp
Adds missing declaration of `is_completed` parameter in freespace_planner.
Without this declaration, the node dies when it tries to set the undeclared parameter.
=> [freespace_planner] add missing declaration of parameter

perception/object_recognition/detection/lidar_apollo_instance_segmentation/CMakeLists.txt, perception/object_recognition/detection/lidar_apollo_instance_segmentation/include/lidar_apollo_instance_segmentation/cluster2d.hpp, perception/object_recognition/detection/lidar_apollo_instance_segmentation/package.xml
Getting errors in headers while running `clang-tidy `
```
lidar_apollo_instance_segmentation/src/cluster2d.cpp:47:10: error: 'lidar_apollo_instance_segmentation/cluster2d.hpp' file not found [clang-diagnostic-error]
#include "lidar_apollo_instance_segmentation/cluster2d.hpp"
```
Even though the headers are available.
=> adding linters to lidar_apollo_instance_segmentation

perception/object_recognition/detection/euclidean_cluster/launch/euclidean_cluster.launch.xml, perception/object_recognition/detection/euclidean_cluster/launch/voxel_grid_based_euclidean_cluster.launch.xml, perception/object_recognition/detection/roi_cluster_fusion/launch/roi_cluster_fusion.launch.xml
- Fix for `roi_cluster_fusion` launch
- Add comment on `euclidean_cluster` launch which is not ported to ros2. Since this launch file uses a nodelet and the priority is low, I just leave a comment and create an issue for this launch file.
=> Fix perception launches

system/autoware_state_monitor/config/autoware_state_monitor.planning_simulation.yaml
This fixes parameter for planning simulator.
How to test:
`ros2 launch autoware_state_monitor autoware_state_monitor.launch.xml config_file:=<path/to/autoware_state_monitor.planning_simulation.yaml>`
=> fix parameter in autoware_state_monitor.planning_simulation.yaml

perception/traffic_light_recognition/traffic_light_classifier/src/cnn_classifier.cpp
- launch cnn classfier
`ros2 launch traffic_light_classifier traffic_light_classifier.launch.xml use_gpu:=true`
- check if engine file is in the package share directory
`ls install/traffic_light_classifier/share/traffic_light_classifier/data/traffic_light_classifier_mobilenetv2.engine`
=> traffic_light_classifier: Fix engine save dir

system/autoware_state_monitor/config/autoware_state_monitor.planning_simulation.yaml, system/autoware_state_monitor/config/autoware_state_monitor.yaml, system/autoware_state_monitor/src/autoware_state_monitor_node/autoware_state_monitor_node.cpp
Fix minor issues in `autoware_state_monitor`
1. Disable /vehicle_info param check since we don't have global /vehicle_info in ROS2 implementation.
2. Fix rate to 10hz as intended.
3. Fix uninitialized currrent_time.
4. Fix to subscribe latched route msg
=> Modify autoware state monitor

localization/twist_estimator/pose2twist/src/pose2twist_core.cpp
Fix to calculate accurate dt in `double` data type. Current implementation calculate dt in `int` data type.
ref: https://github.com/tier4/AutowareArchitectureProposal.iv/blob/ros2/localization/pose_estimator/ndt_scan_matcher/ndt_scan_matcher/include/ndt_scan_matcher/util_func.hpp#L124
=> Fix dt in pose2twist

sensing/preprocessor/gnss/gnss_poser/CMakeLists.txt
This fixes missing link to Geographic lib package.
It has been tested with an actual sensor data.
=> [gnss_poser] fix link to Geographiclib

control/mpc_follower/include/mpc_follower/mpc_follower_core.hpp
Resolve std::runtime_error below.
```
[mpc_follower-27] terminate called after throwing an instance of 'std::runtime_error'
[mpc_follower-27]   what():  can't subtract times with different time sources [1 != 2]
```
=> [mpc follower]: fix timesource

awapi/awapi_awiv_adapter/Readme.md, awapi/awapi_awiv_adapter/launch/awapi_awiv_adapter.launch.xml, common/msgs/autoware_control_msgs/CMakeLists.txt, common/msgs/autoware_control_msgs/msg/EngageMode.msg, common/msgs/autoware_vehicle_msgs/CMakeLists.txt, common/msgs/autoware_vehicle_msgs/msg/Engage.msg, common/util/web_controller/autoware_web_controller/www/autoware_web_controller/js/autoware_engage.js, control/vehicle_cmd_gate/include/vehicle_cmd_gate/vehicle_cmd_gate.hpp, control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp, simulator/simple_planning_simulator/CMakeLists.txt, simulator/simple_planning_simulator/include/simple_planning_simulator/simple_planning_simulator_core.hpp, simulator/simple_planning_simulator/package.xml, simulator/simple_planning_simulator/src/simple_planning_simulator_core.cpp, system/autoware_state_monitor/include/autoware_state_monitor/autoware_state_monitor_node.hpp, system/autoware_state_monitor/include/autoware_state_monitor/state_machine.hpp, system/autoware_state_monitor/src/autoware_state_monitor_node/autoware_state_monitor_node.cpp, system/autoware_state_monitor/src/autoware_state_monitor_node/state_machine.cpp, vehicle/as/include/pacmod_interface/pacmod_interface.hpp, vehicle/as/include/ssc_interface/ssc_interface.hpp, vehicle/as/src/pacmod_interface/pacmod_interface.cpp, vehicle/as/src/ssc_interface/ssc_interface.cpp
* Use autoware_vehicle_msgs/msg/Engage instead of autoware_control_msgs/msg/EngageMode.
* Remove std_msgs from as.
=> Ros2 v0.8.0 engage

planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp
The process has died during a simple test in planing_simulation at Kashiwanoha.
Please check if finishing the simple test in planning_simulation.
=> fix boost_none handling

control/trajectory_follower/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp, control/vehicle_cmd_gate/CMakeLists.txt, control/vehicle_cmd_gate/include/vehicle_cmd_gate/vehicle_cmd_gate.hpp, control/vehicle_cmd_gate/package.xml, control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/include/lane_change_planner/lane_changer.hpp, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/package.xml, planning/scenario_planning/lane_driving/behavior_planning/lane_change_planner/src/lane_changer.cpp, simulator/simple_planning_simulator/CMakeLists.txt, simulator/simple_planning_simulator/include/simple_planning_simulator/simple_planning_simulator_core.hpp, simulator/simple_planning_simulator/include/simple_planning_simulator/vehicle_model/sim_model_constant_acceleration.hpp, simulator/simple_planning_simulator/include/simple_planning_simulator/vehicle_model/sim_model_ideal.hpp, simulator/simple_planning_simulator/include/simple_planning_simulator/vehicle_model/sim_model_interface.hpp, simulator/simple_planning_simulator/include/simple_planning_simulator/vehicle_model/sim_model_time_delay.hpp, simulator/simple_planning_simulator/include/simple_planning_simulator/vehicle_model/sim_model_util.hpp, simulator/simple_planning_simulator/launch/simple_planning_simulator.launch.py, simulator/simple_planning_simulator/launch/simple_planning_simulator.launch.xml, simulator/simple_planning_simulator/package.xml, simulator/simple_planning_simulator/scripts/fitParamDelayInputModel.py, simulator/simple_planning_simulator/src/simple_planning_simulator_core.cpp, simulator/simple_planning_simulator/src/simple_planning_simulator_node.cpp, simulator/simple_planning_simulator/src/vehicle_model/sim_model_constant_acceleration.cpp, simulator/simple_planning_simulator/src/vehicle_model/sim_model_ideal.cpp, simulator/simple_planning_simulator/src/vehicle_model/sim_model_interface.cpp, simulator/simple_planning_simulator/src/vehicle_model/sim_model_time_delay.cpp, simulator/simple_planning_simulator/src/vehicle_model/sim_model_util.cpp, system/autoware_state_monitor/src/autoware_state_monitor_node/autoware_state_monitor_node.cpp
- Update the method of getting vehicle info
- Add latch option to vector-map subscriber / GenericSubscription used by autoware_state_monitor
(The subscription of autoware_state_monitor includes vector-map / pointcloud map)
#How to check
```
$ros2 launch autoware_launch planning_simulator.launch.xml vehicle_model:=lexus vehicle_id:=default sensor_model:=aip_xx1 map_path:=[MAP PATH]
```
Check with merging the related PR https://github.com/tier4/autoware_launcher.iv.universe/pull/64
Item to check
- No following error message: [control.trajectory_follower.lane_departure_checker_node]: waiting for lanelet_map msg...
- No significant understeer on the curve
（*There are many changes in this PR, but most of them are related to lint correction.）
=> Ros2 v0.8.0 fix packages

system/system_monitor/package.xml
Fix compilation error
>AutowareArchitectureProposal.proj/src/autoware/AutowareArchitectureProposal.iv/system/system_monitor/include/system_monitor/cpu_monitor/cpu_monitor_base.hpp:28:10: fatal error: diagnostic_updater/diagnostic_updater.hpp: そのようなファイルやディレクトリはありません
28 | #include "diagnostic_updater/diagnostic_updater.hpp"
=> Fix dependency of system_monitor

system/autoware_state_monitor/src/autoware_state_monitor_node/state_machine.cpp
Fixed an issue that Autoware state did not change from *waitingForEngage* when /autoware/engage:true is published
(implementing miss: https://github.com/tier4/AutowareArchitectureProposal.iv/blob/master/system/autoware_state_monitor/src/autoware_state_monitor_node/state_machine.cpp#L276-L278 )
=> fix implement miss in autoware_state_monitor

system/autoware_error_monitor/config/diagnostic_aggregator/sensing.param.yaml, system/autoware_state_monitor/config/autoware_state_monitor.param.yaml, system/autoware_state_monitor/config/autoware_state_monitor.planning_simulation.param.yaml, system/autoware_state_monitor/include/autoware_state_monitor/autoware_state_monitor_node.hpp, system/autoware_state_monitor/include/autoware_state_monitor/config.hpp, system/autoware_state_monitor/src/autoware_state_monitor_node/autoware_state_monitor_node.cpp, system/emergency_handler/launch/emergency_handler.launch.xml, system/emergency_handler/src/emergency_handler/emergency_handler_core.cpp, system/emergency_handler/src/state_timeout_checker/state_timeout_checker_core.cpp, vehicle/remote_cmd_converter/launch/remote_cmd_converter.launch.xml
Fixed the cause of /autoware/state becoming Emergency
```
$ros2 launch autoware_launch planning_simulator.launch.xml vehicle_model:=lexus vehicle_id:=default sensor_model:=aip_xx1 map_path:=[MAP_PATH]
Set initial pose and goal pose
$ros2 topic echo /autoware/state # check state
```
=> Ros2 v0.8.0 fix packages2

planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/launch/obstacle_avoidance_planner.launch.xml, planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/launch/surround_obstacle_checker.launch.xml, vehicle/as/launch/pacmod_interface.launch.xml
Almost other packages use `vehicle_param_file`, 
but several packages use `vehicle_info_param`.
So this pr aims to make a consistent expression to `vechile_param_file`
=> rename vehicle_info_param to vehicle_param_file

system/emergency_handler/src/emergency_handler/emergency_handler_core.cpp
Fixed implement miss
Original(correct): Autoware_state does not transition to emergency state when current state is  INITIALIZING_VEHICLE, WAITING_FOR_ROUTE, etc.
Missing implementation:  Autoware_state can transition to emergency state only when current state is  INITIALIZING_VEHICLE, WAITING_FOR_ROUTE, etc.
=> fix emergency handler

sensing/preprocessor/pointcloud/pointcloud_preprocessor/src/concatenate_data/concatenate_data_nodelet.cpp
I fixed concatenate_data bug.
I've got this error when input nullptr as a publish message at here https://github.com/tier4/AutowareArchitectureProposal.iv/blob/9a32729ef7d3d8bdbd9ab4189184aab58d78d093/sensing/preprocessor/pointcloud/pointcloud_preprocessor/src/concatenate_data/concatenate_data_nodelet.cpp#L269
```
[component_container-3] terminate called after throwing an instance of 'rclcpp::exceptions::RCLInvalidArgument'
[component_container-3]   what():  failed to publish message: ros_message argument is null, at /tmp/binarydeb/ros-foxy-rcl-1.1.10/src/rcl/publisher.c:317`
```
=> add nullptr check when publish concatenate data

common/msgs/autoware_system_msgs/CMakeLists.txt, common/msgs/autoware_system_msgs/msg/TimeoutNotification.msg, common/msgs/autoware_system_msgs/msg/TimeoutNotificationStamped.msg, system/emergency_handler/include/emergency_handler/emergency_handler_core.hpp, system/emergency_handler/include/emergency_handler/state_timeout_checker_core.hpp, system/emergency_handler/src/emergency_handler/emergency_handler_core.cpp, system/emergency_handler/src/state_timeout_checker/state_timeout_checker_core.cpp
rm std_msgs
```
ros2 node info /emergency_handler
/emergency_handler
Subscribers:
/autoware/driving_capability: autoware_system_msgs/msg/DrivingCapability
/autoware/state: autoware_system_msgs/msg/AutowareState
/control/current_gate_mode: autoware_control_msgs/msg/GateMode
/control/vehicle_cmd: autoware_vehicle_msgs/msg/VehicleCommand
/is_state_timeout: autoware_system_msgs/msg/TimeoutNotificationStamped
/localization/twist: geometry_msgs/msg/TwistStamped
/parameter_events: rcl_interfaces/msg/ParameterEvent
Publishers:
/diagnostics_err: diagnostic_msgs/msg/DiagnosticArray
/parameter_events: rcl_interfaces/msg/ParameterEvent
/rosout: rcl_interfaces/msg/Log
/system/emergency/control_cmd: autoware_control_msgs/msg/ControlCommandStamped
/system/emergency/hazard_status: …
```
=> add timeout notification stamp msgs

map/map_loader/src/lanelet2_map_loader/lanelet2_map_visualization.cpp
This improves visualization of path/trajectory markers which is currently hidden by lanelet2 map visualization markers.
before: 
after:
=> [map_loader] modify colors for lane markers for better visualization

common/util/rviz_plugins/autoware_planning_rviz_plugin/src/tools/max_velocity.cpp, planning/scenario_planning/common/motion_velocity_optimizer/src/motion_velocity_optimizer.cpp
Fix the bug that the max velocityis not visualized in rviz.
=> fix max velocity visualization

planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/src/node.cpp
Fix implement miss in obstacle_stop_planner.
https://github.com/tier4/AutowareArchitectureProposal.iv/blob/master/planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/src/node.cpp#L193
(At the current code, the trajectory is not extended regardless of the value of stop_planner.extend_distance)
=> fix obstacle_stop_planner

system/topic_state_monitor/launch/topic_state_monitor.launch.xml
Fix launch file of topic_state_monitor
(Fix bug that all the node-names of topic_state_monitor are the same.)
("node_name_suffix" become a mandatory option in the process of fixing bugs
=> fix launch file of topic_state_montior

system/emergency_handler/src/state_timeout_checker/state_timeout_checker_core.cpp
Fix parameter name of state_timeout_checker
$ros2 param get /system/state_timeout_checker timeout.InitializingVehicle
=> fix param name

system/autoware_state_monitor/src/autoware_state_monitor_node/state_machine.cpp
Change wait time for autoware-state transition from Planning to WaitForEngage (1.0s->3.0s).
If _autoware-state_ transitions to WaitForEngage while the _topic_state_monitor_ node has NoReceived error yet, _autoware-state_ quickly becomes Emergency. So, set enough time for autoware-state to transition to WaitForEngage
=> change wait time for state transition

system/emergency_handler/src/emergency_handler/emergency_handler_core.cpp
Add timeout_ignore_state to emergency_handler.
When _is_in_timeout_ignore_state_ is True (autoware/state is INITIALIZING_VEHICLE), _hazard_status.level_ does not become ERROR by timeout of topics such as driving_capability.
The reason for the above change is that frequencies of these topics become unstable soon after starting Autoware.
=> add timeout_ignore_state to emergency_handler

common/util/autoware_utils/include/autoware_utils/ros/self_pose_listener.hpp, common/util/autoware_utils/include/autoware_utils/ros/transform_listener.hpp
This resolves console spam errors like this.
```sh
[lane_departure_checker_node-43] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[lane_departure_checker_node-43]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.9/src/buffer_core.cpp
[lane_departure_checker_node-43] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[lane_departure_checker_node-43]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.9/src/buffer_core.cpp
[lane_departure_checker_node-43] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[lane_departure_checker_node-43]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.9/src/buffer_core.cpp …
```
=> Fix autoware_utils

sensing/preprocessor/pointcloud/pointcloud_preprocessor/src/concatenate_data/concatenate_data_nodelet.cpp, sensing/preprocessor/pointcloud/pointcloud_preprocessor/src/crop_box_filter/crop_box_filter_nodelet.cpp
```
ros2 launch sensing_launch sensing.launch.xml sensor_model:=aip_xx1 vehicle_param_file:=src/description/vehicle/lexus_description/config/vehicle_info.param.yaml vehicle_mirror_param_file:=src/description/vehicle/lexus_description/config/mirror.param.yaml
ros2 topic list
```
```
/sensing/lidar/concat_num
/sensing/lidar/not_subscribed_topic_name
/sensing/lidar/front_left/crop_box_polygon
```
```
/sensing/lidar/concatenate_data/concat_num
/sensing/lidar/concatenate_data/not_subscribed_topic_name
/sensing/lidar/front_left/mirror_crop_box_filter/crop_box_polygon
/sensing/lidar/front_left/self_crop_box_filter/crop_box_polygon
```
=> Fix topic name in pointcloud preprocessor

vehicle/as/src/pacmod_interface/pacmod_interface.cpp, vehicle/as/src/ssc_interface/ssc_interface.cpp
Fix typo in the vehicle module. `/vehcle/engage` seems to be problematic.
=> Fix typo in vehicle module

map/map_loader/src/pointcloud_map_loader/pointcloud_map_loader_node.cpp
Fix typo in the map module. This typo might be bug-prone.
=> Fix typo in map module

system/autoware_error_monitor/config/diagnostic_aggregator/sensing.param.yaml, system/autoware_state_monitor/config/autoware_state_monitor.param.yaml, system/system_monitor/include/system_monitor/utils.hpp, system/system_monitor/src/net_monitor/net_monitor.cpp
Fix typo in system module.
@ito-san 
The followings are just my humble suggestion. Do you have any other good words to replace them?
- entried -> appended
- spinned -> spin()
=> Fix typo in system module

map/lanelet2_extension/lib/visualization.cpp
Remove Route Area Error at containg empty points marker
=> avoid pushing empty marker

control/mpc_follower/README.md, control/mpc_follower/cfg/MPCFollower.cfg, control/mpc_follower/config/mpc_follower.param.yaml, control/mpc_follower/include/mpc_follower/mpc_follower_core.hpp, control/mpc_follower/src/mpc_follower_core.cpp, control/trajectory_follower/lane_departure_checker/include/lane_departure_checker/lane_departure_checker_node.hpp, control/trajectory_follower/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp
Fix typo in the control module.
Please merge this with the following pull request simultaneously.
https://github.com/tier4/autoware_launcher.iv.universe/pull/91
=> Fix typo in control module

sensing/preprocessor/image/image_transport_decompressor/src/nodelet.cpp
There is a typo in licence, I fixed it.
=> fix licence typo in image_transport_decompressor

control/vehicle_cmd_gate/launch/vehicle_cmd_gate.launch.xml, control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
- launch vehicle cmd gate
`ros2 launch vehicle_cmd_gate vehicle_cmd_gate.launch.xml vehicle_param_file:=/home/daisuke/workspace/AutowareArchitectureProposal/src/description/vehicle/lexus_description/config/vehicle_info.param.yaml`
- check service name
```
❯ ros2 service list
/vehicle_cmd_gate/clear_external_emergency_stop
/vehicle_cmd_gate/describe_parameters
/vehicle_cmd_gate/external_emergency_stop
/vehicle_cmd_gate/get_parameter_types
/vehicle_cmd_gate/get_parameters
/vehicle_cmd_gate/list_parameters
/vehicle_cmd_gate/set_parameters
/vehicle_cmd_gate/set_parameters_atomically
```
=> Ros2 fix service name

localization/pose_estimator/ndt_scan_matcher/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp, localization/util/autoware_localization_srvs/srv/PoseWithCovarianceStamped.srv, localization/util/pose_initializer/src/pose_initializer_core.cpp
Fix this runtime error.
```
[ndt_scan_matcher-34] terminate called after throwing an instance of 'std::runtime_error'
[ndt_scan_matcher-34]   what():  No InputSource
```
=> Ros2 fix ndt align srv

system/system_monitor/include/system_monitor/utils.hpp
- In ROS2, `diagnostic_updater::Updater` calls `update()` using timer.
https://github.com/ros/diagnostics/blob/foxy/diagnostic_updater/include/diagnostic_updater/diagnostic_updater.hpp#L486-L494
-  The function `spin_and_update()` calls `update() `manually.
-  `rclcpp::spin_some()` in `spin_and_update()` executes `update()` using timer.
- So, duplicated `update()` calls are made.
=> Remove unnecessary diagnostic update.

control/mpc_follower/config/plot_juggler_mpc_follower.xml, control/velocity_controller/config/plot_juggler_velocity_controller.xml
Add config files of plot-juggler (mpc_follower, velocity_controller)
- sudo apt install ros-foxy-plotjuggler-ros
- sudo apt install ros-foxy-plotjuggler
- ros2 launch autoware_launch planning_simulator.launch.xml vehicle_model:=lexus vehicle_id:=default sensor_model:=aip_xx1 map_path:=MAP_PATH
- ros2 run plotjuggler plotjuggler
- Push this button at the top left of the window and load the config files (plot_juggler_mpc_follower.xml or plot_juggler_velocity_controller.xml)
- When loading config files, Set "maximum size of arrays" to 100
- Confirm each graph is plotted normally.
=> add config files of plotjuggler

planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/src/scene_module/traffic_light/scene.cpp
Fix traffic light module
- run the following scenario.
https://github.com/tier4/AutonomousDrivingScenarios/blob/master/odd3/scenario/UC-001-0009/PSim_1/UC-001-0009_PSim_1_case1.yaml
(Before merging this PR, the process of behavior_velocity_planner is killed soon after sending traffic_light_status)
=> fix traffic light module

planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp
Fix bug:
use _state_transit_margin_time_ parameter properly in intersection planner.
=> set transit_margin_time to intersect. planner

control/mpc_follower/launch/mpc_follower.launch.xml, control/pure_pursuit/launch/pure_pursuit.launch.xml, control/trajectory_follower/lane_departure_checker/launch/lane_departure_checker.launch.xml, control/trajectory_follower/obstacle_collision_checker/launch/obstacle_collision_checker.launch.xml, control/vehicle_cmd_gate/launch/vehicle_cmd_gate.launch.xml, control/velocity_controller/launch/velocity_controller.launch.xml, planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/launch/behavior_velocity_planner.launch.xml, planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/launch/obstacle_avoidance_planner.launch.xml, planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/launch/obstacle_stop_planner.launch.xml, planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/launch/surround_obstacle_checker.launch.xml, simulator/simple_planning_simulator/launch/simple_planning_simulator.launch.py, simulator/simple_planning_simulator/launch/simple_planning_simulator.launch.xml, vehicle/as/launch/pacmod_interface.launch.xml, vehicle/util/vehicle_info_util/include/vehicle_info_util/vehicle_info.hpp, vehicle/util/vehicle_info_util/src/vehicle_info.cpp, vehicle/vehicle_description/util/vehicle_info_param_server/CMakeLists.txt, vehicle/vehicle_description/util/vehicle_info_param_server/include/vehicle_info_param_server/vehicle_info_param_server_core.hpp, vehicle/vehicle_description/util/vehicle_info_param_server/launch/vehicle_info_param_server.launch.xml, vehicle/vehicle_description/util/vehicle_info_param_server/package.xml, vehicle/vehicle_description/util/vehicle_info_param_server/src/vehicle_info_param_server_core.cpp, vehicle/vehicle_description/util/vehicle_info_param_server/src/vehicle_info_param_server_node.cpp
Add vehicle_info_param_server.
- vehicle_info_param_server node sets rosparameter for all necessary nodes.
- Delete unnecessary vehicle_param_file parameter described in Launch files.
```
$ros2 launch autoware_launch planning_simulator.launch.xml vehicle_model:=lexus vehicle_id:=default sensor_model:=aip_xx1 map_path:=MAP_PATH
```
- Set initial_pose and goal_pose
- publish autoware/engage and check that the vehicle works normally.
=> Ros2 vehicle info param server

system/system_monitor/README.md, system/system_monitor/reader/hdd_reader/hdd_reader.cpp
- Update the launch command
- Fix some issues detected by Coverity Scan
- Resource leak (`new_sock`)
- Uninitialized variables
- Improper null termination (`buf`)
- Ref. [CWE-170](https://cwe.mitre.org/data/definitions/170.html)
- Almost all cases seem to be no problem, but just in case fixed it
- Fix some issues detected by Clang-Tidy
- Deprecated headers
- Use `using` instead of `typedef`
- Redundant `void`
- Use range-based `for`
- Unused namespace alias
- Use `nullptr` instead of `0` to initialize pointers
Do __not__ fix the other issues, for example:
- Use `std::array<>` instead of C-style array
- Do not use pointer arithmetic
- Do not use reinterpret_cast
- etc.
```shell
sudo systemctl restart hdd.service
ros2 launch system_monitor system_monitor.launch.xml
ros2 run …
```
=> Fix issues in hdd_reader

map/lanelet2_extension/lib/autoware_osm_parser.cpp
AutowareOsmParser is changed point value after RTree is constructed. https://github.com/tier4/AutowareArchitectureProposal.iv/blob/2328f517117a2f5f540ee5080a48748a1c2aa60f/map/lanelet2_extension/lib/autoware_osm_parser.cpp#L38-L45
For reindex RTree, construct LaneletMap class again after overwrite points as local one.
=> fix: re-construct laneletMapLayer for reindex RTree

common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/steering_angle.cpp, common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/steering_angle.hpp
Restores MFD superclass for SteeringAngle plugin. 
Moves rendering to update() function called from the Display superclass in the rendering thread. This fixes the issue.
Note that other plugins can be similarly modified.
=> Rviz overlay render fix

common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/console_meter.cpp, common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/console_meter.hpp, common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/steering_angle.cpp, common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/steering_angle.hpp, common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/turn_signal.cpp, common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/turn_signal.hpp, common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/velocity_history.cpp, common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/velocity_history.hpp
#461 changes applied to other plugins as well. Apply once 461 is merged.
Also, includes a bit of cleaning (removed a bunch of unnecessary includes and some dead code).
Note that there is a high degree of code repetition in the package (between different plugins) and perhaps it would be good to address that (with a dedicated superclass, utils and similar).
=> Rviz overlay render in update

system/autoware_state_monitor/Readme.md, system/autoware_state_monitor/include/autoware_state_monitor/autoware_state.hpp, system/autoware_state_monitor/include/autoware_state_monitor/autoware_state_monitor_node.hpp, system/autoware_state_monitor/include/autoware_state_monitor/state_machine.hpp, system/autoware_state_monitor/launch/autoware_state_monitor.launch.xml, system/autoware_state_monitor/package.xml, system/autoware_state_monitor/src/autoware_state_monitor_node/autoware_state_monitor_node.cpp, system/autoware_state_monitor/src/autoware_state_monitor_node/state_machine.cpp
support .auto msg
autoware_planning_msgs/msg/route -> autoware_auto_planning_msgs/msg/route
autoware_planning_msgs/msg/trajectory -> autoware_auto_planning_msgs/msg/trajectory
autoware_system_msgs/msg/autoware_state -> autoware_auto_system_msgs/msg/autoware_state
autoware_system_msgs/msg/engage -> autoware_auto_system_msgs/msg/engage
autoware_system_msgs/msg/hazard_status_stamped -> autoware_auto_system_msgs/msg/hazard_status_stamped
autoware_vehicle_msgs/msg/control_mode -> autoware_auto_vehicle_msgs/msg/vehicle_state_report
geometry_msgs/msg/twist_stamped -> nav_msgs/msg/odomtery
- add readme (from scratch)
~- Handling of string message in original AutowareState.msg~
~- Handling of Emergency state in original AutowareState.msg~
**PR Author should check the checkboxes below when creating …
=> [autoware state monitor] support autoware.auto msg

planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/Readme.md, planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/launch/behavior_path_planner.launch.xml, planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/launch/behavior_velocity_planner.launch.xml, planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/README.md, planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/launch/obstacle_stop_planner.launch.xml, planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/src/node.cpp, planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/README.md, planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/launch/surround_obstacle_checker.launch.xml, planning/scenario_planning/parking/freespace_planner/README.md, planning/scenario_planning/parking/freespace_planner/launch/freespace_planner.launch.xml, planning/scenario_planning/scenario_selector/README.md, planning/scenario_planning/scenario_selector/launch/dummy_scenario_selector_lane_driving.launch.xml, planning/scenario_planning/scenario_selector/launch/dummy_scenario_selector_parking.launch.xml
=> rename topic name twist -> odometry

planning/scenario_planning/common/external_velocity_limit_selector/README.md, planning/scenario_planning/common/motion_velocity_smoother/README.md, planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/README.md, planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/README.md, planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/README.md, planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/surround_obstacle_checker-design.ja.md, planning/scenario_planning/scenario_selector/README.md
In planning README.md, I updated iv_msgs -> auto_msgs
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuid …
=> update iv_msgs -> auto_msgs in planning readme

vehicle/as/include/pacmod_interface/pacmod_interface.hpp, vehicle/as/package.xml, vehicle/as/src/pacmod_interface/pacmod_interface.cpp
.auto porting of as
**pacmode_interfaceのみの変更**
**PR外のTODO**
autoware_vehicle_msgs/msg/の以下が残り
- ActuationCommandStamped
- ActuationStatusStamped
- VehicleEmergencyStamped
**turn signal**
前提として、もともとは
- .iv: ウィンカーをつけてる間トピックを送り続ける
- .auto: ウィンカーをつける瞬間、消す瞬間のみトピックを送る
auto_msgsはウィンカーをつける、消す瞬間に対応するためにENABLE/DISABLE形式
堀部さん高木さんの議論のもと、今回の変更では.ivの今までのロジック・実装(ウィンカーをつけている間トピックを送り続ける)は変えずに、auto_msgsのENABLE/DISABLEを使う(ENABLE=ONの状態, DISABLE=OFFの状態として扱う)
**トピック名の変更**
https://docs.google.com/presentation/d/1sPrbHOoptGKNibJzgC_OENAy_EZHrWvjJCNDESUJtiw/edit#slide=id.g1009677dfcf_2_0
NOTE:
turn_signal -> turn_indicators + hazard_lights
**PR Author should check the checkboxes …
=> .auto porting as

common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/console_meter.cpp, common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/console_meter.hpp, common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/velocity_history.cpp, common/util/rviz_plugins/autoware_vehicle_rviz_plugin/src/tools/velocity_history.hpp, planning/mission_planning/mission_planner/src/mission_planner_lanelet2/mission_planner_lanelet2.cpp, planning/route_handler/include/route_handler/route_handler.hpp, planning/route_handler/src/route_handler.cpp, simulator/simple_planning_simulator/launch/simple_planning_simulator.launch.py
Fix some packages
comment out Control module in planning_simulator.launch.xml
comment out scenario_planning_module in planning.launch.xml
comment out dummy_perception module in simulator.launch.xml
change simple_planning_simulator.launch.xml to simple_planning_simulator.launch.py in simulator.launch.xml
```
diff --git a/autoware_launch/launch/planning_simulator.launch.xml b/autoware_launch/launch/planning_simulator.launch.xml
index 8738ca0..4ed7d38 100644
--- a/autoware_launch/launch/planning_simulator.launch.xml
+++ b/autoware_launch/launch/planning_simulator.launch.xml
@@ -46,12 +46,6 @@
<include file="$(find-pkg-share planning_launch)/launch/planning.launch.xml">
</include>
-  
-  <include file="$(find-pkg-share control_launch)/launch/control.launch.py">
-    
-    <arg …
```
=> [autoware_vehicle_rviz_plugin/route_handler/simple_planning_simulator]fix some packages

control/trajectory_follower/include/trajectory_follower/mpc.hpp, control/trajectory_follower/src/mpc.cpp, control/trajectory_follower/test/test_mpc.cpp, control/trajectory_follower_nodes/CMakeLists.txt, control/trajectory_follower_nodes/include/trajectory_follower_nodes/lateral_controller_node.hpp, control/trajectory_follower_nodes/include/trajectory_follower_nodes/longitudinal_controller_node.hpp, control/trajectory_follower_nodes/src/lateral_controller_node.cpp, control/trajectory_follower_nodes/src/longitudinal_controller_node.cpp, control/trajectory_follower_nodes/test/test_lateral_controller_node.cpp, control/trajectory_follower_nodes/test/test_longitudinal_controller_node.cpp
This PR changes the interface of nodes in the `trajectory_follower_nodes` package to use `VehicleOdometry` and `SteeringReport` instead of `VehicleKinematicState`.
The tests of the `trajectory_follower` and `trajectory_follower_nodes` are also restored and fixed.
- **Check spelling**: NOT required to pass before the merge. It is up …
=> Fix message interface and tests of 'trajectory_follower_nodes'

control/external_cmd_selector/include/external_cmd_selector/external_cmd_selector_node.hpp, control/external_cmd_selector/package.xml, control/external_cmd_selector/src/external_cmd_selector/external_cmd_selector_node.cpp
Depends on this pr https://github.com/tier4/autoware_iv_msgs/pull/64
port
pending since there are no compatible msgs in autoware.auto
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some …
=> port part of external_cmd_selector

perception/object_recognition/detection/lidar_apollo_instance_segmentation/README.md
Update README.md for lidar apollo instance segmentation.
[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyG …
=> Update document for lidar apollo instance segmentation

control/trajectory_follower_nodes/src/lateral_controller_node.cpp, control/trajectory_follower_nodes/test/test_lateral_controller_node.cpp, control/trajectory_follower_nodes/test/trajectory_follower_test_utils.hpp
sometimes CI fail by pub/sub and is depend on machine power
```
1: [ RUN      ] FakeNodeFixture.longitudinal_emergency
Error: OR] [1637094206.261132890] [longitudinal_controller]: [Emergency stop] vel: 0.000, acc: -0.100
1: [       OK ] FakeNodeFixture.longitudinal_emergency (232 ms)
1: [ RUN      ] FakeNodeFixture.longitudinal_set_param_smoke_test
1: [       OK ] FakeNodeFixture.longitudinal_set_param_smoke_test (138 ms)
1: [----------] 17 tests from FakeNodeFixture (6915 ms total)
1: 
1: [----------] Global test environment tear-down
1: [==========] 17 tests from 1 test suite ran. (6916 ms total)
1: [  PASSED  ] 16 tests.
1: [  FAILED  ] 1 test, listed below:
1: [  FAILED  ] FakeNodeFixture.stopped
1: 
1:  1 FAILED TEST
1:   YOU HAVE 1 DISABLED TEST
1: 
```
fix gtest for latlon muxer …
=> [latlon muxer] fix gtest

control/trajectory_follower_nodes/include/trajectory_follower_nodes/lateral_controller_node.hpp, control/trajectory_follower_nodes/param/lateral_controller_defaults.yaml, control/trajectory_follower_nodes/src/lateral_controller_node.cpp
Sync trajectory_follower and trajectory_follower_nodes with mpc_follower. …
=> Sync trajectory_follower_nodes 

planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/src/scene_module/occlusion_spot/scene_occlusion_spot_in_private_road.cpp, planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/src/scene_module/occlusion_spot/scene_occlusion_spot_in_public_road.cpp
Fix occlusion spot.
1. In calcSlowDownPointsForPossibleCollision, longitudinal speeds of path are used. But all longitudinal speeds of `interp_path` are 0 m/s because these are not interpolated.
2. In calcSlowDownPointsForPossibleCollision, closest_idx is used. This closest_idx is calculated using not `interp path` but `path`. 
Therefore, `path` should be used here.
Check following.
Before merging this PR.
Occlusion spot inserts stop point(= point with 0 m/s speed)
Occulsion spot inserts deceleration point
- …
=> [behavior velocity planner]fix occlusion spot

control/trajectory_follower_nodes/src/lateral_controller_node.cpp, control/trajectory_follower_nodes/test/test_lateral_controller_node.cpp, control/trajectory_follower_nodes/test/trajectory_follower_test_utils.hpp
I was trying to figure out why gtests were sometimes failing on CI.
As a result, I determined that I need to fix the testing method.
The `trajectory_follower` assumes that there are enough messages in the `tf_buffer` before the trajectory message is received.
In our tests, we did not process messages using `spin_some()` after `sendTransform()`. This caused a problem where the order of arrival of the messages was swapped, especially under heavy CPU load, and the current position in `trajectory_follower` could not be obtained.
To fix this, I added a `spin_some()` and debug messages.
To check this issue on local environment, follow this step:
Terminal1:
`stress-ng -c 8 -l 90`
This simulates 90% CPU load, each core. (note that my CPU has 8 cores. Edit this option if you need.)
Terminal2: …
=> Fix unstable test in trajectory_follower_nodes

map/map_loader/script/map_hash_generator
update map_hash_generator to publish pcd map hash.
https://github.com/tier4/AutowareArchitectureProposal_launcher/pull/142
https://github.com/tier4/autoware_api_msgs/pull/42
https://github.com/tier4/AutowareArchitectureProposal_api_msgs/pull/1
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). …
=> add pcd map hash generator

control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp
lane_departure_checkerにおいて、routeトピックのsubscriberのdurabilityがtransient_localになっていなかったため、トピックの取りそこねが発生する可能性があったので修正 …
=> use transient_local to subscribe `/planning/mission_planning/route`

localization/pose_estimator/ndt_scan_matcher/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.hpp, localization/pose_estimator/ndt_scan_matcher/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp, localization/pose_estimator/ndt_scan_matcher/ndt_scan_matcher/src/ndt_scan_matcher_node.cpp
To execute callbackInitialPose in parallel with other callback function, the followings will be introduced after merging this PR.
* `MultiThreadedExecutor`
* Two callback group
* one for callbackInitialPose ( `initial_pose_callback_group` )
* the other for other callback functions ( `main_sub_opt.callback_group` )
Please check the following
* Successfully running Autoware with any rosbag file.
* Increased called count for `callbackInitialPose`
To count how many times `callbackInitialPose` is called, Perf is recommended to measure briefly.
Executing the following command during Autoware's running
```
perf stat -p `pgrep ndt` -- sleep 60
```
The following result is sample result which I got with Intel Xeon 2278GE, NVIDIA RTX2060S.
```
14,636.55 msec task-clock                #    0.244 CPUs …
```
=> separate callback group to execute callbackInitialPose in parallel

planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/test/src/test_state_machine.cpp
add more details for gtest
sync 
https://github.com/autowarefoundation/autoware.universe/pull/147
see CI resutl …
=> add verb and loop counter for check

common/util/rviz_plugins/autoware_state_rviz_plugin/src/autoware_state_panel.cpp, common/util/rviz_plugins/autoware_state_rviz_plugin/src/autoware_state_panel.hpp
https://github.com/tier4/autoware.iv/pull/2406 のポーティングPRです
変更内容が上記PRと同じであること …
=> state_rviz_plugin: visualize selector mode and add disengage function
